### PR TITLE
fix(legal): Use a heart image with a permissive license

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

The welcome heart image in our `main` branch uses the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/deed.en) licence. This licence requires that modified versions are published under the same licence, in some circumstances.

This license term might not be acceptable to some Zebra users. It might also raise concerns among some users, or go against the open source software policies of some companies.

I'm not a lawyer, and I don't think it's worth consulting a lawyer for this, when there is an easily available alternative with a more acceptable licence.

(Edited to clarify.)

## Solution

Use a heart image that is in the public domain. (No license conditions.)

## Review

This is a release blocker, because it might stop some Zebra users upgrading to the next release.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by teor2345** [comment]
Before this PR and PR #7095:
Screenshot 2023-06-29 at 10 05 24

After this PR:
Screenshot 2023-06-29 at 10 12 32

**Comment by str4d** [comment]
> The welcome heart image in our `main` branch uses the [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/deed.en) licence, which requires the source code of derivative works to be shared.

Are you suggesting that due to the inclusion of this image, `zcashd` or `zebrad` binaries, along with subsequent downstream derivatives, are required to be licensed as CC-BY-SA 3.0? That is not my reading of the license.

The license text spends a lot of time defining "Work" in a way that clearly does not cover the source code to a working software implementation of the Zcash consensus rules (and the version 3.0 license was released in 2007, so the authors clearly could have referenced software source code or binaries if they had intended to cover them):
> 1. h. "Work" means the literary and/or artistic work offered under the terms of this License including without limitation any production in the literary, scientific and artistic domain, whatever may be the mode or form of its expression including digital form, such as a book, pamphlet and other writing; a lecture, address, sermon or other work of the same nature; a dramatic or dramatico-musical work; a choreographic work or entertainment in dumb show; a musical composition with or without words; a cinematographic work to which are assimilated works expressed by a process analogous to cinematography; a work of drawing, painting, architecture, sculpture, engraving or lithography; a photographic work to which are assimilated works expressed by a process analogous to photography; a work of applied art; an illustration, map, plan, sketch or three-dimensional work relative to geography, topography, architecture or science; a performance; a broadcast; a phonogram; a compilation of data to the extent it is protected as a copyrightable work; or a work performed by a variety or circus performer to the extent it is not otherwise considered a literary or artistic work.

The ASCII art rendering of the image is clearly an Adaption, but given how Work was defined, the fact that the ASCII art happens to be stored as text inside the `zcashd` or `zebrad` source code should not cause the entire binary to be an Adaption:
> 1. a. "Adaptation" means a work based upon the Work, or upon the Work and other pre-existing works, such as a translation, adaptation, derivative work, arrangement of music or other alterations of a literary or artistic work, or phonogram or performance and includes cinematographic adaptations or any other form in which the Work may be recast, transformed, or adapted including in any form recognizably derived from the original, except that a work that constitutes a Collection will not be considered an Adaptation for the purpose of this License. For the avoidance of doubt, where the Work is a musical work, performance or phonogram, the synchronization of the Work in timed-relation with a moving image ("synching") will be considered an Adaptation for the purpose of this License.

The inclusion of the ASCII art inside the `zcashd` or `zebrad` binary would therefore be to Distribute or Publicly Perform it:
> 1. d. "Distribute" means to make available to the public the original and copies of the Work or Adaptation, as appropriate, through sale or other transfer of ownership.
>    j. "Publicly Perform" means to perform public recitations of the Work and to communicate to the public those public recitations, by any means or process, including by wire or wireless means or public digital performances; to make available to the public Works in such a way that members of the public may access these Works from a place and at a place individually chosen by them; to perform the Work to the public by any means or process and the communication to the public of the performances of the Work, including by public digital performance; to broadcast and rebroadcast the Work by any means including signs, sounds or images.

The closest I can find to a "source code availability" requirement is (in bold):
> 4. b. You may Distribute or Publicly Perform an Adaptation only under the terms of: (i) this License; (ii) a later version of this License with the same License Elements as this License; (iii) a Creative Commons jurisdiction license (either this or a later license version) that contains the same License Elements as this License (e.g., Attribution-ShareAlike 3.0 US)); (iv) a Creative Commons Compatible License. If you license the Adaptation under one of the licenses mentioned in (iv), you must comply with the terms of that license. If you license the Adaptation under the terms of any of the licenses mentioned in (i), (ii) or (iii) (the "Applicable License"), you must comply with the terms of the Applicable License generally and the following provisions: (I) You must include a copy of, or the URI for, the Applicable License with every copy of each Adaptation You Distribute or Publicly Perform; (II) You may not offer or impose any terms on the Adaptation that restrict the terms of the Applicable License or the ability of the recipient of the Adaptation to exercise the rights granted to that recipient under the terms of the Applicable License; (III) You must keep intact all notices that refer to the Applicable License and to the disclaimer of warranties with every copy of the Work as included in the Adaptation You Distribute or Publicly Perform; **(IV) when You Distribute or Publicly Perform the Adaptation, You may not impose any effective technological measures on the Adaptation that restrict the ability of a recipient of the Adaptation from You to exercise the rights granted to that recipient under the terms of the Applicable License.** This Section 4(b) applies to the Adaptation as incorporated in a Collection, but this does not require the Collection apart from the Adaptation itself to be made subject to the terms of the Applicable License.

The rendered screen trivially satisfies this: the ASCII art is copy-pasteable directly from the terminal. But even if a downstream wanted to render in a different way, if you can see the ASCII art rendered, you can (with some effort) recover the corresponding ASCII text, so it not being copy-pasteable isn't a blocker.

In any case, the ASCII art only occurs inside source code files that are part of the final `zcashd` or `zebrad` binary, so any licensing concern is irrelevant to anyone using the Zebra libraries.

**Comment by teor2345** [comment]
> Are you suggesting that due to the inclusion of this image, `zcashd` or `zebrad` binaries, along with subsequent downstream derivatives, are required to be licensed as CC-BY-SA 3.0? That is not my reading of the license.

I don't want to have to care about the details, and I don't want our users to have to care either.

I'll amend what I wrote to say the licence could raise concerns, or go against some companies' open source software policies.

**Review by conradoplg — APPROVED** [review]
The asymmetry bothered me a bit until I realized the Zebra logo is even more asymmetrical :laughing:

**Pull request merged**
