### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Review by jvff — APPROVED** [review]

**Comment by jvff** [comment]
Thank you very much for these fixes! :smile:

**Comment by upbqdn** [comment]
May I ask what tool you used?

**Comment by rex4539** [comment]
> May I ask what tool you used?

https://github.com/codespell-project/codespell

**Comment by oxarbitrage** [comment]
> https://github.com/codespell-project/codespell

I think is possible to add a spell checker (not sure which one) into the CI and make a pull request fail when new spelling issues are introduced. I am pretty sure i saw this in some other project. We could consider to do some research on that when we get the time.

**Comment by teor2345** [comment]
> > https://github.com/codespell-project/codespell
> 
> I think is possible to add a spell checker (not sure which one) into the CI and make a pull request fail when new spelling issues are introduced. I am pretty sure i saw this in some other project. We could consider to do some research on that when we get the time.

The tricky part of this change is adding a dictionary with Zcash-specific words, Rust-specific words, and engineering-specific words. Otherwise the spelling CI might fail every time we add a new feature or design.

**Comment by upbqdn** [comment]
> The tricky part of this change is adding a dictionary with Zcash-specific words, Rust-specific words, and engineering-specific words. Otherwise the spelling CI might fail every time we add a new feature or design.

@teor2345, I looked at the tool Dimitris used. It looks for common (a lot of) misspellings instead of checking dictionary membership. Here's the relevant description:

> It does not check for word membership in a complete dictionary, but instead looks for a set of common misspellings. Therefore it should catch errors like "adn", but it will not catch "adnasdfasdf". This also means it shouldn't generate false-positives when you use a niche term it doesn't know about.

Here are the misspellings https://github.com/codespell-project/codespell/tree/master/codespell_lib/data

We could even add ours if we find a common one. I think it's cool.

**Pull request merged**
