### PR TITLE
build(deps): bump zcash_proofs from 0.8.0 to 0.9.0 and zcash_primitives from 0.8.1 to 0.9.0

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

We want to update these at the same time.

Replaces https://github.com/ZcashFoundation/zebra/pull/5627 and https://github.com/ZcashFoundation/zebra/pull/5628

## Review

Anyone can review

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [x] Does the code do what the ticket and PR says?
  - [x] How do you know it works? Does it have tests?

### CODE REVIEW

**Review by dconnolly — DISMISSED** [review]
🎉

**Comment by gustavovalverde** [comment]
@mergifyio update

**Comment by arya2** [comment]
ssh failure: 

> gcloud compute ssh fully-synced-rpc-5631-merge-7cd38d3 --project=zealous-zebra --zone=us-central1-a --troubleshoot
> 
> Or, to investigate an IAP tunneling issue:
> 
> gcloud compute ssh fully-synced-rpc-5631-merge-7cd38d3 --project=zealous-zebra --zone=us-central1-a --troubleshoot --tunnel-through-iap
> 
> ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
> Error: Process completed with exit code 255.

https://github.com/ZcashFoundation/zebra/actions/runs/3481795921/jobs/5824112862#step:9:116

**Comment by arya2** [comment]
@Mergifyio update

**Comment by arya2** [comment]
@Mergifyio update

**Review by dconnolly — APPROVED** [review]
The approvals will continue until ssh improves 🫠

**Comment by mpguerra** [comment]
@mergifyio update

**Comment by arya2** [comment]
get_block_template test failed with:

>    Message:  negating a NonNegative amount always results in a valid NegativeOrZero: Constraint { value: 43740, range: -2100000000000000..=0 }
>    Location: zebra-rpc/src/methods/get_block_template_rpcs/types/transaction.rs:105

https://github.com/ZcashFoundation/zebra/actions/runs/3498079512/jobs/5859110894#step:6:264

**Pull request merged**
