### PR TITLE
Wrap Blocks in Arc throughout codebase

### LINKED ISSUE #416: replace `Box<Block>` with `Arc<Block>`
following on to this, there should be an issue to replace `Box<Block>` with `Arc<Block>`

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/414/files_

### PR DESCRIPTION
**Pull request by yaahc**
fixes https://github.com/ZcashFoundation/zebra/issues/416

### CODE REVIEW

**Comment by yaahc** [comment]
@hdevalence do you think we might want to also Arc-ify `Transaction`s?

**Comment by hdevalence** [comment]
Yeah, I think `Arc`ing transactions would be good too, they can be quite large. Could be a separate PR.

**Review by hdevalence — APPROVED** [review]
LGTM

**Review by dconnolly — APPROVED** [review]
👍 

i want an arc reactor emoji

**Pull request merged**
