### PR TITLE
change(log): Log loaded config path when Zebra starts up

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

1. We need to check the correct Docker config is loaded in ticket #5168
2. Users need to know what config they are loading so they can debug config issues

## Solution

- Log the config path and fields for all Zebra server commands
- Remove a duplicate config fields log for the start command

## Review

Anyone can review this routine PR.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

Testing in #5168

### CODE REVIEW

**Comment by teor2345** [comment]
Some Docker workflows failed due to some temporary docker registry downtime. Feel free to restart them, or I'll do it when the rest of the jobs finish.

**Review by arya2 — APPROVED** [review]
Looks good!

**Comment by teor2345** [comment]
Merge queue failed due to #5384

**Comment by teor2345** [comment]
@mergifyio refresh

**Review by gustavovalverde — APPROVED** [review]

**Pull request merged**
