### PR TITLE
T1. add(test): add test API that checks logs for multiple regexes

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We want to check lightwalletd logs and Zebra logs for failures like:
- missing RPCs
- RPC argument parse errors
- RPC argument data errors
- RPC response parse errors
- RPC response data errors
- other specific errors logged by lightwalletd

But our testing framework makes it very hard to do that.

This PR makes it easier to check `lightwalletd` logs for multiple regexes.

This is related to:
- #3500 
- #3856 
- #3511

### Regex API Reference

https://docs.rs/regex/latest/regex/struct.RegexSet.html#

### Designs

Add convenience traits for converting and collecting regular expression sets.

## Solution

- Make test log checks accept generic regexes, and convert them automatically
- Support matching multiple regexes internally in the test command

Related Bug Fixes:
- Fix a potential hang in test child error reports 

Documentation:
- Document test command structs

## Review

This PR is not urgent.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

- Use regexes to check all log output for failures

### CODE REVIEW

**Comment by oxarbitrage** [comment]
@mergifyio update

**Comment by oxarbitrage** [comment]
I cherry-picked the 7 commits that were really from this PR and force pushed because github was including here commits from https://github.com/ZcashFoundation/zebra/pull/3901, making the review harder. It seems there was some sort of issue with the automatic rebase.

**Review by oxarbitrage — DISMISSED** [review]

**Comment by teor2345** [comment]
> I cherry-picked the 7 commits that were really from this PR and force pushed because github was including here commits from #3901, making the review harder. It seems there was some sort of issue with the automatic rebase.

GitHub's automatic rebase doesn't handle squashed PRs when there is any kind of conflict.

But `git rebase --onto main` works if you have set the upstream branches.
Otherwise I use `git rebase --interactive` and just delete the squashed commits.

**Comment by teor2345** [comment]
It seems like there was also a problem finding the CI disks, I'm not sure what happened there. Maybe it happened due to the merge conflict, or the GitHub automatic rebase.

**Comment by teor2345** [comment]
@mergifyio update

**Review by oxarbitrage — APPROVED** [review]

**Pull request merged**
