### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Review by oxarbitrage — APPROVED** [review]
Thanks!

**Comment by teor2345** [comment]
This PR needs to be admin-merged due to some bugs in our CI config.

But let's wait until after all the high-priority PRs merge.

**Comment by teor2345** [comment]
We're going to use this PR to test forked repositories in CI, so we're going to delay merging it until #3885 is merged.

**Comment by gustavovalverde** [comment]
@Mergify update

**Pull request merged**
