### PR TITLE
zebrad 1.0.0-alpha.3 Release

### PR DESCRIPTION
**Pull request by teor2345**
## Initial Testing

- [ ] After any changes, test that the `cargo install` command in `README.md` works (use `--path` instead of `--git` locally)

### Which Crates to Increment

To check if any of the top-level crates need version increments, go to the zebra GitHub code page: https://github.com/ZcashFoundation/zebra

- [x] Increment the crates that have new commits since the last version update
- [x] Increment any crates that depend on crates that have changed
- [x] Use the `zebrad` crate version in the `zebrad` app code and `zebra-network` user agent
- [x] Use the latest git tag in `README.md`

### How to Increment Versions

Zebra follows [semantic versioning](https://semver.org).

Semantic versions look like:
`MAJOR`.`MINOR`.`PATCH[`-`TAG`.`PRE-RELEASE]`

#### Pre-Release Crates

Pre-Release versions have a `TAG` like "alpha" or "beta".
For example: "1.0.0-alpha.0"

1. Increment the `PRE-RELEASE` version for the crate.

Optionally, if a `MINOR` feature pre-release breaks `MAJOR` API compatibility:
2. Increment the `MAJOR` version, and reset all the other versions to zero

#### Unstable Crates

Unstable versions have a `MAJOR` version of zero.
For example: "0.1.0"

1. Follow stable crate versioning, but increment the `MINOR` version for breaking changes

#### Stable Crates

For example: "1.0.0"

Increment the first version component in this list, and reset the other components to zero:
1. MAJOR versions for breaking public API changes and removals
  * check for types from dependencies that appear in the public API
2. MINOR versions for new features
3. PATCH versions for bug fixes
  * includes dependency updates that don't impact the public API

### Version Locations

Once you know which versions you want to increment, you can find them in the:
- [x] zebra* `Cargo.toml`s
- [x] tower-* `Cargo.toml`s
- [x] `zebrad` app code: https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/components/tracing/component.rs
- [x] `zebra-network` protocol user agent: https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/constants.rs
- [x] `README.md`

Merge all these version increments as one commit, by squashing and rebasing the PR onto the main branch.

#### Version Tooling

You can use `fastmod` to interactively find and replace versions.

For example, for `zebra-1.0.0-alpha-3`, we did:
```
fastmod --extensions rs,toml,md --fixed-strings '1.0.0-alpha.3' '1.0.0-alpha.4'
fastmod --extensions rs,toml,md --fixed-strings '1.0.0-alpha.2' '1.0.0-alpha.3'
fastmod --extensions rs,toml,md --fixed-strings '0.2.0' '0.2.1' tower-batch
```

We skipped `tower-fallback`, because it hadn't changed since the last tag.

## Change Log

We follow the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format.

We use [the Release Drafter workflow](https://github.com/marketplace/actions/release-drafter) to automatically create a [draft changelog](https://github.com/ZcashFoundation/zebra/releases).

To create the final change log:
- [x] Delete any trivial changes
- [x] Combine duplicate changes
- [x] Edit change descriptions so they are consistent, and make sense to non-developers
- [x] Check the category for each change
  - prefer the "Fix" category if you're not sure

#### Change Categories

From "Keep a Changelog":
* `Added` for new features.
* `Changed` for changes in existing functionality.
* `Deprecated` for soon-to-be removed features.
* `Removed` for now removed features.
* `Fixed` for any bug fixes.
* `Security` in case of vulnerabilities.

## After merging this PR
- [x] Update the draft release with the final changelog
- [x] Point the draft release at the commit resulting from merging this PR, using the correct version tag name
- [x] Mark the release as 'pre-release' (until we are no longer alpha/beta)

## Final Testing

- [x] After tagging the release, test that the exact `cargo install` command works
      (`--git` behaves a bit differently to `--path`)

If the build fails after tagging:
1. fix the build
2. check if the fixes changed any extra crates, and do the required version increments
3. update `README.md` with a **new** git tag
4. tag **another** release

### CODE REVIEW

**Comment by teor2345** [comment]
>     * Point the GitHub changelog to the version increment commit

@dconnolly I can't remember what this means 😳

**Comment by teor2345** [comment]
## Draft Release Notes

Zebra's latest alpha brings multiple reliability and stability improvements for node startup, long-running syncs, and testing.

Some notable changes include:

## Added
- Add beta rust to CI (#1725)
- Add Usability Testing Plan GitHub issue template (#1519)
- Add Release Checklist GitHub pull request template (#1717)

## Changed
- Compute the network message body length to reduce heap allocations (#1773)
- Re-enable the macOS conflict acceptance tests (#1778)
- Re-enable coverage CI (#1758, #1787)
- Disable fail-fast in the CI test job (#1776)
- Rename responsible_disclosure.md to SECURITY.md (#1747)

## Removed
- Disable unreliable testnet large sync test (#1789)

## Fixed

### Hangs and Panics
- Refactor `connection.rs` to make `fail_with` panics impossible (#1721)
- Stop ignoring failed peer addresses (#1709)
- Retry initial peer DNS resolution on failure (#1762)
- Update tower-batch semaphore implementation (#1764)
- Use ready! in ChainVerifier::poll_ready (#1735)
- Use CallAllUnordered in peer_set::add_initial_peers (#1734)

### Testing
- Bump CI build and test timeouts to 60 minutes (#1757)
- Run CI workflow on push to main & manual request (#1748)
- Set ZEBRA_SKIP_NETWORK_TESTS using Windows syntax (#1782)
- Fix Windows build failures due to disk space (#1726)
- Fix acceptance test timeouts, cleanup, and diagnostics (#1736, #1766, #1770, #1777)

### Logging and Metrics
- Update PeerSet metrics after every change (#1727)
- Log initial peer connection failures (#1763)

**Comment by dconnolly** [comment]
> > ```
> > * Point the GitHub changelog to the version increment commit
> > ```
> 
> @dconnolly I can't remember what this means 😳

Aha, when _this commit_ is merged, point the draft release, with our edited release notes pasted in, at the new commit, and mark as 'pre-release', not draft, anymore.

**Comment by dconnolly** [comment]
> > > ```
> > > * Point the GitHub changelog to the version increment commit
> > > ```
> > 
> > 
> > @dconnolly I can't remember what this means 😳
> 
> Aha, when _this commit_ is merged, point the draft release, with our edited release notes pasted in, at the new commit, and mark as 'pre-release', not draft, anymore.

Made edits to this PR and a new one to update the template with them

**Review by dconnolly — APPROVED** [review]

**Comment by dconnolly** [comment]
> After tagging the release, test that the exact cargo install command works
(--git behaves a bit differently to --path)

Tested successfully on macOS, built v1.0.0-alpha.3, ran a good sync

**Pull request merged**
