### PR TITLE
fix(script): updates search-issue-refs to print permalinks with the latest commit sha on main

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

The search-issue-refs binary uses a hardcoded blob id for printing out permalinks to issue references. 

This PR replaces the hardcoded value so permalinks to new TODOs will be correct when we run this script in the future.

## Solution

- Get latest commit sha on main from Github REST API
- Use the latest commit sha when printing permalinks instead of a hardcoded value

## Review

Anyone can review, optional priority.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Review by teor2345 — APPROVED** [review]
I don't know much about this code, but the changes seem to match my suggestion.

**Comment by teor2345** [comment]
Failed in the merge queue due to #6498

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by oxarbitrage** [comment]
Failed again with the same https://github.com/ZcashFoundation/zebra/actions/runs/4684761663/jobs/8301221723#step:14:3059

Retrying.

**Comment by oxarbitrage** [comment]
@mergifyio refresh

**Comment by arya2** [comment]
@Mergifyio update

**Pull request merged**
