### PR TITLE
Make debug_stop_at_height and ephemeral work together

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

1. Our new RocksDB implementation doesn't flush or close before exiting on `debug_stop_at_height`
2. If `debug_stop_at_height` and `ephemeral` are both set, the database isn't deleted

## Solution

1. drop or flush the database before `debug_stop_at_height` exits Zebra
2. if `debug_stop_at_height` and `ephemeral` are set, when the stop height is reached, delete the database, then exit

The drop or flush might not be needed, because RocksDB seems to handle forced exits better than sled. But they might help us avoid lost data or failing acceptance tests.

The code in this pull request has:
  - [x] Documentation Comments
  - [x] Acceptance Tests

## Review

@yaahc wrote this code.

We're not seeing these bugs in the acceptance tests, which test the restart scenario. ~And no-one is using ephemeral and a stop height together yet.~ We use ephemeral and a stop height in the acceptance tests, but they seem to be working so far. So this review is not urgent.

### CODE REVIEW

**Comment by hdevalence** [comment]
My recollection from talking with @yaahc while pairing on some of the rocksdb work is that we don't need to explicitly flush the database, because it handles forced exits correctly.

**Comment by hdevalence** [comment]
Do we support `debug_stop_at_height` and `ephemeral` together? That option combo doesn't really make sense to me.

**Comment by teor2345** [comment]
> My recollection from talking with @yaahc while pairing on some of the rocksdb work is that we don't need to explicitly flush the database, because it handles forced exits correctly.

I haven't seen that guarantee in the Rust or C++ reference docs. Do you have a link?

The RocksDB FAQ suggests that forced exits need to be handled in our code, but it doesn't have much detail:

> Q: Is it safe to close RocksDB while another thread is issuing read, write or manual compaction requests?
> 
> A: No. The users of RocksDB need to make sure all functions have finished before they close RocksDB. You can speed up the waiting by calling CancelAllBackgroundWork().

https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ#basic-readwrite

But the Rust wrapper doesn't provide access to the cancel API, so:
* if we own the database, we drop it, which calls `ffi:rocksdb_close` (and hopefully drops the default `Env` as well)
* otherwise, we flush, and assume that the flush will wait on all the background reads, writes, and compactions

(I'm going to assume that `DB::drop` is implemented correctly, because the Rust wrapper doesn't provide access to any of the underlying cancel, close, or thread join functions.)

**Comment by teor2345** [comment]
> Do we support `debug_stop_at_height` and `ephemeral` together? That option combo doesn't really make sense to me.

We set both `debug_stop_at_height` and `ephemeral` in most of our sync acceptance tests. We want to test that syncing to a particular height works, but we don't need to keep the files afterwards.

**Comment by teor2345** [comment]
It turns out we can't call `DB::destroy` on an open database. And we can't close the database, because close is only available via `drop`, and the database is owned by the `StateService`.

So I reverted that part of the change.

**Review by dconnolly — APPROVED** [review]

**Pull request merged**
