### PR TITLE
Implement equihash verification

### LINKED ISSUE #335: Implement Equihash verification
I'm guessing we pull this in either directly or copied and reworked from librustzcash: https://github.com/zcash/librustzcash/blob/master/zcash_primitives/src/block/equihash.rs

image
https://zips.z.cash/protocol/protocol.pdf#equihashgen

image
https://zips.z.cash/protocol/protocol.pdf#equihash

### PR DESCRIPTION
**Pull request by yaahc**
part of #335

### CODE REVIEW

**Comment by yaahc** [comment]
I'm assuming this is not even close to the API we want but this seems to pass the functionality test so I think now all the changes that need to be made are structural

**Review by teor2345 — APPROVED** [review]
> I'm assuming this is not even close to the API we want but this seems to pass the functionality test so I think now all the changes that need to be made are structural

This looks great! I really like the negative tests.

We should also make sure that any modified header bytes make the solution fail. (Because that's part of the consensus rules.)

In particular, let's test a modified:
* input (header without nonce or solution)
* nonce, and
* solution.

I think we want an API that takes a block header, and returns a `Result<(), Error>`. There should only be one "solution is incorrect" error, because serialization can't fail.

But these things can be done in future PRs, if you'd like to merge this one.

**Comment by yaahc** [comment]
I think separate PR is a good idea, I'll go ahead and merge this and start working on the other test cases rn

**Comment by hdevalence** [comment]
:+1: to @teor2345's comment.  The signature `pub fn is_valid(&self, input: &[u8], nonce: &[u8]) -> bool` is a bit worrisome compared to one that takes a `BlockHeader` because it forces the caller to perform extra parsing logic.  Since we perform structural validation during parsing, we should try to work only on parsed representations as much as possible (even if it meant that we need to occasionally re-serialize for hashing, etc.). 

As a concrete example, the `equihash_solution_test_vector_is_valid` test has two checks that aren't really checks of the method itself, but of the parsing logic its interface pushes to the caller, and as soon as we take a `BlockHeader`, we can guarantee those properties statically so we have nothing to test.

**Comment by teor2345** [comment]
Also `pub fn is_valid(&self, input: &[u8], nonce: &[u8]) -> bool` is untyped, so any field of the correct size would be accepted at runtime.

Passing the `BlockHeader` means that we only have to check we're using the correct fields in `is_valid()`. Then the compiler makes sure that callers pass the correct type.

**Pull request merged**
