### PR TITLE
cleanup(gossip): Use a separate named constant for the gossip interval

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

In PR #6625, I re-used an existing constant for the gossip rate limit. But it's not really related to gossiping, so it might be confusing.

## Solution

- Use a separate named constant
- Increase the gossip interval slightly, so it's greater than the timeout for querying peers after gossips
- Update tests

## Review

This is a low priority cleanup.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Review by arya2 — APPROVED** [review]
Thank you for the cleanup!

**Review by arya2 — DISMISSED** [review]
`mempool_transaction_expiration` is failing consistently, `TIPS_RESPONSE_TIMEOUT` may need to be replaced with `PEER_GOSSIP_DELAY` in [`inbound/tests/fake_peer_set.rs`](https://github.com/ZcashFoundation/zebra/pull/6625/files#diff-6a7425f2d6ab0ef475e13cb6412322b72023e7139a23e04f0bc70205846d42b6).

**Comment by teor2345** [comment]
> `mempool_transaction_expiration` is failing consistently, `TIPS_RESPONSE_TIMEOUT` may need to be replaced with `PEER_GOSSIP_DELAY` in [`inbound/tests/fake_peer_set.rs`](https://github.com/ZcashFoundation/zebra/pull/6625/files#diff-6a7425f2d6ab0ef475e13cb6412322b72023e7139a23e04f0bc70205846d42b6).

Oops, thanks for this! It's nice to know the test works though.

**Comment by teor2345** [comment]
Needed the CI fix in PR #6729 to merge

**Comment by teor2345** [comment]
@mergifyio update

**Review by arya2 — APPROVED** [review]

**Pull request merged**
