### PR TITLE
fix(sync): Increase block download timeout and retries

### PR DESCRIPTION
**Pull request by teor2345**
## TODO

We might need to update some tests for the new values, or revert the block download timeout change.

These changes might not fix anything, they need a full sync test before they merge. It's possible we have some sync deadlocks, or an async task is not yielding often enough.

## Scheduling

We might need these changes if the full sync test fails. Otherwise, we can just close this PR.

## Motivation

After the fixes in PR #5561, there might still be some timeout warnings in Zebra's logs.

This a bug for a few reasons:
1. Users get alarmed at warnings
2. The timeouts could make Zebra's CI fail
3. It costs money to have full sync machines repeatedly doing nothing for an 8 minute timeout

## Solution

Try increasing the block download retries and timeout. This will help if peers are slow to send blocks.

I'm testing this locally.

(If that doesn't work, we might want to increase the full verification concurrency limit. That will help if we're getting blocks in the wrong order, then deadlock on both the concurrency limit, and getting a block we don't have.)

## Review

Anyone can review this PR.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by teor2345** [comment]
@mergifyio update

**Comment by gustavovalverde** [comment]
@Mergifyio update

**Comment by teor2345** [comment]
I'm running a full sync here:
https://github.com/ZcashFoundation/zebra/actions/runs/3519147385

If it has fewer timeouts, I'll fix up the test failures and submit this PR for review.

**Comment by teor2345** [comment]
This didn't help with the timeouts, so it's likely that we have some sync deadlocks, or an async task is not yielding often enough.

They are a low priority to fix, we can just extend the sync timeout for now.

**Pull request closed without merging**
