### PR TITLE
fix(release): Run `cargo update`

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We need to update Cargo.lock at release time.

## Solution

Run `cargo update` in the release branch. Warning of a deprecated function was found and was fixed. 

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by teor2345** [comment]
> Open a separate PR with the changes, including the output of `cargo update`

Can you please put the output of `cargo update` in a comment on this PR?

It helps verify that we're ok with all the changes, and work out if we have to revert any changes due to CI failures.

**Comment by teor2345** [comment]
This update is particularly large because:
- it's been more than a month since we did the last one
- I forgot to manually check for missed duplicate dependencies in #6535, because I was distracted by CI failures

**Comment by oxarbitrage** [comment]
```
$ cargo update
    Updating crates.io index
    Updating aead v0.5.1 -> v0.5.2
    Removing aes v0.7.5
    Updating anyhow v1.0.70 -> v1.0.71
    Updating async-stream v0.3.4 -> v0.3.5
    Updating async-stream-impl v0.3.4 -> v0.3.5
    Updating async-trait v0.1.67 -> v0.1.68
    Updating axum v0.6.12 -> v0.6.18
    Updating axum-core v0.3.3 -> v0.3.4
      Adding bindgen v0.65.1
    Removing bip0039 v0.9.0
    Removing block-modes v0.8.1
    Removing block-padding v0.2.1
    Removing bls12_381 v0.7.1
    Updating bumpalo v3.12.0 -> v3.12.2
    Updating chacha20 v0.9.0 -> v0.9.1
    Updating ciborium v0.2.0 -> v0.2.1
    Updating ciborium-io v0.2.0 -> v0.2.1
    Updating ciborium-ll v0.2.0 -> v0.2.1
    Removing cipher v0.3.0
    Updating clang-sys v1.6.0 -> v1.6.1
    Updating clap v3.2.23 -> v3.2.25
    Updating console-api v0.4.0 -> v0.5.0
    Updating console-subscriber v0.1.8 -> v0.1.9
    Updating core-foundation-sys v0.8.3 -> v0.8.4
    Updating cpufeatures v0.2.5 -> v0.2.7
    Updating crossbeam-channel v0.5.7 -> v0.5.8
    Removing crypto-mac v0.11.1
      Adding curve25519-dalek v4.0.0-rc.2
    Updating cxx v1.0.83 -> v1.0.94
    Updating cxx-build v1.0.93 -> v1.0.94
    Updating cxx-gen v0.7.93 -> v0.7.94
    Updating cxxbridge-flags v1.0.83 -> v1.0.94
    Updating cxxbridge-macro v1.0.83 -> v1.0.94
    Updating darling v0.20.0 -> v0.20.1
    Updating darling_core v0.20.0 -> v0.20.1
    Updating darling_macro v0.20.0 -> v0.20.1
    Updating directories v5.0.0 -> v5.0.1
    Updating enum-iterator v1.4.0 -> v1.4.1
    Updating enum-iterator-derive v1.2.0 -> v1.2.1
    Removing errno v0.2.8
    Removing errno v0.3.0
      Adding errno v0.3.1
    Removing ff v0.12.1
      Adding fiat-crypto v0.1.20
    Updating flate2 v1.0.25 -> v1.0.26
    Removing fpe v0.5.1
    Updating generic-array v0.14.6 -> v0.14.7
    Updating getrandom v0.2.8 -> v0.2.9
    Removing group v0.12.1
    Updating h2 v0.3.17 -> v0.3.18
    Removing halo2_gadgets v0.2.0
    Removing halo2_proofs v0.2.0
    Removing hmac v0.11.0
    Updating iana-time-zone v0.1.54 -> v0.1.56
    Updating io-lifetimes v1.0.9 -> v1.0.10
    Updating ipnet v2.7.1 -> v2.7.2
    Updating is-terminal v0.4.5 -> v0.4.7
    Updating js-sys v0.3.61 -> v0.3.62
    Removing jubjub v0.9.0
    Updating libc v0.2.140 -> v0.2.144
      Adding libm v0.1.4
    Updating libz-sys v1.1.8 -> v1.1.9
    Removing linux-raw-sys v0.1.4
    Removing linux-raw-sys v0.3.0
      Adding linux-raw-sys v0.3.7
      Adding metrics v0.20.1
    Updating metrics-exporter-prometheus v0.12.0 -> v0.12.1
      Adding metrics-macros v0.6.0
      Adding miniz_oxide v0.7.1
    Updating openssl v0.10.48 -> v0.10.52
    Updating openssl-macros v0.1.0 -> v0.1.1
    Updating openssl-sys v0.9.83 -> v0.9.87
    Removing orchard v0.3.0
      Adding packed_simd_2 v0.3.8
    Removing pairing v0.22.0
    Updating parity-scale-codec v3.4.0 -> v3.5.0
    Removing pasta_curves v0.4.1
    Removing pbkdf2 v0.9.0
    Updating pest v2.5.6 -> v2.6.0
    Updating pest_derive v2.5.6 -> v2.6.0
    Updating pest_generator v2.5.6 -> v2.6.0
    Updating pest_meta v2.5.6 -> v2.6.0
    Updating pkg-config v0.3.26 -> v0.3.27
      Adding platforms v3.0.2
    Removing portable-atomic v0.3.19
    Removing portable-atomic v1.2.0
      Adding portable-atomic v0.3.20
      Adding portable-atomic v1.3.2
      Adding prettyplease v0.2.4
    Updating quote v1.0.26 -> v1.0.27
    Removing reddsa v0.3.0
    Updating rustc-demangle v0.1.22 -> v0.1.23
    Removing rustix v0.36.11
    Removing rustix v0.37.5
      Adding rustix v0.37.19
    Updating serde v1.0.160 -> v1.0.162
    Updating serde_derive v1.0.160 -> v1.0.162
    Updating sketches-ddsketch v0.2.0 -> v0.2.1
    Updating spin v0.9.7 -> v0.9.8
    Removing time v0.1.43
    Removing time v0.3.20
      Adding time v0.1.45
      Adding time v0.3.21
    Updating time-core v0.1.0 -> v0.1.1
    Updating time-macros v0.2.8 -> v0.2.9
    Updating tokio v1.28.0 -> v1.28.1
    Removing tonic v0.8.3
    Updating tracing-attributes v0.1.23 -> v0.1.24
    Updating uuid v1.3.0 -> v1.3.2
      Adding wasi v0.10.0+wasi-snapshot-preview1
    Updating wasm-bindgen v0.2.84 -> v0.2.85
    Updating wasm-bindgen-backend v0.2.84 -> v0.2.85
    Updating wasm-bindgen-futures v0.4.34 -> v0.4.35
    Updating wasm-bindgen-macro v0.2.84 -> v0.2.85
    Updating wasm-bindgen-macro-support v0.2.84 -> v0.2.85
    Updating wasm-bindgen-shared v0.2.84 -> v0.2.85
    Updating web-sys v0.3.61 -> v0.3.62
    Updating windows v0.46.0 -> v0.48.0
    Updating winnow v0.4.0 -> v0.4.6
    Updating x25519-dalek v2.0.0-pre.1 -> v2.0.0-rc.2
    Removing zcash_note_encryption v0.2.0
    Removing zcash_primitives v0.9.1
    Updating zcash_script v0.1.11 -> v0.1.12
    Updating zeroize v1.5.7 -> v1.6.0
    Updating zeroize_derive v1.3.3 -> v1.4.2
$ 
```

**Comment by oxarbitrage** [comment]
It seems i need to make changes to deny file but the CI is not telling me the exact problems:

https://github.com/ZcashFoundation/zebra/actions/runs/4940489565/jobs/8832178217?pr=6656

**Comment by teor2345** [comment]
> Adding fiat-crypto v0.1.20

This new dependency contains auto-generated curve code, it was added in 4.0.0 of:

> Adding curve25519-dalek v4.0.0-rc.2

**Comment by teor2345** [comment]
> It seems i need to make changes to deny file but the CI is not telling me the exact problems:
> 
> https://github.com/ZcashFoundation/zebra/actions/runs/4940489565/jobs/8832178217?pr=6656

GitHub is having infrastructure problems at the moment.

On the PR summary it says:
https://github.com/ZcashFoundation/zebra/actions/runs/4940489565?pr=6656

IMG_2728

And the status page https://www.githubstatus.com/ says

IMG_2729

But these errors are only happening in jobs that were modified by PR #6628, so maybe that PR is responsible, and it only started failing when merged to `main`.

**Comment by teor2345** [comment]
> It seems i need to make changes to deny file but the CI is not telling me the exact problems:
> 
> https://github.com/ZcashFoundation/zebra/actions/runs/4940489565/jobs/8832178217?pr=6656

Looks like GitHub is fixed now.

This job has the output you need:
https://github.com/ZcashFoundation/zebra/actions/runs/4940489565/jobs/8834221652?pr=6656#step:4:50

The "skip tree root was not found" warnings don't need to be fixed, if you do want to fix them, you'll need the output from the `--all-features` job.

There's also a rustfmt issue.

**Comment by oxarbitrage** [comment]
The above merge was an error i made, i am now trying to fix it. Will probably have to make a new pull request.

**Comment by teor2345** [comment]
> The above merge was an error i made, i am now trying to fix it. Will probably have to make a new pull request.

I wouldn't worry about it that much, you can point people to this PR if they want to see the exact changes from `cargo update`.

**Pull request merged**
