### PR TITLE
fix(ci): delete a redundant "test all" job

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

CI has a job that runs all tests excluding ignored tests,  and a job that runs all tests including ignored tests.

These jobs are redundant.

## Solution

- make the first "run all" job include ignored tests
- delete the second "run all" job

## Review

@gustavovalverde can review this PR.

### Reviewer Checklist

  - [ ] Tests still pass

### CODE REVIEW

**Comment by gustavovalverde** [comment]
@Mergifyio update

**Review by gustavovalverde — COMMENTED** [review]
Wouldn't it be better to add the missing `--include-ignored` to the `test-all` job, and completely remove `test-zunstable`?

https://github.com/ZcashFoundation/zebra/pull/3552/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R106-R109

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
> Wouldn't it be better to add the missing `--include-ignored` to the `test-all` job, and completely remove `test-zunstable`?

You're right, I thought the same thing after I submitted the PR.

Fixed in the latest commit.

**Review by gustavovalverde — APPROVED** [review]

**Pull request merged**
