### PR TITLE
Revert "ref(workflow): move most scripts to their own executables"

### LINKED ISSUE #8123: main branch CI failed: "GitHub Actions has encountered an internal error when running your job" in Integration Tests on GCP
GitHub Actions workflow [Integration Tests on GCP #664](https://github.com/ZcashFoundation/zebra/actions/runs/7291110237) failed.

Event: push
Branch: [main](https://github.com/ZcashFoundation/zebra/tree/main)
Commit: [d1e72c114faff3eab212c90a21a7258f4e5b11ed](https://github.com/ZcashFoundation/zebra/commit/d1e72c114faff3eab212c90a21a7258f4e5b11ed)

<sup><i>Created by [jayqi/failed-build-issue-action](https://github.com/jayqi/failed-build-issue-action)</i></sup>

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

CI has been failing with an internal GitHub error since PR #8005 merged. Since people are away, the simplest way to fix this is to revert it for now.

Reverts ZcashFoundation/zebra#8005
Close #8123

### CODE REVIEW

**Comment by teor2345** [comment]
If this CI passes without errors, we can merge this PR. We need to manually scroll down and check it for errors, because they don't reliably show up in the CI summary or auto-opened tickets:
https://github.com/ZcashFoundation/zebra/actions/runs/7383079119?pr=8132

**Comment by teor2345** [comment]
That worked, and I manually checked all of the other CI runs for this PR, they also passed.

**Review by gustavovalverde — CHANGES_REQUESTED** [review]
Fixing it this way would revert improvements made to workflows that are not failing. From the 15+ impacted workflow files here, 1 workflow is failing. I'd prefer to tackle this specific issue and not revert the whole PR. I'll prioritize this

**Comment by teor2345** [comment]
> Fixing it this way would revert improvements made to workflows that are not failing. From the 15+ impacted workflow files here, 1 workflow is failing. I'd prefer to tackle this specific issue and not revert the whole PR. I'll prioritize this

My goal was restoring test coverage as reliably and quickly as possible. This PR does that.

If we merge this PR, then the rest of the team doesn't need to worry about this bug, and you can take whatever time you need to fix the bugs in that workflow and its sub-workflows.

So I'd prefer a quick solution that makes all workflows functional. We can always add back the improvements when they are working correctly.

Would you be ok with reverting the changes to `ci-integration-tests-gcp.yml` and the workflows it depends on instead?

**Comment by gustavovalverde** [comment]
> My goal was restoring test coverage as reliably and quickly as possible. This PR does that.

The odd thing here is that those failures are not being reflected in PR or main _checks_
image

As far as I've been able to identify the workflow is getting a failure, but all jobs are ending successfully (so the final check result is a successful run) even on the commit that opened the issue: https://github.com/ZcashFoundation/zebra/commit/d1e72c114faff3eab212c90a21a7258f4e5b11ed 

> Would you be ok with reverting the changes to ci-integration-tests-gcp.yml and the workflows it depends on instead?

Yes, I'd be ok reverting the changes in `sub-deploy-integration-tests-gcp.yml` (which is the sub-workflow being executed), but I'd prefer to try a fix with tomorrow as a deadline, and if I can't fix it, we merge the partial revert.

**Comment by teor2345** [comment]
Ok, happy to leave the fix or the partial revert to you.

**Comment by teor2345** [comment]
We don't need reminders for this, we're still deciding how to fix it.

**Pull request closed without merging**
