### PR TITLE
change(zebrad): opens the database in a blocking tokio thread, which allows tokio to run other tasks 

### LINKED ISSUE #4821: Open the database in a blocking tokio thread
## Motivation

Zebra can take a long time to re-open the database after the initial sync:
> 2022-07-25T03:50:05.294821Z  WARN {net="Main"}: zebra_chain::diagnostic: opening finalized state database code took a long time to execute execution_time="1m 8s" module_path=Some("zebra_state::service") line=Some(172)

We should do this work in a blocking thread, so it doesn't block the rest of the `tokio` executor.

Some RocksDB documentation warns that the first read can also be slow, so we might want to do it in the same blocking call.

### Designs

- Open the database and do the first database read using `tokio::spawn_blocking()` or `tokio::block_in_place()`
- Log an info-level message before opening the database, so that users know it might take a while

## Related Work

- #4822

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

To allow tokio to run other tasks while the database is opening and to tell users that it may take a couple minutes

Closes #4821.

## Solution

- Move the initialization of zebra-state and the database to a blocking thread
- Log an info-level message before starting to open the database

## Review

This PR is part of regular scheduled work.

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [x] Does the code do what the ticket and PR says?
  - [x] How do you know it works? Does it have tests?

## Follow Up Work

- Do the first read in a blocking tokio thread. (Some RocksDB documentation warns that that can also be slow)

### CODE REVIEW

**Review by teor2345 — APPROVED** [review]
I like how you designed the new API, and the tests!

**Comment by teor2345** [comment]
@arya2 looks like this failed in the Mergify PR, did you need help working out why?

**Comment by arya2** [comment]
> @arya2 looks like this failed in the Mergify PR, did you need help working out why?

Yes please.

**Comment by teor2345** [comment]
> > @arya2 looks like this failed in the Mergify PR, did you need help working out why?
> 
> Yes please.

I just realised we didn't have this documented anywhere, so I wrote something up:
https://github.com/ZcashFoundation/zebra/pull/5240/files

In summary, we go to the Mergify PR and find the errors on that PR, just like we would any other PR. It looks like this one failed downloading and caching the Zcash parameters. That's a transient network error, so we can just retry Mergify.

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by arya2** [comment]
@Mergifyio refresh

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by teor2345** [comment]
@arya2 usually if an error happens twice, it's not a transient network error, and we have to look for other causes.

In this case, it seems to be an issue with the new Rust release and our old compiled code caches. I added that to the instructions in #5240

**Comment by arya2** [comment]
@Mergifyio refresh

**Comment by arya2** [comment]
download-params is failing on main too. There's currently no actions cache for this PR, I'll try clearing all of the caches if it fails again.

**Comment by arya2** [comment]
@Mergifyio update

**Comment by teor2345** [comment]
It looks like this is actually a Rust 1.64 issue, see #5251

**Comment by upbqdn** [comment]
@mergifyio update

**Pull request merged**
