### PR TITLE
feat(ci): add a codespell linting action

### LINKED ISSUE #3318: Consider adding codespell to the CI
## Motivation

It seems @rex4539 is a regular contributor who fixes our typos by running [codespell](https://github.com/codespell-project/codespell) over the codebase. As @oxarbitrage  mentioned, it might be possible to integrate a spell-checker like [codespell](https://github.com/codespell-project/codespell) into our CI.

### Specifications

Here's a previous discussion about spell-checking with @teor2345:

> The tricky part of this change is adding a dictionary with Zcash-specific words, Rust-specific words, and engineering-specific words. Otherwise the spelling CI might fail every time we add a new feature or design.

> > Codespell looks for common (and a lot of) misspellings instead of checking dictionary membership. Here's the relevant description: It does not check for word membership in a complete dictionary, but instead looks for a set of common misspellings. Therefore it should catch errors like "adn", but it will not catch "adnasdfasdf". This also means it shouldn't generate false-positives when you use a niche term it doesn't know about.

> > Here are the misspellings https://github.com/codespell-project/codespell/tree/master/codespell_lib/data.
We could even add ours if we find a common one.

### PR DESCRIPTION
**Pull request by gustavovalverde**
## Motivation

Codespell looks for common (and a lot of) misspellings instead of checking dictionary membership. It does not check for word membership in a complete dictionary, but instead looks for a set of common misspellings. Therefore it should catch errors like "adn", but it will not catch "adnasdfasdf". This also means it shouldn't generate false-positives when you use a niche term it doesn't know about.

Fixes #3318

## Solution

- Add a codespell action to to the `Lint` workflow and activate it when a rust file is changed

## Review

@upbqdn or anyone from @ZcashFoundation/devops-reviewers 

### Reviewer Checklist

  - [ ] Codespell is not generating false-positives
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

- Validate if we can fix the amount of errors now
- If not, add a `continue-on-error` on the job

### CODE REVIEW

**Review by teor2345 — CHANGES_REQUESTED** [review]
I'm not sure if we actually want this check in CI.

Here are the benefits I see:
- Documentation is spelt correctly

Here are the drawbacks I see:
- We block merges for a single misspelling, even if the meaning is clear, or
- We get red check marks on every PR if we accidentally merge a misspelling

This seems like a negative experience, particularly for new contributors.

What does everyone think?

**Comment by gustavovalverde** [comment]
> Here are the drawbacks I see:
> 
> * We block merges for a single misspelling, even if the meaning is clear, or
> * We get red check marks on every PR if we accidentally merge a misspelling

- Merges won't get block using `warning` as the maximum level
- This only validates the current changes in the PR so we should not worry on existing misspellings as those will be filtered and won't raise a warning
  - Example: https://github.com/ZcashFoundation/zebra/runs/6583671800

**Comment by teor2345** [comment]
> > Here are the drawbacks I see:
> > 
> > * We block merges for a single misspelling, even if the meaning is clear, or
> > * We get red check marks on every PR if we accidentally merge a misspelling
> 
> * Merges won't get block using `warning` as the maximum level
> * This only validates the current changes in the PR so we should not worry on existing misspellings as those will be filtered and won't raise a warning      
>   * Example: https://github.com/ZcashFoundation/zebra/runs/6583671800

Can you show me an example of what a misspelling in a PR's changes looks like?

**Comment by upbqdn** [comment]
I personally think the benefits of this check outweigh the drawbacks. I think this because of the reasons gustavovalverde stated: PRs don't get blocked and only edited files are checked.
I agree that it can be a negative experience, but not to the extend that it would discourage people from contributing (I'm usually happy when a machine checks my work for free, and gives me suggestions). The biggest drawback I see is the maintenance of `ignore-words-list`.

I don't think it's complicated to deprecate this check, so if we start using it, and we don't like it, we can easily get rid of it.

**Comment by gustavovalverde** [comment]
Result from the linter. I'm reverting this test commit
image

**Review by conradoplg — COMMENTED** [review]
This looks good, but I don't get this: where is it specified that it should run only on changed files? Or is that the default behavior?

**Comment by teor2345** [comment]
> This looks good, but I don't get this: where is it specified that it should run only on changed files? Or is that the default behavior?

Review Dog does this kind of filtering automatically.

**Review by teor2345 — APPROVED** [review]
Looks great, thanks for the explanation!

**Pull request merged**
