### PR TITLE
do not merge: deliberately fail all the tests

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

@gustavovalverde asked for a PR that fails all the tests.

If a test job doesn't fail with this PR, it has one of these bugs:
- doesn't run the test due to CI job filters
- doesn't run the test in the CI `cargo test` command
- doesn't call `zebra_test::init` in the Rust code
- doesn't check the test status in the CI config

These are all bugs, because all the tests should run the code that is changed by this PR.
(Unless they are an integration test without a test harness, or a `should_panic` test.)

### CODE REVIEW

**Comment by teor2345** [comment]
Clippy also fails, because the panic makes the rest of the function unused.

**Comment by gustavovalverde** [comment]
Thank you @teor2345, this gives me a bunch of visibility

A few comments, based on the outcome:
- `Test all` is just running 3 tests, I thought this was supposed to run most tests, without the `ignored` ones, or those that require a variable. 

- `Test with fake activation heights` is not selecting a test

**Comment by teor2345** [comment]
> * `Test all` is just running 3 tests, I thought this was supposed to run most tests, without the `ignored` ones, or those that require a variable.

It fails after the first 3 tests, and then stops. If we want to see all the tests it runs, we need to tell cargo to continue on failures.

There are also other jobs that run most of the tests, they are called "Test stable on ubuntu-latest" (or similar).

So maybe "Test all" should be called "Test stable on debian-bullseye on docker".

> * `Test with fake activation heights` is not selecting a test

This is:
- #3673

**Comment by teor2345** [comment]
@gustavovalverde did you need me to do anything here?

**Comment by gustavovalverde** [comment]
@teor2345 I've written a few comments in the specific issues related to this PR.

**Review by jvff — COMMENTED** [review]
Looks good! (Not approving just in case it risks triggering a merge)

**Comment by teor2345** [comment]
> Looks good! (Not approving just in case it risks triggering a merge)

I added the `do-not-merge` label, which should stop mergify doing anything with this PR.
(So should all the test failures!)

**Comment by teor2345** [comment]
I think this PR has served its purpose.

**Pull request closed without merging**
