### PR TITLE
feat(diagnostics): Add tokio-console support to zebrad

### LINKED ISSUE #2112: Integrate tokio-console
**Scheduling**

This ticket is only required if we've fixed all the known hang bugs in Zebra, and Zebra still has frequent hangs.

**Is your feature request related to a problem? Please describe.**

It's hard to see what tokio is doing inside Zebra.

> another cool thing the console does now is its ⚠️warnings system. this is like a linter, but for your program’s runtime behavior. by monitoring the tasks in the application, we can detect behavior patterns that might indicate bugs or performance issues.

https://twitter.com/mycoliza/status/1471880880289366022

**Describe the solution you'd like**

- [ ] Integrate tokio-console into Zebra: https://github.com/tokio-rs/console#using-it
- [ ] Manually test that it works

**Describe alternatives you've considered**

Continue trying to debug tokio using metrics and other indirect methods

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We want to find out why Zebra is slow to sync, so we need to see what its async tasks are doing.

Depends-On: #4517

Close #2112

This is part of fixing the high priority ticket #4456.

### API Specifications

Integration instructions:
https://github.com/tokio-rs/console/blob/main/console-subscriber/README.md#getting-started

tokio-console requires per-layer filtering:
https://docs.rs/tracing-subscriber/latest/tracing_subscriber/layer/index.html#per-layer-filtering
https://docs.rs/tracing-subscriber/latest/tracing_subscriber/registry/struct.Registry.html

### Designs

Add tokio-console as an optional dependency, enabled by the `tokio-console` feature.
Add the console layer to the existing tracing layer stack, making the required changes to the rest of the stack.

### Instructions

Compile and launch `zebrad` with these compile-time configs:
```sh
RUSTFLAGS="--cfg tokio_unstable" cargo build --release --no-default-features --features="tokio-console" --bin zebrad
target/release/zebrad
```

Then in another terminal:
```sh
cargo install --locked tokio-console
tokio-console
```

## Solution

- Add optional tokio-console support
    - Use a tracing Registry for tokio-console, and a fmt::Subscriber if it is not enabled

Features & Dependencies:
- Add the tokio-console feature and dependencies
- Always activate tokio/tracing feature in production
- Always activate all tokio features in tests

Refactoring:
- Refactor tracing-subscriber init to simplify it

Diagnostics:
- Log the installed tracing layers at info level, after tracing is initialised

## Review

Anyone can review this PR, I'm not sure who is most familiar with tracing or async executors.

This might need a review call.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Existing tests pass

## Follow Up Work

See PR #4539 for a list of follow-up work.

Out of scope:
- Work out why this change enables some debug logs (it's not meant to, but it's a developer tool, so it doesn't matter)

### CODE REVIEW

**Comment by teor2345** [comment]
I'm running a speed test here, ideally we're looking for around 5h35m:
https://github.com/ZcashFoundation/zebra/actions/runs/2413134843

**Comment by teor2345** [comment]
I marked this as a high priority for review, because it increases the sync speed

**Comment by gustavovalverde** [comment]
@Mergifyio update

**Comment by teor2345** [comment]
@mergifyio update

**Comment by gustavovalverde** [comment]
For future follow-up https://github.com/tokio-rs/tracing/tree/master/tracing-opentelemetry

**Comment by teor2345** [comment]
@oxarbitrage did you want to do a review call for this PR, or did you want to hand the review to someone else?

**Review by conradoplg — COMMENTED** [review]
The code looks good, but I'm trying to figure out two things:

- When I enable it and run it, a get a lot of TRACE messages though I'm using the default logging (`info`), e.g.

       2022-06-07T23:02:49.902673Z TRACE {zebrad="0be50cc" net="Main"}:sync:try_to_sync: zebrad::components::sync: waiting for pending blocks tips.len=1 in_flight=2013 lookahead_limit=2000 state_tip=Some(Height(105626))
       
- `tokio-console` [docs](https://github.com/tokio-rs/console#instrumenting-your-program) mention
  > if you are manually configuring the tracing subscriber using the [EnvFilter](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html) or [Targets](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/targets/struct.Targets.html) filters from [tracing-subscriber](https://lib.rs/crates/tracing-subscriber), add "tokio=trace,runtime=trace" to your filter configuration.

  However this PR does not seem to do that, but it works. Do you know why? If I try to add that filter to the Zebra config it logs a lot of stuff to the terminal, which is not what we want. I guess I'm confused about the relationship between tracing & logging.

None of these are blockers so I'll probably approve this after I take another look.

**Comment by teor2345** [comment]
>     * When I enable it and run it, a get a lot of TRACE messages though I'm using the default logging (`info`), e.g.
>       ```
>        2022-06-07T23:02:49.902673Z TRACE {zebrad="0be50cc" net="Main"}:sync:try_to_sync: zebrad::components::sync: waiting for pending blocks tips.len=1 in_flight=2013 lookahead_limit=2000 state_tip=Some(Height(105626))
>       ```

I think I must have set up the logging filters wrong (on `tracing_subscriber::fmt::Layer`):
https://github.com/ZcashFoundation/zebra/pull/4519/files#diff-f3a497bdec8cf6c584ff806e24fe9e531a24cf8d8ef0fa09a57b42238e76a837R65-R72

I'll see if I can fix that quickly today, it's something that should work!

>     * `tokio-console` [docs](https://github.com/tokio-rs/console#instrumenting-your-program) mention
>       > if you are manually configuring the tracing subscriber using the [EnvFilter](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html) or [Targets](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/targets/struct.Targets.html) filters...
> 
>       However this PR does not seem to do that, but it works. Do you know why? If I try to add that filter to the Zebra config it logs a lot of stuff to the terminal, which is not what we want. I guess I'm confused about the relationship between tracing & logging.

The PR calls `console_subscriber::spawn()`, which automatically adds the correct per-layer filter to the tokio-console layer:
https://docs.rs/console-subscriber/latest/console_subscriber/fn.spawn.html

(We're not using `EnvFilter` or `Targets` to set up that layer.)

**Comment by conradoplg** [comment]
> I think I must have set up the logging filters wrong (on `tracing_subscriber::fmt::Layer`): https://github.com/ZcashFoundation/zebra/pull/4519/files#diff-f3a497bdec8cf6c584ff806e24fe9e531a24cf8d8ef0fa09a57b42238e76a837R65-R72
> 
> I'll see if I can fix that quickly today, it's something that should work!

OK!
 
> The PR calls `console_subscriber::spawn()`, which automatically adds the correct per-layer filter to the tokio-console layer: https://docs.rs/console-subscriber/latest/console_subscriber/fn.spawn.html
> 
> (We're not using `EnvFilter` or `Targets` to set up that layer.)

Got it, thanks! For some reason I assumed  `spawn()` counted as "manually configured"

**Comment by teor2345** [comment]
> > ```
> > * When I enable it and run it, a get a lot of TRACE messages though I'm using the default logging (`info`), e.g.
> >   ```
> >    2022-06-07T23:02:49.902673Z TRACE {zebrad="0be50cc" net="Main"}:sync:try_to_sync: zebrad::components::sync: waiting for pending blocks tips.len=1 in_flight=2013 lookahead_limit=2000 state_tip=Some(Height(105626))
> >   ```
> > ```
> 
> I think I must have set up the logging filters wrong (on `tracing_subscriber::fmt::Layer`):
> https://github.com/ZcashFoundation/zebra/pull/4519/files#diff-f3a497bdec8cf6c584ff806e24fe9e531a24cf8d8ef0fa09a57b42238e76a837R65-R72
> 
> I'll see if I can fix that quickly today, it's something that should work!

The logging filters are correct, but a few functions (`crawl_and_dial`, `try_to_sync`) seem to evade the layer filter and the global span.

Since this only happens with the tokio-console feature, I added a TODO to fix it later.
(It might be a `tracing_subscriber` bug.)

**Comment by teor2345** [comment]
This worked fine in the last CI run, and I just added a TODO and a minor cleanup.

So I'm going to admin-merge this PR.

**Pull request merged**
