### PR TITLE
Fix some "needless lifetime" clippy lints

### PR DESCRIPTION
**Pull request by teor2345**
These lints seem to be new in clippy nightly.

### CODE REVIEW

**Comment by teor2345** [comment]
@hdevalence this PR contains minor changes to `zebra-network/src/peer/connection.rs`, can you check that they're ok?

I assume that's what this comment means:
> // The danger is to the mind. The danger is unleashed only if you substantially
> // disturb this code. This code is best shunned and left encapsulated.

Maybe we could also replace that comment with something a bit more explicit?
We could start the module with a doc comment that explains why people should be careful modifying that code.

Some people only read the first line, so let's be upfront about the risks.

**Comment by teor2345** [comment]
I'm going to merge this now, because the new lint is causing spurious CI errors in other PRs.

But please review these changes!

**Review by dconnolly — COMMENTED** [review]
👍

**Comment by daira** [comment]
Clippy is being quite opinionated here, no? I actually prefer the style that names the lifetime.

(Note that if you google 'needless_lifetimes clippy', there are a bunch of unfixed cases where this lint is just wrong and broken.)

**Comment by hdevalence** [comment]
@teor2345 Those changes look fine to me!  The comment is a joke about the complexity of the Bitcoin network protocol.  We can remove it later if you'd like, but I think that's a lower priority than completing the verification logic.

**Comment by dconnolly** [comment]
> @teor2345 Those changes look fine to me! The comment is a joke about the complexity of the Bitcoin network protocol. We can remove it later if you'd like, but I think that's a lower priority than completing the verification logic.

<コ:彡

**Comment by teor2345** [comment]
> Clippy is being quite opinionated here, no? I actually prefer the style that names the lifetime.
> 
> (Note that if you google 'needless_lifetimes clippy', there are a bunch of unfixed cases where this lint is just wrong and broken.)

I mean, it's pretty much clippy's job to have opinions. (And our job to decide if we agree.)

I'm not surprised it's broken, it's a nightly build, after all.

**Pull request merged**
