### PR TITLE
fix(deploy): no dot name instance template disks to allow scaling

### LINKED ISSUE #4946: Managed instance groups deployed with continuous deployment can't scale beyond 1 instance per Zone
## Motivation

This warning is raised when deploying instance groups

```
WARNING: Some requests generated warnings:
 - Instance template specifies a disk with a custom name. This will cause instance group not to scale beyond 1 instance per zone.
```

### Designs

- Remove the instance disk name, and allow google to create the disk name
- Delete old instance disks using the name that google creates

## Related Work

None

### LINKED ISSUE #5644: infra: Some disks are not being recognized as RO/RW and containers are failing to get raised
## Motivation

We've been reducing the amount of errors happening in CI, and in GCP logs, to reduce the spectrum of possibilities causing SSH errors from CI.

One of the latest errors is:

```
Failed to start container: Volume pd-0: Could not determine if the GCE Persistent Disk zebrad-cache-7b73aa0 is attached read-only or read-write
```

### Designs

- Verify if there's documentation on how to properly mount disks on Compute Engine
- Validate if we're mounting disks in a standard way for all instances in CI and CD.

### PR DESCRIPTION
**Pull request by gustavovalverde**
## Motivation

We've been having the following errors when deploying:
- ```Instance template specifies a disk with a custom name. This will cause instance group not to scale beyond 1 instance per zone.```
- ```Error: Failed to start container: Volume pd-0: Could not determine if the GCE Persistent Disk zebrad-cache-b722e22 is attached read-only or read-write```

Fixes #4946
Fixes #5644

### Specifications

See: https://cloud.google.com/sdk/gcloud/reference/compute/instances/create-with-container#--create-disk:~:text=This%20option%20cannot%20be%20specified%20if%20more%20than%20one%20instance%20is%20being%20created

See: https://cloud.google.com/sdk/gcloud/reference/compute/instances/create-with-container#--create-disk:~:text=specifying%20disk%20name%20here%20is%20optional

## Solution

- Apply documentation recommendations to remove this errors and allow CD instances to increase as expected

## Review

Anyone can review this PR

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by dconnolly** [comment]
Is this a critical?

**Comment by gustavovalverde** [comment]
> Is this a critical?

Long-lived instances (the one being deployed after merging to `main` and creating new versions) are failing and filling GCP logs with errors. It's not being recorded on CI, but the instances are not behaving as expected.

For example: `Error: Failed to start container` means the instance is deployed, but the container is not even being started. So we have placebo instances right now :/

**Review by teor2345 — CHANGES_REQUESTED** [review]
Have you tested that the new workflows are valid?
Can you link to the results of those tests?

**Comment by gustavovalverde** [comment]
> Have you tested that the new workflows are valid?

I ran this locally (the parts I changed) using `gcloud` ~as this steps can't be manually run considering the jobs filters specific GitHub events to run~

> Can you link to the results of those tests?

Sadly, I didn't save the results of my local run. I just ran it for the manual instance creation, to validate it works deploying from the actual workflow (which I didn't do before): https://github.com/ZcashFoundation/zebra/actions/runs/3526626859/jobs/5914773589#step:5:75

I'm leaving the instance ON, so you're able to verify the logs to confirm is running as expected without the errors from the OP  https://console.cloud.google.com/logs/query;query=%2528resource.type%3D%22gce_instance%22%20AND%20resource.labels.instance_id%3D%225563755729968469549%22%2529%20OR%20%2528resource.type%3D%22global%22%20AND%20jsonPayload.instance.id%3D%225563755729968469549%22%2529;cursorTimestamp=2022-11-22T19:53:58.734702293Z?authuser=1&project=zealous-zebra

**Review by teor2345 — APPROVED** [review]
Looks good!

As a totally separate ticket, it would be nice to deploy these instances without coloured l`zebrad` ogs, because in google cloud I see this:
> [2m2022-11-22T19:56:53.829956Z[0m [32m INFO[0m [1m[0m[1m{[0m[3mnet[0m[2m=[0m"Main"[1m}[0m[2m:[0m[1msync[0m[2m:[0m[1mtry_to_sync[0m[2m:[0m[1mextend_tips[0m[2m:[0m[1mcheckpoint[0m[2m:[0m [2mzebra_consensus::checkpoint[0m[2m:[0m verified checkpoint range [3mblock_count[0m[2m=[0m400 [3mcurrent_range[0m[2m=[0m(Excluded(Height(16896)), Included(Height(17296)))

**Pull request merged**
