### PR TITLE
fix(ci): Show logs after each Google Cloud test job

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

PR #5330 stopped showing any test logs in Google Cloud test runs that use the `ssh-compute` action.

But we need those logs to diagnose test failures.

## Solution

Add a step that shows the logs after each time we run `ssh-compute`

## Review

This PR is urgent because we need to be able to diagnose google cloud failures.

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [x] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Review by dconnolly — DISMISSED** [review]

**Comment by teor2345** [comment]
I think we're running into the 1 MB step output limit here:
https://github.com/ZcashFoundation/zebra/actions/runs/3200985566/jobs/5228636615

Longer-term, we could use log artifacts:
https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
Or modify the `ssh-compute` GitHub action so it shows the SSH output.

**Comment by teor2345** [comment]
https://github.com/google-github-actions/ssh-compute/issues/29

**Comment by teor2345** [comment]
Failed with:
>   Error: Unable to locate the previous sha: de3640ddccfbd66371d4a7e81c49d4230ed35b7f
>  Error: You seem to be missing 'fetch-depth: 0' or 'fetch-depth: 2'. See https://github.com/tj-actions/changed-files#usage

https://github.com/ZcashFoundation/zebra/actions/runs/3203562017/jobs/5233804843#step:3:97

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
Failed with:
> ERROR: (gcloud.compute.start-iap-tunnel) Error while connecting [4010: 'destination read failed'].
> kex_exchange_identification: Connection closed by remote host

This is #5362

**Review by dconnolly — APPROVED** [review]
tee hee | tail

**Comment by gustavovalverde** [comment]
Superseded by https://github.com/ZcashFoundation/zebra/pull/5367

**Pull request closed without merging**
