### PR TITLE
Send `Response::Nil` instead of sending empty `Message`s

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We should try to match `zcashd`'s behaviour and the Bitcoin spec when sending network messages.

In most cases, the network layer filters out empty responses already.
But this change makes the the inbound service code clearer.

### Specifications

Most Bitcoin messages must contain at least one item.

For example:
https://en.bitcoin.it/wiki/Protocol_documentation#addr

### Other Implementations

`zcashd` doesn't send empty messages.

For example:
https://github.com/zcash/zcash/blob/498d42219c2cae93ae808c314a8986ed3b484d6b/src/main.cpp#L7424-L7425

## Solution

- Stop sending empty responses from the inbound service
- Make it clearer that existing empty responses are actually no response - `Response::Nil`
- Make logging consistent

## Review

I think @conradoplg and @oxarbitrage wrote some of this code.
Either can review.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

Maybe we should handle empty requests and responses at the network layer? #1724

### CODE REVIEW

**Review by conradoplg — DISMISSED** [review]
LGTM :+1:

**Comment by conradoplg** [comment]
Some tests failed after syncing with main, not sure what's going on

**Comment by oxarbitrage** [comment]
ill try to fix.

**Comment by oxarbitrage** [comment]
The PR was done before the tests were merged.
The changes done to `PushTransaction` and `AdvertiseTransactionIds` were looking good to me(there was a bit of less code overall) but it seems they don't work, not sure exactly why but it looks like the `.map_ok()` call is needed. I reverted that back in https://github.com/ZcashFoundation/zebra/pull/2791/commits/1a06ff41143aaecb88c8c9183c83dc5ae0c1b1d7 

Except for that the rest of the PR seems to be ok.

**Review by conradoplg — APPROVED** [review]

**Comment by teor2345** [comment]
> I missed this while reviewing, here the oneshot is discarded while it should be returned (this function returns a future that is executed by the caller). Therefore this revert is correct, thanks

Thanks for catching this!

**Pull request merged**
