### PR TITLE
Use ok_or for constants in zebra-network

### PR DESCRIPTION
**Pull request by teor2345**
I can't see these clippy warnings locally, but they happen in CI.

### CODE REVIEW

**Review by hdevalence — DISMISSED** [review]
LGTM

**Comment by hdevalence** [comment]
@teor2345 Should we merge this immediately, to suppress the errors in the other PRs?

**Comment by hdevalence** [comment]
It looks like there's one case left, and a complaint about the check annotations coming from a fork: https://github.com/ZcashFoundation/zebra/runs/1059659639

**Comment by teor2345** [comment]
> It looks like there's one case left

Ok, that case didn't show up in the other PRs. I'll go fix it.

I have no idea why these are so inconsistent, it's pretty annoying.

> a complaint about the check annotations coming from a fork

That's a GitHub limitation, not our problem. Anyone who submits PRs from a fork runs into this issue.

**Comment by teor2345** [comment]
> Should we merge this immediately, to suppress the errors in the other PRs?

I'll admin-merge once it passes the clippy CI.

**Pull request merged**
