### PR TITLE
refactor(docker): organize Dockerfiles and remove unused

### PR DESCRIPTION
**Pull request by gustavovalverde**
## Motivation

Remove unused Dockerfile and use better locations for existing ones, to reduce confusion.

Depends-On: https://github.com/ZcashFoundation/zebra/pull/3657

## Solution
- Create a folder for lightwalletd
- Create a folder for zcash params
- Rename all Dockerfiles
- Remove Dockerfile.test (consolidated in zebra's Dockerfile)

## Review
@dconnolly and @teor2345 can review this

### CODE REVIEW

**Comment by teor2345** [comment]
Seems like there's a merge conflict in this PR.

**Review by teor2345 — APPROVED** [review]
Seems pretty small, let's merge!

**Review by dconnolly — APPROVED** [review]
lgtm!

Since this is targeting the `add-lightwalletd-build` branch, there are no rules that Mergify understands to automerge it (all the rules are for PRs that target #main)

**Comment by gustavovalverde** [comment]
@dconnolly oh yeah, this was on purpose. Once `add-lightwalletd-build` gets merged, this PR base branch gets _automagically_ changed to `main`, and then Mergify does the automation.

The `Depends-On: https://github.com/ZcashFoundation/zebra/pull/3657` attribute on the opening post is read by Mergify to identify the PRs or Issues that must be merged or closed before starting to merge this one.

**Comment by dconnolly** [comment]
> @dconnolly oh yeah, this was on purpose. Once `add-lightwalletd-build` gets merged, this PR base branch gets _automagically_ changed to `main`, and then Mergify does the automation.
> 
> The `Depends-On: https://github.com/ZcashFoundation/zebra/pull/3657` attribute on the opening post is read by Mergify to identify the PRs or Issues that must be merged or closed before starting to merge this one.

Cool that works 😁

**Pull request merged**
