### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Review by oxarbitrage — DISMISSED** [review]
Thanks :)

**Comment by oxarbitrage** [comment]
We need someone with admin privileges (i don't have them) to merge as the CI is temporally broken for pull requests coming from forked branches :(

**Comment by teor2345** [comment]
@mergifyio update

**Review by teor2345 — DISMISSED** [review]
This PR might cause a merge conflict with PR #3617, so I don't want to merge it yet.

@oxarbitrage can you review PR #3617 when you get time?

**Comment by teor2345** [comment]
@rex4539 would you mind re-doing this PR with the latest main branch?

It conflicted with a large refactor, so we merged the other PR first.

**Comment by rex4539** [comment]
Rebased.

**Review by teor2345 — APPROVED** [review]
Thanks!

**Comment by teor2345** [comment]
@mergifyio update

**Review by teor2345 — APPROVED** [review]

**Comment by gustavovalverde** [comment]
@Mergifyio update

**Review by teor2345 — APPROVED** [review]

**Pull request merged**
