### PR TITLE
change(test): Require cached lightwalletd state for the send transaction tests

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

After we have a cached lightwalletd image, we want to require that cached state, to speed up the tests.

This reverts part of PR #4302.

Depends-On: #4302, #4267, #4268,#4269

This also needs a DevOps change to mount the lightwalletd cached state disk.

## Solution

- require cached lightwalletd state for the send transaction tests

## Review

Anyone can review this PR, it is not urgent.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

**Comment by gustavovalverde** [comment]
Added https://github.com/ZcashFoundation/zebra/pull/4269 as a dependency, as we're changing the way we define if a lightwalletd cache is needed there. And changes here will break when #4269 gets merged

**Comment by gustavovalverde** [comment]
This is working as expected https://github.com/ZcashFoundation/zebra/runs/6430615895?check_suite_focus=true 🎉

**Comment by dconnolly** [comment]
> This is working as expected https://github.com/ZcashFoundation/zebra/runs/6430615895?check_suite_focus=true 🎉 

🎊🦄🤩🥳🥰

**Review by gustavovalverde — APPROVED** [review]
LGTM!

**Pull request merged**
