### PR TITLE
change(consensus): Update mainnet and testnet checkpoints

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We're seeing some slow syncs, updating the checkpoints might help.

## Review

This is routine, but required for tagging the release candidate.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by teor2345** [comment]
Failed ssh connection, see #5362 for details

**Comment by teor2345** [comment]
Failed due to #5366, logs in that ticket.

**Review by oxarbitrage — APPROVED** [review]

**Comment by arya2** [comment]
I added some intermediate jobs between `logs-1790k` and `logs-checkpoint` in https://github.com/ZcashFoundation/zebra/pull/5372

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by teor2345** [comment]
The macOS job failed while building the Zcash parameter path binary, which is really unusual. (It's not particularly big, and it doesn't do much.)
https://github.com/ZcashFoundation/zebra/actions/runs/3223280477/jobs/5273188507#step:11:299

I'll try again, but if that doesn't work, we should clear the macOS build cache:
https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/continuous-integration.md#fixing-disk-full-errors-and-zcash-parameter-errors

And if that doesn't work, we can disable the macOS job, because macOS tests are not a release blocker. (Tier 2 doesn't guarantee tests will work.)

**Comment by teor2345** [comment]
There was no test cache for this PR or `main`, but I deleted the clippy cache:
```json
    {
      "id": 39427,
      "ref": "refs/heads/main",
      "key": "v0-rust-clippy-cargo-lock-1.64.0-x86_64-unknown-linux-gnu-a55dd71d5fb0-1b751ccaa4b37d9524c4",
      "version": "8a9936d632ad0d67adaee02f5d9fd8c1dddbbd5af8d94331392b76f17401cf6d",
      "last_accessed_at": "2022-10-11T01:06:11.716666700Z",
      "created_at": "2022-10-10T19:34:51.596666700Z",
      "size_in_bytes": 1203215728
    },
```

**Comment by teor2345** [comment]
@mergifyio refresh

**Pull request merged**
