### PR TITLE
Remove dconnolly as default assignee and reviewer on dependabot PRs, and make them low priority

### PR DESCRIPTION
**Pull request by dconnolly**
## Motivation

When Dependabot opens PRs that update our dependencies, dconnolly is currently assigned and added as reviewer. We want to spread the load for reviewers.

## Solution

- Remove defaults for assignees and reviewers.
- Assign dependabot PRs low priority by default.

## Follow Up Work

Change labels depending on priority of the update

### CODE REVIEW

**Comment by teor2345** [comment]
I also made the other change we discussed, which was making dependabot PRs low priority.

**Comment by dconnolly** [comment]
Nice:
image

**Review by teor2345 — APPROVED** [review]
I think we're good to go here, we can't really test this until it merges, and we get a dependabot PR.

**Comment by teor2345** [comment]
Let's merge #2942 first though.

**Comment by teor2345** [comment]
This seems to have worked, see PR #2956

**Pull request merged**
