### PR TITLE
NonFinalizedState: Finish implementation and testing according to RFC0005

### PR DESCRIPTION
**Pull request by yaahc**
## Motivation

This PR is tracking the follow up changes necessary to fully implement the
non-finalized state according to the state RFC and to test the implementation.

- [ ] Correctly handle duplicate blocks in `CommitBlock`
- [ ] test the best chain is selected correctly
- [ ] test the best chain height is correctly returned
- [ ] check that the right queued blocks are pruned

## Related Issues

* Prior PR - https://github.com/ZcashFoundation/zebra/pull/1101
* Relevant comments - https://github.com/ZcashFoundation/zebra/pull/1101#discussion_r500716408 and https://github.com/ZcashFoundation/zebra/pull/1101#discussion_r501365663
* PR updating RFC - https://github.com/ZcashFoundation/zebra/pull/1136

### CODE REVIEW

**Comment by teor2345** [comment]
Now that #1101 has merged, can we rebase this PR (or open another PR), so it's easy to see the new commits?

**Review by teor2345 — APPROVED** [review]
This refactor is good as it is, and I would like to merge it straight away.

(If we keep building on it, then any future reviews will have to read through this refactor code - even though we know it's good.)

I think the TODO list in this PR should actually become a tracking issue.

**Review by dconnolly — APPROVED** [review]

**Comment by teor2345** [comment]
> I think the TODO list in this PR should actually become a tracking issue.

Or maybe a section in the RFC5 tracking issue - whatever works best for the developers and reviewers.

**Comment by teor2345** [comment]
This is good work, and it's an improvement, so I'm going to merge it now.

I moved the remaining TODOs into the state tracking issue #1049.

**Pull request merged**
