### PR TITLE
fix(diagnostics): Hex-encode debug format of commitments, nonces, and nullifiers

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Zebra's debug output shows block header commitments and nonces as an array of integers, rather than hexadecimal. This makes them very hard to debug.

This diagnostics bug is impacting RPC testing.

Most of the changes in this PR are in test code, or they are tiny changes to existing code.

## Solution

- Create a `HexDebug` type wrapper, which automatically makes the wrapped type encode as hex during `derive(Debug)`
- Apply the wrapper to the block header commitments and nonce
- Apply the wrapper to Sprout nullifiers and commitments
- Apply the wrapper to Sapling nullifiers
- Apply the wrapper to Orchard redpallas keys

I also opened ticket https://github.com/ZcashFoundation/reddsa/issues/215 to make similar changes in `redjubjub`.

## Review

This is blocking RPC testing, it is important to review soon.

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [x] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by teor2345** [comment]
Looks like crates.io is having some network or capacity issues, I'll retry those parts of CI later. (Or anyone can do it if I'm not around.)

**Review by arya2 — DISMISSED** [review]
Looks good!

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by teor2345** [comment]
Failed with bug #5958 in the merge queue:
https://github.com/ZcashFoundation/zebra/actions/runs/3934423672/jobs/6729152365#step:9:2156

**Comment by teor2345** [comment]
It looks like this has a build conflict with some code in other PRs, I'll see what I can do to fix it.

**Comment by teor2345** [comment]
This needs a quick re-approval.

I added commit 0912da3 to make it build with the latest `main` branch, which gets reverted straight away in PR #5944 and replaced with a different fix.

**Review by conradoplg — APPROVED** [review]

**Pull request merged**
