### PR TITLE
Increase block validation timeouts

### PR DESCRIPTION
**Pull request by jvff**
## Motivation

The full synchronization test currently times out after running for 6 hours. One possible cause is that during synchronization the block validation may time out a few times, which leads to a few minutes of delays.

## Solution

Increase the UTXO lookup timeout and the block validation time out to see if the synchronization finishes earlier.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

**Comment by teor2345** [comment]
This could be a bug in the recently merged PR #4149, or an intermittent error:
> WARNING: Default device-name for disk name [zebrad-cache-28dc985-mainnet-checkpoint] will be [zebrad-cache-28dc985-mainnet-checkpoint] because it is being mounted to a container with [`--container-mount-disk`]
> ERROR: (gcloud.compute.instances.create-with-container) Could not fetch resource:
> - The resource 'projects/zealous-zebra/global/images/zebrad-cache-main-e5f00c5-v23-mainnet-checkpoint' is not ready

https://github.com/ZcashFoundation/zebra/runs/6103901143?check_suite_focus=true#step:7:95

Maybe @gustavovalverde can help diagnose?

**Comment by jvff** [comment]
This did not lead to a performance increase that's enough to solve the issue (#4155).

This PR can be closed, but it might be useful for reference because it contains the workaround I used when synchronization gets stuck on a single block. This can happen on debug builds or on release builds using trace-level logging. It could also happen on some lower-end computers.

**Comment by teor2345** [comment]
> This did not lead to a performance increase that's enough to solve the issue (#4155).
> 
> This PR can be closed, but it might be useful for reference because it contains the workaround I used when synchronization gets stuck on a single block. This can happen on debug builds or on release builds using trace-level logging. It could also happen on some lower-end computers.

I'd like to fix this bug for low-end computers, if we can do it without breaking the full sync test.

Can we leave this PR in draft, fix the sync speed, and then re-test to make sure it doesn't make the sync *worse*?

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
I am updating this branch to delete the clean action, which causes other actions to fail.

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
I'm running a full sync test here:
https://github.com/ZcashFoundation/zebra/actions/runs/2267417739

If it takes around 5h50m, we should merge this PR, because it fixes part of the bug in PR #4286.

**Comment by oxarbitrage** [comment]
So the full sync tests was skipped, can we relaunch this to check how much time it takes ?

**Comment by teor2345** [comment]
> So the full sync tests was skipped, can we relaunch this to check how much time it takes ?

The test I ran manually took 5h47m, so it is about the same speed.

**Review by teor2345 — APPROVED** [review]
Required to fix bugs like #4286.

**Pull request merged**
