### PR TITLE
Repoint zebra image links to our new zfnd.org site for now

### PR DESCRIPTION
**Pull request by dconnolly**
## Motivation

When we migrated the zfnd.org website to a new hosting service, a few image links that the Zebra docs / book / sites use got broken.

## Solution

Repoint at new hosted images.

## Review

This is low priority, anyone can review.

### CODE REVIEW

**Review by teor2345 — COMMENTED** [review]
I'd prefer to put the images in a separate repository, so that CI and developers don't have to download them all the time.

Otherwise, I'm all for these changes, thanks for fixing this up!

**Review by upbqdn — COMMENTED** [review]
All looks good. 👍 
I didn't approve in case we want to address Teor's comment.

**Comment by dconnolly** [comment]
> I'd prefer to put the images in a separate repository, so that CI and developers don't have to download them all the time.
> 
> Otherwise, I'm all for these changes, thanks for fixing this up!

Oh I'm sorry, I forgot those changes were still on my local. I can remove committing the images to this repo.

**Comment by dconnolly** [comment]
> > I'd prefer to put the images in a separate repository, so that CI and developers don't have to download them all the time.
> > Otherwise, I'm all for these changes, thanks for fixing this up!
> 
> Oh I'm sorry, I forgot those changes were still on my local. I can remove committing the images to this repo.

This has been updated

**Comment by teor2345** [comment]
@mergifyio update

**Review by teor2345 — APPROVED** [review]

**Pull request merged**
