### PR TITLE
Refine Ed25519 byte arrays to ed25519-zebra types.

### LINKED ISSUE #109: Zcash-flavored Ed25519
Parts of the Zcash specification require Ed25519 with specific, consensus-critical verification rules, for instance in [the JoinSplit signatures](https://zips.z.cash/protocol/protocol.pdf#concretejssig).  Because it is critical that we do Ed25519 verification exactly as in the spec, we may want to create a Zcash-flavored Ed25519 on top of `curve25519-dalek` that has exactly the properties we need.

### PR DESCRIPTION
**Pull request by hdevalence**
Closes #109.

### CODE REVIEW

**Comment by hdevalence** [comment]
@dconnolly I'm not sure how this interacts with #118 since it presumably will require changes to the `Arbitrary` impls but I'm happy to help rebase that on top of this PR if you want?

**Comment by dconnolly** [comment]
> @dconnolly I'm not sure how this interacts with #118 since it presumably will require changes to the `Arbitrary` impls but I'm happy to help rebase that on top of this PR if you want?

I will rebase that on top on this when merged to main, I'll just do an `impl Arbitrary` for `PublicKeyBytes` and `Signature` as needed. 👍

**Review by dconnolly — APPROVED** [review]
👍

**Comment by hdevalence** [comment]
I'm not sure, but if there's an `Arbitrary` impl for `[u8; 32]` and `[u8; 64]` it might not be necessary to implement `Arbitrary` for `PublicKeyBytes` and `Signature` and instead just use `.into()`?

**Pull request merged**
