### PR TITLE
make clippy warnings errors in CI

### PR DESCRIPTION
**Pull request by yaahc**

### CODE REVIEW

**Review by dconnolly — DISMISSED** [review]
📎

**Review by dconnolly — APPROVED** [review]

**Comment by dconnolly** [comment]
Oh hey also this will expose the warnings and fail the _check_, but will not block the merging of the PR, that's currently pegged on 1: a good review, and 2: passing ubuntu-latest build check.

**Comment by yaahc** [comment]
I think thats fine @dconnolly, if people end up ignoring the clippy warnings just because they're not blocking the merge then we can think about making it a blocker, but I bet this will be sufficient for preventing warnings from sneaking into the codebase.

**Comment by teor2345** [comment]
> I think thats fine @dconnolly, if people end up ignoring the clippy warnings just because they're not blocking the merge then we can think about making it a blocker, but I bet this will be sufficient for preventing warnings from sneaking into the codebase.

@yaahc the underlying problem is that warnings on forks don't appear in the job status as a failed clippy build, due to a GitHub integration issue with annotations:
> I didn't see the clippy warnings when I did the review, because GitHub doesn't show check annotations in PRs from forked repositories:
> actions-rs/clippy-check#2

(See #598.)

**Pull request merged**
