### PR TITLE
fix(openapi): Remove trailing characters in descriptions

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

The openapi spec has trailing `"]` on each method description, for example:

```
Submits block to the node to be validated and committed."]
```

#### Check before marking the PR as ready for review:
  - [x] Will the PR name make sense to users?
  - [x] Does the PR have a priority label?
  - [ ] Have you added or updated tests?
  - [ ] Is the documentation up to date?

## Solution

Use `trim_end_matches()` in the description to fix the issue. Regenerate spec.

## Review

Anyone can review.

### Reviewer Checklist

Check before approving the PR:
  - [ ] Does the PR scope match the ticket?
  - [ ] Are there enough tests to make sure it works? Do the tests cover the PR motivation?
  - [ ] Are all the PR blockers dealt with?
        PR blockers can be dealt with in new tickets or PRs.

_And check the PR Author checklist is complete._

### CODE REVIEW

**Review by arya2 — DISMISSED** [review]

**Comment by gustavovalverde** [comment]
FYI, this is not merging because of https://github.com/ZcashFoundation/zebra/actions/runs/9467963278/job/26083250170

**Comment by oxarbitrage** [comment]
> FYI, this is not merging because of https://github.com/ZcashFoundation/zebra/actions/runs/9467963278/job/26083250170

Yes, i will rebase when this gets merged: https://github.com/ZcashFoundation/zebra/pull/8602

**Review by mpguerra — APPROVED** [review]

**Comment by mpguerra** [comment]
@mergifyio refresh

**Comment by oxarbitrage** [comment]
@mergifyio refresh

**Pull request merged**
