### PR TITLE
feat(state): Store history trees by height in the non-finalized state

### LINKED ISSUE #4837: Store history trees by height in the non-finalized state
## Motivation

In order to implement #4824, the non-finalized state needs to store history trees by their height, so that it can send the history tree corresponding to the root block to the finalized state when committing the root block.

## Related Work

#4824

### PR DESCRIPTION
**Pull request by upbqdn**
## Motivation

In order to implement #4824, the non-finalized state needs to store history
trees by their height, so that it can send the history tree corresponding to the
root block to the finalized state when committing the root block.

## Solution

This PR adds `history_trees_by_height` to `Chain` in the non-finalized state.

Closes #4837.

## Follow Up Work

Finish #4721.

### CODE REVIEW

**Review by teor2345 — APPROVED** [review]
Thanks, nice work on the `PartialEq` refactor.

**Comment by upbqdn** [comment]
@teor2345 if the CI doesn't pass, do you think you'd be able to merge this manually? It would be handy to have this PR in place for #4721.

**Comment by teor2345** [comment]
> @teor2345 if the CI doesn't pass, do you think you'd be able to merge this manually? It would be handy to have this PR in place for #4721.

I think we've fixed all the outstanding bugs, so I'm hoping that we're done with admin merges.
(And we should really only be skipping CI for high priority PRs.)

Can you start your next PR by rebasing it on the [add-hist-trees-by-height](https://github.com/ZcashFoundation/zebra/tree/add-hist-trees-by-height) branch?
You might want to rebase [add-hist-trees-by-height](https://github.com/ZcashFoundation/zebra/tree/add-hist-trees-by-height) on `main` first.

If that won't work, here's what I expect will happen with CI:
- PR #4918 will pass CI and get merged by Mergify, then
- Other PRs will pass CI once they are rebased on the latest `main` branch, and
- CI will speed up after the first full sync finishes on `main`

If PR #4918 fails, you can try doing a `@mergifyio update`, and increasing the timeouts in that PR, or you can ask @oxarbitrage to fix the PR.

If all that doesn't work out, I'll see what I can do tomorrow morning.

**Comment by teor2345** [comment]
This PR is a low priority, but I'm marking it with Medium so it merges a bit earlier, so that Marek can use it for other work.

**Comment by teor2345** [comment]
@mergifyio update

**Comment by gustavovalverde** [comment]
@Mergifyio update

**Pull request merged**
