### PR TITLE
Update version strings for Zebra v1.0.0-alpha.7 release

### PR DESCRIPTION
**Pull request by mpguerra**
---
name: Release Checklist Template
about: Checklist of versioning to create a taggable commit for Zebra
title: ''
labels:
assignees: ''

---

### Which Crates to Increment

To check if any of the top-level crates need version increments, go to the zebra GitHub code page: https://github.com/ZcashFoundation/zebra. `git diff --stat <previous-release-tag> origin/main` is also useful to see
what's changed.

- [x] Increment the crates that have new commits since the last version update
- [x] Increment any crates that depend on crates that have changed
- [x] Use the `zebrad` crate version in the `zebra-network` user agent string
- [x] Use the latest git tag in `README.md`

### Version Locations

Once you know which versions you want to increment, you can find them in the:
- [x] zebra* `Cargo.toml`s
- [x] tower-* `Cargo.toml`s
- [x] `zebra-network` protocol user agent: https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/constants.rs
- [x] `README.md`
- [x] `Cargo.lock`: automatically generated by `cargo build`

Merge all these version increments as one commit, by squashing and rebasing the PR onto the main branch.

## Initial Testing

- [x] After any changes, test that the `cargo install` command in `README.md` works (use `--path` instead of `--git` locally)

## Change Log

**Important**: Any merge into `main` deletes any edits to the draft changelog. Edit the draft changelog in a pad like https://pad.riseup.net

We follow the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format.

We use [the Release Drafter workflow](https://github.com/marketplace/actions/release-drafter) to automatically create a [draft changelog](https://github.com/ZcashFoundation/zebra/releases).

To create the final change log:
- [x] Copy the draft changelog into a pad like https://pad.riseup.net
- [x] Delete any trivial changes
- [x] Combine duplicate changes
- [x] Edit change descriptions so they are consistent, and make sense to non-developers
- [x] Check the category for each change
  - prefer the "Fix" category if you're not sure

#### Change Categories

From "Keep a Changelog":
* `Added` for new features.
* `Changed` for changes in existing functionality.
* `Deprecated` for soon-to-be removed features.
* `Removed` for now removed features.
* `Fixed` for any bug fixes.
* `Security` in case of vulnerabilities.

## After merging this PR
- [x] Check for any PRs that have been merged since you created the changelog pad
- [x] Update the draft release with the final changelog
- [x] Set the release title to `Zebra ` followed by the version tag, for example: `Zebra 1.0.0-alpha.0` 
- [x] Set the tag name to the version tag, for example: `1.0.0-alpha.0`
- [x] Set the release to target the `main` branch
- [x] Mark the release as 'pre-release' (until we are no longer alpha/beta)

## Final Testing

- [ ] After tagging the release, test that the exact `cargo install` command works
      (`--git` behaves a bit differently to `--path`)

If the build fails after tagging:
1. fix the build
2. check if the fixes changed any extra crates, and do the required version increments
3. update `README.md` with a **new** git tag
4. tag a **new** release

### CODE REVIEW

**Comment by mpguerra** [comment]
Changelog pad: https://pad.riseup.net/p/2UGwI9jQuyxScbuw880M

**Comment by mpguerra** [comment]
Having issues running zebrad after building and installing.

Steps done:

1. `cargo build` (to update Cargo.lock)
2. `cargo install --path <path to my local zebra git repo>/zebrad`
3. `~/.cargo/bin/zebrad start`

Gives an error:
```
$ ~/.cargo/bin/zebrad start
Apr 22 15:59:55.397  INFO {zebrad="592a174" net="Main"}: zebrad::commands::start: Starting zebrad
Apr 22 15:59:55.400  INFO {zebrad="592a174" net="Main"}: zebrad::commands::start: config=ZebradConfig { consensus: Config { checkpoint_sync: false }, metrics: MetricsSection { endpoint_addr: None }, network: Config { listen_addr: 0.0.0.0:8233, network: Mainnet, initial_mainnet_peers: {"mainnet.seeder.zfnd.org:8233", "dnsseed.str4d.xyz:8233", "dnsseed.z.cash:8233", "mainnet.is.yolo.money:8233"}, initial_testnet_peers: {"testnet.is.yolo.money:18233", "testnet.seeder.zfnd.org:18233", "dnsseed.testnet.z.cash:18233"}, peerset_initial_target_size: 50, crawl_new_peer_interval: 60s }, state: Config { cache_dir: "/Users/pguerra/Library/Caches/zebra", ephemeral: false, debug_stop_at_height: None }, tracing: TracingSection { use_color: true, filter: None, endpoint_addr: None, flamegraph: None, use_journald: false }, sync: SyncSection { max_concurrent_block_requests: 50, lookahead_limit: 2000 } }
Apr 22 15:59:55.402  INFO {zebrad="592a174" net="Main"}: zebrad::commands::start: initializing node state
Apr 22 15:59:55.402  INFO {zebrad="592a174" net="Main"}: zebra_state::config: set the open file limit for Zebra new_limit=1024 old_limit=Some(256) hard_rlimit=Some(9223372036854775807)
Apr 22 15:59:55.465  INFO {zebrad="592a174" net="Main"}: zebra_state::service::finalized_state: Opened Zebra state cache at /Users/pguerra/Library/Caches/zebra/state/v4/mainnet
The application panicked (crashed).
Message:  there is no reactor running, must be called from the context of a Tokio 1.x runtime
Location: /Users/pguerra/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.6/src/buffer/service.rs:76

Metadata:
version: 1.0.0-alpha.1+347.g592a174
branch: pili-v1.0.0-alpha.7-release
git commit: 592a174
commit timestamp: 2021-04-22T11:20:28+00:00
target triple: x86_64-apple-darwin
Zcash network: Mainnet

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: zebrad::application:: with zebrad="592a174" net="Main"
      at zebrad/src/application.rs:346

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Consider reporting this error using this URL: https://github.com/ZcashFoundation/zebra/issues/new?title=%3Cautogenerated-issue%3E&body=%23%23+Error%0A%60%60%60%0Athere+is+no+reactor+running%2C+must+be+called+from+the+context+of+a+Tokio+1.x+runtime%0A%60%60%60%0A%0A%23%23+Metadata%0A%7Ckey%7Cvalue%7C%0A%7C--%7C--%7C%0A%7C**version**%7C1.0.0-alpha.1%2B347.g592a174%7C%0A%7C**branch**%7Cpili-v1.0.0-alpha.7-release%7C%0A%7C**git+commit**%7C592a174%7C%0A%7C**commit+timestamp**%7C2021-04-22T11%3A20%3A28%2B00%3A00%7C%0A%7C**target+triple**%7Cx86_64-apple-darwin%7C%0A%7C**Zcash+network**%7CMainnet%7C%0A%7C**location**%7C%2FUsers%2Fpguerra%2F.cargo%2Fregistry%2Fsrc%2Fgithub.com-1ecc6299db9ec823%2Ftower-0.4.6%2Fsrc%2Fbuffer%2Fservice.rs%3A76%3A9%7C%0A%0A%0A%23%23+SpanTrace%0A%0A%3Cdetails%3E%0A%0A%60%60%60%0ASpanTrace%3A%0A+++0%3A+zebrad%3A%3Aapplication%3A%3A%0A+++++++++++with+zebrad%3D%22592a174%22+net%3D%22Main%22%0A+++++++++++++at+zebrad%2Fsrc%2Fapplication.rs%3A346%0A%60%60%60%0A%3C%2Fdetails%3E
Abort trap: 6
```

**Comment by teor2345** [comment]
> 2\. `cargo install --path <path to my local zebra git repo>/zebrad`

Try `cargo install --locked --path <path to my local zebra git repo>`.

The missing `--locked` will skip the lock file, making some components use tokio 1.x.

Using the path to zebrad might also skip the lock file. The zebra workspace knows that zebrad is the default binary anyway.

(This issue will be fixed once we upgrade to tokio 1.x #1086, and we'll fix the general cause by keeping up with the latest versions of most packages. But that takes a bit of work that we don't have time for right now.)

**Review by teor2345 — DISMISSED** [review]
We'll also need to bump the version in tower-fallback, because it depends on zebra-test, which got a version bump.

in general we might want to rewrite the instructions to assume everything gets bumped, and ask for an explanation for things that don't need a bump.

**Comment by teor2345** [comment]
I did a few changelog tweaks, mainly deleting changes obsoleted within the release, merging related changes, and splitting multiple changes made in a single PR.

We might also want to sort the changes into subcategories.

And we'll need a summary sentence or two for the release. (See previous releases.)

**Comment by teor2345** [comment]
> We might also want to sort the changes into subcategories.
> 
> And we'll need a summary sentence or two for the release. (See previous releases.)

I just made these changes on the pad.

**Review by oxarbitrage — APPROVED** [review]
Requested bump to `tower-fallback` was done and the changelog is worked on.

**Pull request merged**
