### PR TITLE
T2. add(test): add test API that checks process logs for failures

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We want to check lightwalletd logs and Zebra logs for failures like:
- missing RPCs
- RPC argument parse errors
- RPC argument data errors
- RPC response parse errors
- RPC response data errors
- other specific errors logged by lightwalletd

But our testing framework makes it very hard to do that.

This PR adds an API to check test logs for failures, but it doesn't actually do those checks yet.

This is related to:
- #3500 
- #3856 
- #3511

### Designs

Add a set of failure regexes to each child process, and check each log line for those regexes. Panic if any failures are logged.

Make sure test processes are cleaned up correctly, so their logs are read and checked for failures.

## Solution

Failure logs:
- Add a set of failure regexes to test child processes, and use them to check process output
- When the child is dropped, check any remaining output
- Add internal tests for failure regex panics

Reading process output:
- Add test APIs for consuming child output lines, without checking them for a success regex

Also document some edge cases, and some things we might want to fix later.

## Review

This PR is not urgent.

It is based on PR #3892.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

- Check lightwalletd logs for failures

### CODE REVIEW

**Comment by oxarbitrage** [comment]
Please rebase and fix conflicts when you get the time. Thanks!

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
@mergifyio rebase

**Comment by teor2345** [comment]
> Please rebase and fix conflicts when you get the time. Thanks!

Done!

The conflicts aren't real, they're just caused by squashing PRs.

**Review by oxarbitrage — APPROVED** [review]
Looks great, very complete with a lot of testing so it should work pretty much as we expect.

**Pull request merged**
