### PR TITLE
change(format): improve CommitBlockError message: include underlying ValidateContextError message

### LINKED ISSUE #6218: Implement custom Debug trait for CommitBlockError
## Motivation
For CommitBlockError tuple the default implementation for Debug is used now so with statements like `println!("{:?}, err);` there is no formatted error description is printed for the base ValidateContextError but only the error parameters.
Suggestion is to implement the std::fmt::Debug trait for CommitBlockError which would also print expanded ValidateContextError, like:
```
impl std::fmt::Debug for CommitBlockError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "CommitBlockError(\"{}\": ValidateContextError(\"{}\"))", self.to_string(), self.0.to_string())
    }
}
``` 
Or maybe we could use debug_tuple with the formatted ValidateContextError field as well.

### PR DESCRIPTION
**Pull request by teor2345**
This is a copy of PR #6236 in the Zebra repository, so all our CI can run on it.

### CODE REVIEW

**Comment by teor2345** [comment]
@mergifyio refresh

**Review by upbqdn — DISMISSED** [review]

**Comment by upbqdn** [comment]
I can't approve this PR since I pushed it, even though I didn't make the commit.

**Comment by teor2345** [comment]
> I can't approve this PR since I pushed it, even though I didn't make the commit.

If that rule gets annoying an admin can turn it off. But every time I've seen it come up, it's a situation where we actually want another review!

**Comment by teor2345** [comment]
@mergifyio update

**Review by mpguerra — APPROVED** [review]

**Comment by teor2345** [comment]
Failed due to an infrastructure configuration issue, Gustavo is working on a fix.

To re-queue the PR, comment `@mergify refresh` once he's fixed it.

**Pull request merged**
