### PR TITLE
Light Client Root Hash for Block

### PR DESCRIPTION
**Pull request by teor2345**
Parse the LightClientRootHash using `block.light_client_root_hash(network)`.

### CODE REVIEW

**Comment by teor2345** [comment]
See #768 for a previous attempt at this change, and the associated discussion.

**Comment by teor2345** [comment]
Blocked by data dependency problems, which need design changes or refactoring.

**Comment by hdevalence** [comment]
@teor2345 pointed out that we need not just the block height but also the network in order to interpret the field, because the block height at which the interpretation changes depends on the network, and this doesn't fit with the `ZcashDeserialize` trait.  So I guess we cannot fully parse the field upfront.  The next best option seems like a variant of @str4d's suggestion on Discord to have a method that takes a `Network` and returns the enum representation (I don't think it's necessary to pass the block height, since the block height is included in the block already).  Since the block height is optional I guess it will have to return an option of an enum.

**Comment by teor2345** [comment]
>  The next best option seems like a variant of @str4d's suggestion on Discord to have a method that takes a `Network` and returns the enum representation (I don't think it's necessary to pass the block height, since the block height is included in the block already). Since the block height is optional I guess it will have to return an option of an enum.

I implemented this design as `block.light_client_root_hash(network)`.

**Review by hdevalence — APPROVED** [review]
LGTM!

**Pull request merged**
