### PR TITLE
Remove 'self-DoS'ing tokio task for testing 'zebra seed' command.

### PR DESCRIPTION
**Pull request by dconnolly**
Request::Peers not GetPeers

Fix 'dos' feature for seed command, and Buffer the seed service

### CODE REVIEW

**Review by yaahc — CHANGES_REQUESTED** [review]
does the CI need to be updated as well to ensure that this is tested? we might want to add another build step that sets --all-features.

**Comment by hdevalence** [comment]
In the future I think it would be good to split that code out into a separate binary rather than using features at all (since if it's in a load-generator tool, it's much more useful for testing, rather than a static build configuration option), in which case another alternative would be to just do that rather than fixing the CI.

**Review by yaahc — APPROVED** [review]
:shipit:

**Comment by yaahc** [comment]
> :shipit:

why is this a squirrel????

**Comment by dconnolly** [comment]
> > :shipit:
> 
> why is this a squirrel????

Someone on the internet [says](https://www.quora.com/On-GitHub-what-is-the-significance-of-the-Ship-It-squirrel)

image

**Pull request merged**
