### PR TITLE
Upgrade to Abscissa v0.5

### PR DESCRIPTION
**Pull request by tarcieri**

### CODE REVIEW

**Comment by hdevalence** [comment]
Thanks for doing this!! It looks like in this PR, the zebra `TracingComponent` is mostly unchanged, although the tracing part of it is now upstreamed into Abscissa.  So I think that ideally we would also refactor the component to only keep the tracing RPC endpoint and connect it to the Abscissa functions for setting the tracing filters.  I'd be happy to do that – I don't want to ask more work of you – but I'm wondering whether it would be possible to push more commits to your branch (I don't recall how Github's "Allow edits from maintainers" settings work).

**Comment by tarcieri** [comment]
> I'm wondering whether it would be possible to push more commits to your branch (I don't recall how Github's "Allow edits from maintainers" settings work).

Well, it's checked:

Screen Shot 2019-12-20 at 3 41 07 PM

You should be able to do it, I think.

**Comment by hdevalence** [comment]
Cool, thanks! I will try to add on that commit and get this merged.

**Comment by dconnolly** [comment]
The GitHub Action never kicked off our Cloud Build, I'll try to kick it.

**Comment by hdevalence** [comment]
I fixed the `TracingEndpoint` code in a commit on this repo's `iqlusioninc-abscissa/v0.5`; I tried adding it to the fork's branch but I don't know how.

There's a further problem related to the Tokio component.  We need to enter an async context at some point in some subcommands, which is currently done by getting a mutable reference to the `TokioComponent` via Abscissa's global lock and then calling `block_on` with that subcommand's future.  However, this means that those subcommands can't ever use the framework components, because doing so causes a deadlock.   We can't access the `TokioComponent` via the registry, because it will hold a global lock (write, or read if using interior mutability) for the program's lifetime. We can't start the runtime when we want to enter an async context, because we need to start the runtime while the application is booting (so it is available when we start the tracing endpoint). We also can't use `tokio::main`, because Abscissa isn't async.

**Comment by hdevalence** [comment]
Probably the best fix for this in the near term is to change the `TokioComponent` to have an `Option<Reactor>` and provide a `take` method that moves the reactor out of the component to call `block_on`.  Then the reactor is available for spawning tasks during setup, and at some point when we want to enter an "async context" we take it out to start the root future, and it is then ambiently available to all sub-tasks.

**Comment by tarcieri** [comment]
@hdevalence if you get something like that working, I think it’d be great to extract into an `abscissa_tokio` crate for reuse

**Comment by hdevalence** [comment]
Closed by #169

**Pull request closed without merging**
