### PR TITLE
Full chain synchronization acceptance tests

### LINKED ISSUE #3493: Add a `zebrad` acceptance test that does a full sync to tip
## Motivation

This is the Rust part of:
- #1592

## Suggested Design

Here's one way to do the Rust part of this change:

Partly done in #3495:
1. Create a future that returns when the estimated height has been reached
2. Add that future to `zebrad start`'s main loop as a "continuing task", so Zebra exits when it finishes

New work:
3. Create a sync test case with a 6 hour timeout, which uses a "stop at estimated height" config

https://github.com/ZcashFoundation/zebra/blob/1a14baf8e7c6c82dba7a64e9b43d076b8f856f2a/zebrad/src/commands/start.rs#L195-L200

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/1592#issuecomment-1032006501_

## Follow-Up Tasks

Required:
- check that we are at least 200<sup>*</sup> blocks above the highest checkpoint (detects stalls)

<sup>*</sup> I picked 200 because 100 non-finalized blocks are excluded from checkpoint generation, and it takes 2 hours to build and run the test. (If mainnet syncs get fast, or we're using testnet.) If we make it any higher, the first time we submit each checkpoint update PR the tests will be slow, because we'll wait to sync newly generated blocks.

Useful to increase coverage:
- wait until the mempool has been active for a few minutes before exiting (increases coverage)

Optional:

<details>

Only if needed due to CI failures:
- Adjust the timeout so that at least 99% of syncs succeed (makes failing tests fail faster)

Here is a refactor I don't think we need to do yet:
- #3442 (simplifies similar test code that's currently in the state)

</details>

### PR DESCRIPTION
**Pull request by jvff**
## Motivation

As we approach our first stable release, it's important for Zebra to work well and not have any regressions. We've had a few issues with chain synchronization before (#3322, #3375, #3352), and we didn't have a good way to catch these issues early one. Running an acceptance test that synchronizes the full chain should help us detect if there are any hangs or performance regressions in the future.

This closes #3493, and serves as a base for #1592.

## Solution

Two acceptance tests were added, one for mainnet and one for testnet. Both synchronize the chain and check that it completes within an externally specified timeout and that the mempool becomes active when synchronization finishes.

The tests only run if `--ignored` is specified to the test command and if an environment value with the specific test timeout value is specified. This is because these tests may take a long time, and can exceed GitHub Action's time limit. Having the timeout value specified externally makes it easier to tweak it in the CI jobs.

## Review

@oxarbitrage can review this.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

#1592 will add this test to the CI pipeline.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
Do we want to run this test periodically or something outside the CI ? Maybe we need to add a follow up work for @gustavovalverde ?

Should we consider adding a suggested environment timeout number to people who want to run this ?

**Review by oxarbitrage — APPROVED** [review]
Th code looks good so i am approving; left some questions as well but they dont block.

**Comment by oxarbitrage** [comment]
@jvff also, did you had a chance of testing running the test and confirmed a successful exit ?

**Comment by jvff** [comment]
> Do we want to run this test periodically or something outside the CI ? Maybe we need to add a follow up work for @gustavovalverde ?

Yeah, we'll add it to the CI in #1592. We can also run it manually if needed (but hopefully we shouldn't need to do this often :laughing: )

> Should we consider adding a suggested environment timeout number to people who want to run this ?

That might be a good idea. I'm not sure what to set this though, because for example my testnet test took more than 4 hours (I think it didn't have many peers) and my mainnet test took about 7 hours. I think it might vary a lot based on the environment. I guess the ideal is to set it to 12 hours and leave it running overnight :joy: 

> @jvff also, did you had a chance of testing running the test and confirmed a successful exit ?

Yeah, it worked well but took a long time :grin:

There's one thing I'm slightly concerned about: the mempool check and the synchronization finished check happen very close to each other, so I think there might be situations where there's a race and the test fails. I can open a PR to make things more robust, but I was thinking about letting it run a few times first to see if that issue could really happen or not.

**Comment by gustavovalverde** [comment]
> Do we want to run this test periodically or something outside the CI? Maybe we need to add a follow-up work for @gustavovalverde ?

If there's value-added running it periodically, it can be quickly done. Just let me know a good periodicity cc: @conradoplg @teor2345

**Review by teor2345 — COMMENTED** [review]
Nice, this is a lot simpler than I was expecting!

**Comment by teor2345** [comment]
> > Do we want to run this test periodically or something outside the CI? Maybe we need to add a follow-up work for @gustavovalverde ?
> 
> If there's value-added running it periodically, it can be quickly done. Just let me know a good periodicity cc: @conradoplg @teor2345

Good question - I'm not sure if we need to run any tests periodically, because:
- Zebra is being actively developed, and
- we pin the versions of all our dependencies.

But if development slows down, we should think about running every week or so, to test against network changes. And to keep the block cache up to date.

For `lightwalletd`, we probably want regular integration tests, because it's a large dependency that can change independently. I added scheduled tests to the list of tasks in:
- #3511

**Pull request merged**
