### PR TITLE
Get redpallas tweak proptests working again

### LINKED ISSUE #2170: Fix orchard spend auth signature regressions
**Is your feature request related to a problem? Please describe.**

#2168 contains some proptest regressions that cause the `redpallas::prop::tweak_signature` test's spend auth signature check to fail.

**Describe the solution you'd like**

- [ ] Fix these regressions
- [ ] Re-enable the tests by reverting #2169

**Describe alternatives you've considered**

Delete the tests if they are unreliable.

**Related issues**

Regression PR #2168 
Temporarily disable test PR #2169
Underlying fix ticket #2170

### PR DESCRIPTION
**Pull request by dconnolly**
## Motivation

When we ported the redjubjub proptests over for redpallas, we found some seeds for tweak_signatures that were expected to fail signature validation but did not, therefore the tests were failing. Looks like the particular byte twiddles that worked for jubjub do not reliably work for pallas, which is understandable because it's over a different base field with different modular reduction when creating a keypair.

## Solution

Instead of creating an invalid verification key for a particular signature by tweaking its bytes,
create another verification key and when the ChangePubkey tweak is applied, just swap out the correct
SignatureCase::pk_bytes for SignatureCase::invalid_pk_bytes and check that trying to verify the signature
using that wrong key fails, as expected.

This is a little kludgy compared to the original but quite reliable.

The code in this pull request has:
  - [x] Documentation Comments
  - [x] Unit Tests and Property Tests

## Review

Anyone can review, maybe @conradoplg @jvff 

## Related Issues

Resolves #2170

## Follow Up Work

None?

### CODE REVIEW

**Review by jvff — APPROVED** [review]
Looks good :tada:

**Review by teor2345 — APPROVED** [review]
This looks good, glad to see it fixed!

**Comment by daira** [comment]
I don't understand why the [original code](https://github.com/ZcashFoundation/zebra/pull/2219/files#diff-ac055069f1186b8eb04bfdf6c938ab4fdaebb119a3779eb9b3a7214751690e1dL84-L89) wouldn't make the signature invalid. That merits a more thorough investigation.

(There are two cases: if `bytes[2]` is initially 2 (mod 32) then `bytes[2]` becomes 0 which is a change; otherwise `bytes[2]` becomes nonzero and therefore `bytes[j]` is changed. Any change to the public key *should* invalidate the signature except with probability 1/q where q is the order of the Pallas curve.)

**Comment by dconnolly** [comment]
> I don't understand why the [original code](https://github.com/ZcashFoundation/zebra/pull/2219/files#diff-ac055069f1186b8eb04bfdf6c938ab4fdaebb119a3779eb9b3a7214751690e1dL84-L89) wouldn't make the signature invalid. That merits a more thorough investigation.
> 
> (There are two cases: if `bytes[2]` is initially 2 (mod 32) then `bytes[2]` becomes 0 which is a change; otherwise `bytes[2]` becomes nonzero and therefore `bytes[j]` is changed. Any change to the public key *should* invalidate the signature except with probability 1/q where q is the order of the Pallas curve.)

@hdevalence originally wrote this tweak test for redjubjub, maybe he can clarify how to original tweak is intended to modify a jubjub point/key, vs how it may(?) not work for a pallas point.

**Comment by dconnolly** [comment]
@

> I don't understand why the [original code](https://github.com/ZcashFoundation/zebra/pull/2219/files#diff-ac055069f1186b8eb04bfdf6c938ab4fdaebb119a3779eb9b3a7214751690e1dL84-L89) wouldn't make the signature invalid. That merits a more thorough investigation.
> 
> (There are two cases: if `bytes[2]` is initially 2 (mod 32) then `bytes[2]` becomes 0 which is a change; otherwise `bytes[2]` becomes nonzero and therefore `bytes[j]` is changed. Any change to the public key _should_ invalidate the signature except with probability 1/q where q is the order of the Pallas curve.)

So it looks like the original tweak to the `pallas::Point` is resulting in an invalid point, rather than a still-valid pubkey, so the test is failing not because we are trying to verify a signature with a well-formed but incorrect `VerificationKey` and succeeding when we should be failing, but because we are allowing the test to fail when we produce a malformed Pallas point.

**Comment by dconnolly** [comment]
Another clue: in redpallas in this repo, we switched to use `ChaChaRng::from_seed()` as opposed to `::seed_from_u64()`. We might be hitting cases for redpallas we never hit with redjubjub?

https://github.com/ZcashFoundation/redjubjub/blob/e2940a465d62012581b89800fef23ec6dc241d40/tests/proptests.rs#L136

https://github.com/ZcashFoundation/zebra/blob/a6e272bf1cd14d8c34a9b9bf6d48078cd04ce3cf/zebra-chain/src/primitives/redpallas/tests/prop.rs#L129

**Comment by dconnolly** [comment]
> Another clue: in redpallas in this repo, we switched to use `ChaChaRng::from_seed()` as opposed to `::seed_from_u64()`. We might be hitting cases for redpallas we never hit with redjubjub?
> 
> https://github.com/ZcashFoundation/redjubjub/blob/e2940a465d62012581b89800fef23ec6dc241d40/tests/proptests.rs#L136
> 
> https://github.com/ZcashFoundation/zebra/blob/a6e272bf1cd14d8c34a9b9bf6d48078cd04ce3cf/zebra-chain/src/primitives/redpallas/tests/prop.rs#L129

hehehehe yup, reproduced with redjubjub:


image


image

**Comment by dconnolly** [comment]
> > Another clue: in redpallas in this repo, we switched to use `ChaChaRng::from_seed()` as opposed to `::seed_from_u64()`. We might be hitting cases for redpallas we never hit with redjubjub?
> > https://github.com/ZcashFoundation/redjubjub/blob/e2940a465d62012581b89800fef23ec6dc241d40/tests/proptests.rs#L136
> > https://github.com/ZcashFoundation/zebra/blob/a6e272bf1cd14d8c34a9b9bf6d48078cd04ce3cf/zebra-chain/src/primitives/redpallas/tests/prop.rs#L129
> 
> hehehehe yup, reproduced with redjubjub:
> 
> image
> 
> image

Therefore I do not think there is a problem with any curve math related to pallas, I think this is a tweaked test that also had this weird behavior on redjubjub, and we have to fix both.

**Comment by dconnolly** [comment]
Turns out you don't even need the different rng to reproduce this issue in redjubjub tests, just to change the weighting of the tweak test strategy to heavily weigh the `ChangePubkey` tweak, say reversing the weights of `None` and `ChangePubkey`.

**Comment by dconnolly** [comment]
The test was eating malformed keys and reporting them as 'this signature correctly failed to verify against this (malformed) key', not, 'this is a malformed key therefore we cannot even attempt to verify the signature for this case'. In my changes in this PR, we always are checking a signature with a well-formed key, and actually checking that the signature validation fails, not just that the key bytes are a well-formed key. I will make this explicit also..

**Comment by teor2345** [comment]
> The test was eating malformed keys and reporting them as 'this signature correctly failed to verify against this (malformed) key', not, 'this is a malformed key therefore we cannot even attempt to verify the signature for this case'. In my changes in this PR, we always are checking a signature with a well-formed key, and actually checking that the signature validation fails, not just that the key bytes are a well-formed key. I will make this explicit also..

Thanks for getting to the bottom of this!

**Pull request merged**
