### PR TITLE
Fix the storage of anchors in the state

### PR DESCRIPTION
**Pull request by conradoplg**
## Motivation

#2407 added note commitment trees and anchors to the state. However I got the storage wrong: we should store the root as a key with an empty value (to make it work as a set) instead of using the height as the key and the root as the value.

This fixes that.

### Specifications

N/A

### Designs

https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures

## Solution

Use the correct key/value

## Review

Anyone can review this.

This is blocking regenerating the cached state, which in turn is blocking testing other state work.

After this is accepted we can regenerate the cached state.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

N/A

---
This change is [Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2563)

### CODE REVIEW

**Review by teor2345 — COMMENTED** [review]
Looks good!

Normally, we would increment the state version for a format change like this.

But I don't think we need to right now, because:
* the previous state version was in the last release, but Zebra is still in alpha
* we're going to increment the version for value pools soon anyway
  * so we'll clear out any heights in that column family
* heights and anchors have different sizes, so they will never compare equal
  * so we'll never try to deserialize an anchor as `()` and panic
* RocksDB allows different-sized keys in the same column family
* there is no `FromDisk` implementation for anchors, and we don't impl `FromDisk` for keys
  * so we'll never try to deserialize a height as an anchor and panic

Also, if I'm wrong, and we do panic or get errors, we can just tell that one user to delete their database and re-sync.

Can someone double-check my reasoning here, and approve the PR?

**Comment by teor2345** [comment]
Or we can just increment the format version anyway, it doesn't cost us anything, because we haven't rebuilt the cached state yet.

**Comment by conradoplg** [comment]
> Can someone double-check my reasoning here, and approve the PR?

> Or we can just increment the format version anyway, it doesn't cost us anything, because we haven't rebuilt the cached state yet.

I agree with the reasoning but I also agree that we can just increment the version. I've just did that and will regenerate the state using this branch while I wait for a final approval.

**Review by dconnolly — APPROVED** [review]
✅

**Pull request merged**
