### PR TITLE
change(docs): Fix typos in Zebra book treestate RFC draft

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Review by arya2 — APPROVED** [review]
Thank you for catching and fixing this!

**Comment by arya2** [comment]
It seems there are CI issues related to running jobs from a fork:

> Error: google-github-actions/auth failed with: retry function failed after 4 attempts: gitHub Actions did not inject $ACTIONS_ID_TOKEN_REQUEST_TOKEN or $ACTIONS_ID_TOKEN_REQUEST_URL into this job. **This most likely means the GitHub Actions workflow permissions are incorrect, or this job is being run from a fork.**

https://github.com/ZcashFoundation/zebra/actions/runs/3550647296/jobs/5964583896#step:3:17

**Comment by arya2** [comment]
Merging it into an intermediary branch to bypass the issue.

**Comment by teor2345** [comment]
> It seems there are CI issues related to running jobs from a fork:
> 
> > Error: google-github-actions/auth failed with: retry function failed after 4 attempts: gitHub Actions did not inject $ACTIONS_ID_TOKEN_REQUEST_TOKEN or $ACTIONS_ID_TOKEN_REQUEST_URL into this job. **This most likely means the GitHub Actions workflow permissions are incorrect, or this job is being run from a fork.**
> 
> https://github.com/ZcashFoundation/zebra/actions/runs/3550647296/jobs/5964583896#step:3:17

This is ticket #4529, which discourages external developers from contributing to Zebra.

@mpguerra what's the priority for fixing errors like this, to allow external contributors to submit Zebra PRs without lots of spurious errors?

**Pull request merged**
