### PR TITLE
fix(rpc): Make the verbosity argument optional in the getblock RPC

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

When `s-nomp` mines a block with Zebra, it double-checks that block was accepted by the node using `getblock`. Currently, this fails with:
> 2023-02-02 11:59:27 [Pool]      [zcash_testnet] (Thread 1) Submitted Block using submitblock successfully to daemon instance(s)                          
> 2023-02-02 11:59:27 [Pool]      [zcash_testnet] (Thread 1) We thought a block was found but it was rejected by the daemon, share data: {"job":"ccce","ip":"::ffff:127.0.0.1","port":1234,"worker":"tmRGc4CD
1UyUdbSJmTUzcB6oDqk4qUaHnnh.worker1","height":2213653,"difficulty":0.05,"shareDiff":"0.16859053","blockDiff":0.062643492,"blockDiffActual":0.062643492,"blockHash":"002f73c6b1fb5a58137955d83aaef22a20921ec
fca5d64ce6798664c2b8d27fe","error":{"unknown":"check coin daemon logs"}}  

This is a confusing message for users (and developers!), because the block is actually accepted in the chain.

### Specifications

The default for `verbosity` is 1:
https://zcash.github.io/rpc/getblock.html

## Solution

- Make the `verbosity` argument optional with a default of 1
- Update existing tests
- Add new snapshots and test vectors

## Review

This is not on the critical path because it's just annoying and confusing - it doesn't actually block testing progress.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Review by arya2 — APPROVED** [review]
Looks good.

**Comment by arya2** [comment]
In the merge queue:

> block-source-validateproposal-proposal-is-not-based-on-the-current-best-chain-tip-previous-block-hash-must-be-the-best-chain-tip

https://github.com/ZcashFoundation/zebra/actions/runs/4078692209/jobs/7029791337#step:8:290

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by teor2345** [comment]
> In the merge queue:
> 
> > block-source-validateproposal-proposal-is-not-based-on-the-current-best-chain-tip-previous-block-hash-must-be-the-best-chain-tip
> 
> https://github.com/ZcashFoundation/zebra/actions/runs/4078692209/jobs/7029791337#step:8:290

This looks like it will be fixed by PR #6091, so I'll retry this PR.

**Pull request merged**
