### PR TITLE
fix(perf): Decrease the peer handshake timeout to 3 seconds, to speed up the initial sync

### LINKED ISSUE #4155: Full synchronization test times out in CI
## Motivation

The full chain synchronization test is currently timing out in CI. We should find a way to speed up synchronization so that it doesn't time out.

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

In #4155, we want to speed up Zebra's initial sync.

One way to do that is to choose faster peers.

## Solution

- Decrease the peer handshake timeout to 3 seconds

Close #4155

## Review

Anyone can review this PR.

If it makes the sync faster, we should merge it, and open a ticket for a longer-term solution.
If it doesn't make the sync faster, we should close it.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

- open a ticket for a longer-term solution

### CODE REVIEW

**Comment by teor2345** [comment]
I'm running a full sync test here:
https://github.com/ZcashFoundation/zebra/actions/runs/2230475345

The time to beat is 5h47m.

**Comment by teor2345** [comment]
Full sync took 5h41m, which is about 4 minutes faster. So we should merge this temporary fix.

**Comment by teor2345** [comment]
I opened #4226 for the long-term follow-up.

**Review by oxarbitrage — APPROVED** [review]
ok

**Pull request merged**
