### PR TITLE
fix(rpc): Fix Merkle root transaction order in getblocktemplate RPC method

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

Block templates returned by the getblocktemplate RPC need to be valid.

## Solution

- Sort `mempool_txs` before generating a default merkle root for the template

## Review

Anyone can review.

See #5884 for testing.

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [x] Does the code do what the ticket and PR says?
    - [x] Does it change concurrent code, unsafe code, or consensus rules?
  - [x] How do you know it works? Does it have tests?

### CODE REVIEW

**Review by teor2345 — APPROVED** [review]
Thanks for this fix!

**Comment by teor2345** [comment]
Failed due to #5958:
> #27 ERROR: failed to push us-docker.pkg.dev/zealous-zebra/zebra/zebrad-test:pr-5957: failed to copy: io: read/write on closed pipe

https://github.com/ZcashFoundation/zebra/actions/runs/3925766571/jobs/6710902148#step:9:931

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by mpguerra** [comment]
did we create an issue for this? it's ok if not just trying to track things

**Comment by arya2** [comment]
> did we create an issue for this? it's ok if not just trying to track things

We didn't create an issue for this.

**Pull request merged**
