### PR TITLE
change: Refactor error handling for block subsidies

### PR DESCRIPTION
**Pull request by upbqdn**
## Motivation

Zebra unnecessarily panics when calculating block subsidies for blocks with heights in the slow start interval.

Depends-On: #8729.

## Solution

- Support all heights when calculating the halving divisor.
- Refactor `block_subsidy()`:
	- Return an error instead of panicking for blocks with height in the slow start interval.
	- Explain why we're returning an error for those blocks.
	- Return `SubsidyError` instead of `amount:Error`.
- Refactor error conversion.
- Add new error variants.

### Tests

Existing tests should suffice. Some tests needed adjustments.

### PR Author's Checklist

- [x] The PR name will make sense to users.
- [ ] The PR provides a CHANGELOG summary.
- [x] The solution is tested.
- [x] The documentation is up to date.
- [x] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR Author's checklist is complete.
- [ ] The PR resolves the issue.

### CODE REVIEW

**Review by arya2 — DISMISSED** [review]

**Comment by upbqdn** [comment]
@mergifyio update

**Comment by oxarbitrage** [comment]
Is it is possible to point this pull request to the main branch?

**Comment by upbqdn** [comment]
It is. We can merge #8729 first.

**Comment by mpguerra** [comment]
@oxarbitrage can you please review this one now in @arya2's absence?

**Review by arya2 — APPROVED** [review]

**Pull request merged**
