### PR TITLE
change(tests): adds RPC request client for condensing shared code

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

To reduce repetition in acceptance tests and improve maintainability.

## Solution

- Refactor shared code into `RPCRequestClient`

## Review

Anyone can review

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by dconnolly** [comment]
@mergify update

**Review by teor2345 — DISMISSED** [review]
Thanks!

Normally we wouldn't want to do big refactors during an audit. But this is test code, so it's not being audited.

Can you also refactor these raw RPC calls?

https://github.com/ZcashFoundation/zebra/blob/c447b03223005e7a4f1a71aa046fc19047d83f35/zebrad/tests/common/lightwalletd/sync.rs#L185-L189

https://github.com/ZcashFoundation/zebra/blob/c447b03223005e7a4f1a71aa046fc19047d83f35/zebrad/tests/acceptance.rs#L1347-L1354

https://github.com/ZcashFoundation/zebra/blob/c447b03223005e7a4f1a71aa046fc19047d83f35/zebrad/tests/acceptance.rs#L1427-L1430

https://github.com/ZcashFoundation/zebra/blob/c447b03223005e7a4f1a71aa046fc19047d83f35/zebrad/tests/acceptance.rs#L2054-L2063

**Review by oxarbitrage — APPROVED** [review]
Looks great.

**Comment by gustavovalverde** [comment]
@mergifyio update

**Comment by oxarbitrage** [comment]
@mergifyio update

**Pull request merged**
