### PR TITLE
change(state) Shares the known_utxos fields of SentBlocks and QueuedBlocks to avoid unnecessary removals and re-additions

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

To share the known_utxos between SentHashes and QueuedBlocks to avoid removing and re-adding them from and to a HashMap. 

## Solution

 - Nest QueuedBlocks and SentBlocks inside PendingBlocks and return an iterator that adds hashes from dequeue_children that adds the hash and outpoints of dequeued blocks to SentBlocks.
 - Move known_utxos field to PendingBlocks and only remove elements from it during pruning.
 
### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by arya2** [comment]
This seems less important now that I'm looking at the end-product, we can potentially close this PR.

**Comment by arya2** [comment]
@Mergifyio update

**Comment by teor2345** [comment]
I have a channel UTXO bug fix that will conflict with this PR.

**Comment by teor2345** [comment]
@arya2 did you want to rebase this PR on the latest PR #5257 (and optionally #5339), or did you want to close it?

It seems low risk, but it's not a release blocker, and we also want to finish this work and tag the release.

(If it's not merged by the time we start tagging the release, we'll have to close it, because we're not doing refactors after we tag the audit code.)

**Comment by arya2** [comment]
> (If it's not merged by the time we start tagging the release, we'll have to close it, because we're not doing refactors after we tag the audit code.)

It would be nice to merge it before then if possible, and I wouldn't mind closing it otherwise.

**Comment by teor2345** [comment]
> > (If it's not merged by the time we start tagging the release, we'll have to close it, because we're not doing refactors after we tag the audit code.)
> 
> It would be nice to merge it before then if possible, and I wouldn't mind closing it otherwise.

Feel free to open a ticket for the refactor, and link to your branch. We might do it later if we need to modify this code.

**Pull request closed without merging**
