### PR TITLE
Add user agent metrics

### LINKED ISSUE #2871: Add connection user-agent metrics to Zebra
## Motivation

To diagnose #1904, we want to check if DNS seeders or block explorers are connecting to Zebra.

This involves adding user-agent metrics to Zebra.

## Implementation Suggestion

Copy and tweak the existing connection version metrics.
(It's a very small change.)

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

It is important for us to have remote user agent metrics: Closes https://github.com/ZcashFoundation/zebra/issues/2871

## Solution

Add user agent metrics (thanks @jvff for the help there) and add a new row to the peer dashboard with the user agent chart.

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Run grafana and import the modified peer dashboard, make sure it is being populated.

## Follow Up Work

I think and probably other metrics can be a pie chart or similar. At some point we can review all our dashboards and make some decisions on chart types.

### CODE REVIEW

**Review by teor2345 — COMMENTED** [review]
Looks good!

Can we also count the user agents for obsolete peers?

We don't need to graph it yet, but that information might come in handy if we're trying to diagnose issues with obsolete peers.

**Comment by oxarbitrage** [comment]
> Can we also count the user agents for obsolete peers?
>
> We don't need to graph it yet, but that information might come in handy if we're trying to diagnose issues with obsolete peers.

Makes sense, added it at https://github.com/ZcashFoundation/zebra/pull/2957/commits/eb6a2790ed5215dfc8339fc08adea7f326087f

ua_obs

**Review by teor2345 — COMMENTED** [review]
This looks good, but I haven't checked the dashboard yet.

**Review by conradoplg — APPROVED** [review]
Looks good! 

image

I'll leave this unmerged for now since I'm not sure if we should merge before the beta release or not

**Pull request merged**
