### PR TITLE
Deploy zebrad containers via managed instance group

### LINKED ISSUE #496: Create a zebrad healthcheck
Something we can hit (perhaps with an HTTP request) to ensure that the node is up and healthy when trying to scale out a fleet of nodes.

### PR DESCRIPTION
**Pull request by dconnolly**
Also default command to 'zebrad connect' until 'start' is fleshed out.

### CODE REVIEW

**Review by hdevalence — DISMISSED** [review]
LGTM.  We should figure out when to switch to the `start` command.

**Review by yaahc — COMMENTED** [review]
where does this default to `zebrad connect`? I only see `zebrad seed` at the end of the docker file and nothing that looks like an invocation anywhere else.

**Comment by hdevalence** [comment]
@yaahc it was changed back in 
8b76a3b

**Review by yaahc — DISMISSED** [review]
Aah, okay, LGTM then.

**Review by yaahc — DISMISSED** [review]

**Pull request merged**
