### PR TITLE
Check that Zebra is only using one version of tokio

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Duplicate tokio dependencies might result in hard-to-diagnose bugs in Zebra.
This happens because code expects a single instance of some structs, but there are multiple instances running.

If we add duplicate dependencies, Zebra compiles slower, and its binaries will be larger.
This slows down CI, and can fill up CI disks.

### Scheduling

This is unexpected work in Sprint 21, to make sure that tokio is upgraded correctly.

It should be merged *with* the tokio roll-up PR.

## Solution

- Require a single tokio version in `deny.toml` 
- Ban tokio git sources in `deny.toml` 
- Allow remaining and new duplicates caused by the tokio upgrade

## Review

@jvff should review this PR.

It is based on PR #2986.

### Reviewer Checklist

  - [ ] CI passes when combined with the tokio upgrades
  - [ ] `deny.toml` changes makes sense

### CODE REVIEW

**Review by jvff — DISMISSED** [review]

**Comment by jvff** [comment]
Nice catch! I didn't know about that file :sweat: 

EDIT: Nevermind, just realized this is an extension of #2986.

**Comment by jvff** [comment]
Would it make sense to merge this PR into #2986 and merge this after the Tokio upgrade? That would help to avoid feature creep in the rollup PR. IMHO, we could upgrade to Tokio first, and then fix any bugs that this PR finds afterwards.

**Comment by teor2345** [comment]
> Would it make sense to merge this PR into #2986 and merge this after the Tokio upgrade? That would help to avoid feature creep in the rollup PR. IMHO, we could upgrade to Tokio first, and then fix any bugs that this PR finds afterwards.

This PR tests that the dependencies are correct in the rollup PR.

Duplicate crates can cause weird runtime errors and test failures.
The duplicate checks might also reveal missed dependency updates, which could require extra code updates.

So I think it's helpful to include it in the rollup, to avoid a half-broken `main` branch.

**Review by jvff — APPROVED** [review]

**Comment by jvff** [comment]
Merged through #2994.

**Pull request closed without merging**
