### PR TITLE
fix(ci): Remove redundant build-chain-no-features job

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Once we merge PRs #4637 and #4640, this job will be redundant.
Depends-On: #4637 

## Review

Anyone can review this low priority PR.

### Reviewer Checklist

  - [x] Job is gone

### CODE REVIEW

**Comment by teor2345** [comment]
@mergifyio update

**Review by gustavovalverde — DISMISSED** [review]
LGTM

**Review by dconnolly — DISMISSED** [review]

**Comment by teor2345** [comment]
This will probably have merge conflicts with PR #4637, feel free to fix them.
(Just two jobs deleted next to each other.)

**Review by gustavovalverde — APPROVED** [review]
Re-approving after solved merge conflict

**Pull request merged**
