### PR TITLE
fix(doc): Fix an incorrect consensus-critical ZIP 212 comment

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

This comment is potentially confusing, because the consensus rule reference is wrong.

## Review

This is a low priority consensus docs bug.

### Reviewer Checklist

  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by oxarbitrage** [comment]
I see some problems in the CI with billing not enabled https://github.com/ZcashFoundation/zebra/actions/runs/6567215057/job/17839508993?pr=7774 

I think this might had been temporal so i am running the full workflows again.

**Review by oxarbitrage — APPROVED** [review]
oops, thanks!

**Comment by oxarbitrage** [comment]
> I think this might had been temporal so i am running the full workflows again.

Didn't help, i now upgraded witth the base branch to see if the errors go away.

**Comment by teor2345** [comment]
This seems to be an infrastructure issue, I'm just going to restart that job:

> get block template / Run get-block-template test
> The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

https://github.com/ZcashFoundation/zebra/actions/runs/6580053486?pr=7774

**Pull request merged**
