### PR TITLE
imp(ci): test full sync when pushing to main

### PR DESCRIPTION
**Pull request by gustavovalverde**
## Motivation

This will allow faster merges to main, and reduce the considerably when a CI fails because of deployment or infrastructure bugs.

This is a temporal fix.

Related: https://github.com/ZcashFoundation/zebra/issues/4090

## Solution

- Test full sync in `main`

## Review

@teor2345 or @conradoplg can review this

### CODE REVIEW

**Review by teor2345 — APPROVED** [review]
Can you open a ticket to change this back, and schedule it for next week?

**Review by teor2345 — CHANGES_REQUESTED** [review]
The full validation tests are required by Mergify, so we also need to remove them from its config.

**Comment by gustavovalverde** [comment]
Oh, wait. Those are 2 different checks, I think we've been confusing that 😅

The full validation test is the one using the cached state. Which just takes a few minutes after #4073

**Comment by teor2345** [comment]
> Oh, wait. Those are 2 different checks, I think we've been confusing that 😅

We don't need to change anything about the full sync test, because PRs don't wait for it, and they don't fail if it fails.

> The full validation test is the one using the cached state. Which just takes a few minutes after #4073

We need to change the full validation test, because it is failing due to cached state infrastructure bugs.
It takes a few minutes for some PRs. But if the cached state needs to be rebuilt, it takes a few hours.

Can we re-do the changes in this PR for the full validation test?

**Comment by gustavovalverde** [comment]
@teor2345 before proceeding with those changes, this PR is a good example, as it's waiting for the Full sync https://github.com/ZcashFoundation/zebra/pull/4096

Even if it fails and it gets merged, I think it will keep waiting for the full sync until it ends. If that's the case, we still need to merge this one.

**Comment by teor2345** [comment]
> @teor2345 before proceeding with those changes, this PR is a good example, as it's waiting for the Full sync #4096
> 
> Even if it fails and it gets merged, I think it will keep waiting for the full sync until it ends. If that's the case, we still need to merge this one.

I'm not sure exactly what is going on here. It's possible mergify or GitHub is just a bit slow.

Mergify says it is waiting for:
> check-success=Test stable on macOS-latest

That job finished 9 minutes ago:
https://github.com/ZcashFoundation/zebra/runs/5983376268?check_suite_focus=true

If mergify is waiting for the full sync, that's a bug in mergify, because that job is not mentioned in the Mergify config or branch protection rules. And mergify doesn't have it in its PR or job status.

Can we confirm the details of the full sync problem before we take any action?

**Comment by teor2345** [comment]
> Can we confirm the details of the full sync problem before we take any action?

I think what is happening is that these PRs contain mergify changes, so they will never merge automatically:
https://github.com/ZcashFoundation/zebra/pull/3940/files#diff-dcdc7e558c3de57ed664315abfe65892d731523da4d59d992f324b891453c430

I'll merge them both manually.

**Comment by gustavovalverde** [comment]
We have to do this even to fix the disk that we want to use for `main`, but I'll approach this differently in another PR

**Pull request closed without merging**
