### PR TITLE
doc: add tokio-console page in book dev section

### PR DESCRIPTION
**Pull request by dconnolly**
## Motivation

While getting `tokio-console` working against `zebrad` I longed for handy docs like the ones we have for `lightwalletd`. 

## Solution

Adds a page to the dev section of the Zebra book with instructions of how to build `zebrad` with the optional `tokio-console` support enabled, install `tokio-console`, and use it with `zebrad`. This is a dev page and not a user page as we don't expect 'regular' users to be profiling `zebrad` performance with `tokio-console`.  

## Review

There is some slight duplication between comments in the `zebrad/Cargo.toml` on how to compile `zebrad` with the appropriate `RUSTFLAGS` and `--features` - should we deduplicate? Or is this low concern?

### Reviewer Checklist

  - [ ] Instructions are sufficient
  - [ ] Instructions are appropriately categorized
  - [ ] Deduplication required?

### CODE REVIEW

**Comment by gustavovalverde** [comment]
Now that I see this PR, shouldn't we have sections with links in our main README.md linking to this kind of documentation? It's easier if the main README has links targeting other important documentation like this one, `lightwalletd`, the `cli`, etc.

That should be another PR.

Here's a simple example with an index sending you to specific parts of the READMEor to other READMEs across the repository https://github.com/docker/build-push-action

**Comment by teor2345** [comment]
> There is some slight duplication between comments in the `zebrad/Cargo.toml` on how to compile `zebrad` with the appropriate `RUSTFLAGS` and `--features` - should we deduplicate? Or is this low concern?

I think we should link to the docs from `Cargo.toml`, so they don't get out of sync.

**Comment by teor2345** [comment]
> Now that I see this PR, shouldn't we have sections with links in our main README.md linking to this kind of documentation? It's easier if the main README has links targeting other important documentation like this one, `lightwalletd`, the `cli`, etc.

Yep, we should be moving details out of our README into linked docs.

**Review by teor2345 — APPROVED** [review]
These instructions look good, let's do the README cleanup in another ticket.

**Comment by teor2345** [comment]
@mergifyio update

**Pull request merged**
