### PR TITLE
Start node-problem-detector on deployed instances to collect memory stats

### PR DESCRIPTION
**Pull request by dconnolly**
## Motivation

The current default metrics available in gcloud about our zebrad nodes deployed on VMs don't have metrics about memory usage.

## Solution

Add google-monitoring-enabled=true metadata to deployed instances

Enables the Node Problem Detector on Container-Optimized OS, which collects metrics on memory usage, open tcp connections, processes, cpu steal, swap usage, on top of existing host-collected metrics.

## Review

Not urgent.

### CODE REVIEW

**Review by teor2345 — DISMISSED** [review]
Looks great, and it should help us monitor memory issues like #1486 and #1487

**Comment by dconnolly** [comment]
Unfortunately this metadata flag doesn't seem to get picked up when using any of the `create-with-container` instance deployment variants, it works fine for plain ol' `gcloud compute instances create`. I'll play around with [options](https://cloud.google.com/container-optimized-os/docs/how-to/monitoring) like startup scripts /cloud init

**Comment by teor2345** [comment]
These look good, but I'm not sure if they actually work, and if they need another review.

Also I think there is a conflict with #1529.

**Comment by dconnolly** [comment]
Moving to draft while I keep trying options that work with the `create-with-container` command variants: https://github.com/ZcashFoundation/zebra/pull/1523#issuecomment-745396658

**Comment by dconnolly** [comment]
When deploying containers to containers I just cannot get these memory metrics out. Closing. :/

**Pull request closed without merging**
