### PR TITLE
Verify orchard spend auth

### LINKED ISSUE #2317: Validate Orchard SpendAuth signatures for Transaction::V5
## Motivation

We need to validate Orchard Spend Auth signatures as part of validating NU5 consensus rules.

### Specifications

- [ ] Validate Orchard Action SpendAuth signatures:
image https://zips.z.cash/protocol/protocol.pdf#actiondesc

## Solution

Queue up the Orchard Action SpendAuth signatures with the `RedPallasVerifier` instance, getting a future. Check the `Result `of that future as `Ok` as part of validating all the async consensus checks, without errors.

### Alternatives

Do RedPallas signature verification one-by-one, or synchronously. 

## Related Work

https://github.com/ZcashFoundation/zebra/issues/2103
#2318

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

https://github.com/ZcashFoundation/zebra/issues/2317

### Specifications

https://zips.z.cash/protocol/protocol.pdf#actiondesc

## Solution

Verify orchard spend auth very similar to sapling. No tests are currently included.

## Review

This is just a draft and it is based on https://github.com/ZcashFoundation/zebra/pull/2441 as the code was added into `verify_orchard_shielded_data()`. The relevant commit is https://github.com/ZcashFoundation/zebra/commit/8cbe813b8517668729314e07a59da0028fce9906

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

### CODE REVIEW

**Review by teor2345 — DISMISSED** [review]
Can you please split this PR from #2441?
#2441 is blocked on bug #1939, but this PR isn't.

We might also need to do some additional checks before we can validate Orchard spend authorizations. This is something we should check with the spec and a cryptographer.

**Comment by oxarbitrage** [comment]
> Can you please split this PR from #2441?

Force pushed to do this.

**Comment by teor2345** [comment]
@conradoplg can you review the cryptography in this PR, and make sure we've covered all the Orchard Spend Auth consensus rules?

@jvff can you check that the new validation function fits the refactor you've just done?

**Review by jvff — COMMENTED** [review]
Looks good to me, but I did not check the cryptography rules.

**Review by conradoplg — APPROVED** [review]
Looks good!

**Pull request merged**
