### PR TITLE
fix(doc): Clarify the cooperation between Zebra and `zcashd` in `README.md`

### PR DESCRIPTION
**Pull request by sandakersmann**
Fixed one typo in README.md

### CODE REVIEW

**Comment by upbqdn** [comment]
Thank you very much for the PR @sandakersmann.

In this case, _"interoperably"_ is an adverb meaning "in an interoperable manner". The whole sentence means that Zebra and `zcashd` can maintain the Zcash network together in an interoperable manner.

If the phrasing still doesn't seem right, let us know, and we'll come up with a more suitable alternative.

I'm closing this for now, but if you feel like you spotted any other issue, feel free to submit more PRs. We always welcome them.

**Comment by sandakersmann** [comment]
@upbqdn "interoperably" does not exist in the dictionary:

 https://www.oxfordlearnersdictionaries.com/spellcheck/english/?q=interoperably

**Comment by upbqdn** [comment]
Yea, that word is peculiar, and is probably going to cause confusion. What if we replaced it with "together"?

**Comment by sandakersmann** [comment]
Sounds good :)

**Comment by upbqdn** [comment]
If you want to fix it, push a new commit, and I'll merge it. Otherwise, I'll do it over the week.

**Comment by sandakersmann** [comment]
It's ready to be merged :)

**Review by upbqdn — APPROVED** [review]
Thank you for clarifying the README.

**Pull request merged**
