### PR TITLE
Make tests faster by decreasing the chance of generating shielded transactions

### LINKED ISSUE #2575: Some tests take more than 60 seconds in a standard (maybe slow) notebook
We want to decrease the time of execution of at least the following state tests:

```
test service::finalized_state::tests::prop::blocks_with_v5_transactions has been running for over 60 seconds
test service::non_finalized_state::tests::prop::finalized_equals_pushed has been running for over 60 seconds
test service::non_finalized_state::tests::prop::forked_equals_pushed has been running for over 60 seconds
test service::non_finalized_state::tests::prop::rejection_restores_internal_state has been running for over 60 seconds
```

The default number of tests is already at 1 (https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/finalized_state/tests/prop.rs#L18) so we can't try the simple fix we did at https://github.com/ZcashFoundation/zebra/pull/2574

### PR DESCRIPTION
**Pull request by conradoplg**
## Motivation

We have some tests that take too long, in particular some proptests.

Part of the reason is that updating the note commitment trees is expensive, and `PreparedChain` creates ~100 blocks which are comitted to the state in the tests which requires updating trees.

One possible approach is to decrease the number of shielded transactions generated in the tests, which makes the test go faster.

## Solution

Use `option::weighted` to generate shielded transactions 10% of the time instead of the default 50%.

## Review

This is very low priority because it's part of https://github.com/ZcashFoundation/zebra/issues/2575 which is not scheduled for this sprint. But it may help development go faster. (People may want to cherry-pick the commit while developing)

This is a draft because I'm not sure if this is a good approach nor what exact percentage we should use. 10% (5 times less) seem OK considering we generate 100 blocks in `PreparedChain` (i.e. there will be still plenty of shielded transactions) but I'm not sure about other tests. (Another possibility would be to feed the percentage as an argument somehow to the strategy so that we use a lower value only in the context of `PreparedChain`, but it would take a bit more work)

May close https://github.com/ZcashFoundation/zebra/issues/2575

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

**Comment by teor2345** [comment]
What's the smallest number of blocks we use in any proptest where shielded is relevant?

I think it might be around 100, because:
* the default number of cases is 256, and most tests use one block: 256 blocks
* some tests use around 20 blocks with 8 cases: 160 blocks
* long chain tests use 104 blocks with 1 case: 104 blocks

Can we double-check the lowest `chain length * proptest cases`?
Because if it's 100, then I think 10% is fine.

**Comment by conradoplg** [comment]
> What's the smallest number of blocks we use in any proptest where shielded is relevant?
> 
> I think it might be around 100, because:
> 
> * the default number of cases is 256, and most tests use one block: 256 blocks
> * some tests use around 20 blocks with 8 cases: 160 blocks
> * long chain tests use 104 blocks with 1 case: 104 blocks
> 
> Can we double-check the lowest `chain length * proptest cases`? Because if it's 100, then I think 10% is fine.

I started checking this but halfway I realized that seems to be a really error-prone process. Even if this holds now it may no longer hold in the future. So it seems better to change this PR to only enable the low percentage inside the PreparedChain and similar tests

(For the record the only exception I found during that is `block_roundtrip` which uses 10 proptest cases and a single block)

**Comment by teor2345** [comment]
> > Can we double-check the lowest `chain length * proptest cases`? Because if it's 100, then I think 10% is fine.
> 
> I started checking this but halfway I realized that seems to be a really error-prone process. Even if this holds now it may no longer hold in the future. So it seems better to change this PR to only enable the low percentage inside the PreparedChain and similar tests
> 
> (For the record the only exception I found during that is `block_roundtrip` which uses 10 proptest cases and a single block)

We can add a shielded fraction argument with a default of 0.5. Then we can keep calling `arbitrary` in most tests, but use `arbitrary_with` in the tests we want to customise.

https://docs.rs/proptest/1.0.0/proptest/arbitrary/fn.arbitrary_with.html

**Comment by conradoplg** [comment]
I'm closing this because the required change is not trivial and this is not a big issue anymore since CPU-intensive dependencies are now optimized by default. It's also possible to run those tests with `--release` to greatly speed them up during testing/development if required.

**Pull request closed without merging**
