### PR TITLE
consolidate arbitrary impls to one file in zebra-chain

### LINKED ISSUE #220: Break out Block* components into submodules
> Arrange the submodules of block to match transaction, splitting out into submodules, e.g., header, serialize, tests, etc, and then re-exporting components from block?

https://github.com/ZcashFoundation/zebra/pull/212#discussion_r374342673

### PR DESCRIPTION
**Pull request by yaahc**
Implements the last bullet from https://github.com/ZcashFoundation/zebra/issues/220#issuecomment-582644124 and fixes #220 

@hdevalence I couldn't find any ZcashSerialize or ZcashDeserialize impls outside of `serialize.rs` in the `transactions` module so I already checked off that box in the above issue.

### CODE REVIEW

**Comment by dconnolly** [comment]
I finally replied over on #220 that I don't think we should consolidate all `Arbitrary` impls in one place, I'm in favor of keeping them beside the code they are testing to avoid drift:

https://github.com/ZcashFoundation/zebra/issues/220#issuecomment-650405891

**Comment by yaahc** [comment]
@dconnolly ACK, I'll leave this open for @hdevalence and @teor2345 to weigh in on our group preference and we can close or merge this accordingly.

Personally I prefer keeping the `Arbitrary` near the impls because we already cannot move the Arbitrary derive for types that don't implement it manually and for more consistent organization.

**Comment by dconnolly** [comment]
> @dconnolly ACK, I'll leave this open for @hdevalence and @teor2345 to weigh in on our group preference and we can close or merge this accordingly.
> 
> Personally I prefer keeping the `Arbitrary` near the impls because we already cannot move the Arbitrary derive for types that don't implement it manually and for more consistent organization.

Yeah we should discuss this, both proposals have pros and cons so

**Comment by teor2345** [comment]
When I wrote and modified Arbitrary impls and tests, it was easier to have them near their types.

That was particularly important when I added a length constraint to block parsing. I probably would have forgotten the arbitrary tests otherwise.

**Comment by yaahc** [comment]
Okay, I opened an issue to discuss how we should handle trait organization across the project, if we end up deciding to keep arbitrary impls near their types I'll go back and audit the existing impls to make sure none of them are far away from their type definitions.

**Comment by yaahc** [comment]
@ZcashFoundation/zebra-team based on the discussion in https://github.com/ZcashFoundation/zebra/issues/556 I'm assuming this PR is good to merge

**Comment by dconnolly** [comment]
@yaahc I would also move `test_vectors.rs` into the `tests/` dir now.

**Review by dconnolly — APPROVED** [review]
LGTM! 🧹

**Pull request merged**
