### PR TITLE
B. change(db): Tune database file compaction

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We need Zebra to sync faster for the cached state lightwalletd tests.

Tuning database files makes it slightly faster (3%).

### Specifications

The RocksDB wiki recommends using LZ4 compression, but the default is Snappy:
https://github.com/facebook/rocksdb/wiki/Compression#configuration

## Solution

- Use 128MB of RAM for database memtables

This does not need a state version increment, RocksDB should handle it transparently.

This is a bit faster than the default memtable settings:
- https://github.com/ZcashFoundation/zebra/runs/5842837263?check_suite_focus=true

It finished in 5h45m, but the base branch finished in 5h55m:
https://github.com/ZcashFoundation/zebra/runs/5842837263?check_suite_focus=true

## Review

Anyone can review this PR.

This PR is based on PR #4027.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Existing Tests Pass
  - [ ] Sync is faster or database is smaller

### CODE REVIEW

**Comment by teor2345** [comment]
These changes don't seem to make the initial sync any faster.

**Review by dconnolly — DISMISSED** [review]
Future work: make this value configurable from the zebra.state config file?

**Comment by teor2345** [comment]
> Future work: make this value configurable from the zebra.state config file?

We did ok with the default value for a long time. And every config generates bug reports from people who try it out, and then it causes problems :-)

But if users need it, it's easy to make it configurable.

**Comment by teor2345** [comment]
I just tweaked the priority so this PR merges along with #3978

**Review by dconnolly — APPROVED** [review]

**Comment by teor2345** [comment]
@mergifyio refresh

**Pull request merged**
