### PR TITLE
Bump sha2 from 0.9.8 to 0.10.0

### PR DESCRIPTION
**Pull request by conradoplg**
## Motivation

This is https://github.com/ZcashFoundation/zebra/pull/3172 but with a fix to make it work (requires importing a trait)

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

**Comment by conradoplg** [comment]
`bip0039`, `bs58`, `ed25519-zebra`, `zcash-primitives` all import `sha2 v0.9.8` so we either need to wait for them to update or add an exception in `deny.toml`. Since there isn't anything critical in v0.10.0 I suggest just waiting for now. Let me know if I should create an issue.

**Comment by teor2345** [comment]
> `bip0039`, `bs58`, `ed25519-zebra`, `zcash-primitives` all import `sha2 v0.9.8` so we either need to wait for them to update or add an exception in `deny.toml`. Since there isn't anything critical in v0.10.0 I suggest just waiting for now. Let me know if I should create an issue.

Let's create an optional issue, and schedule it with the ECC NU5 crate dependency updates?

**Comment by conradoplg** [comment]
> > `bip0039`, `bs58`, `ed25519-zebra`, `zcash-primitives` all import `sha2 v0.9.8` so we either need to wait for them to update or add an exception in `deny.toml`. Since there isn't anything critical in v0.10.0 I suggest just waiting for now. Let me know if I should create an issue.
> 
> Let's create an optional issue, and schedule it with the ECC NU5 crate dependency updates?

Done in https://github.com/ZcashFoundation/zebra/issues/3202

**Comment by teor2345** [comment]
Obsoleted by ticket #3202. (We can re-open this PR when that ticket gets scheduled in a sprint.)

**Pull request closed without merging**
