### PR TITLE
Reverse displayed endianness of transaction and block hashes

### LINKED ISSUE #1031: Reverse displayed endianness of transaction and block hashes.
**Is your feature request related to a problem? Please describe.**

Zcashd, for bad legacy reasons, displays block and transaction hashes as the hex-encoding of the *reversal* of the byte string.  This is solely a display choice.  Hashes are parsed as byte sequences as normal, but displayed differently.  Why? They are displayed as if the hex output (a byte string) were actually encoding of an integer, which can have an ordering for proof of work checks.

In Zebra, we try not to replicate bad legacy decisions from Zcashd by default, unless we have a good reason to do to (or have to, for compatibility).  So we originally didn't implement this reverse-endianness display.  However, this is a pretty bad user-experience.

**Describe the solution you'd like**

- [x] Change `Debug`, `Display`, and `FromStr` for `block::Hash` to display the encoding of the reversed byte sequence, and to reverse a hex encoding during parsing.
- [x] Remove the `byte_reverse_hex` function from `zebra-utils/src/bin/zebra-checkpoints/main.rs`.
- [x] Use `zebrad revhex` to reverse all existing `block::Hash` literals in the source code.  To find them, commenting out the `FromStr` impl should turn all `.parse()` invocations into compile errors.
  - [x] Compile using `cargo test`, so that you find hash literals in test code.
  - [x] Regenerate the hard-coded `main-checkpoints.txt` and `test-checkpoints.txt’ checkpoint lists using the modified `zebra-checkpoints` binary.
- [x] Change `Debug`, `Display`, and `FromStr` for `transaction::Hash` to display the encoding of the reversed byte sequence, and to reverse a hex encoding during parsing.
- [x] Use `zebrad revhex` to reverse all existing `transaction::Hash` literals in the source code.  To find them, commenting out the `FromStr` impl should turn all `.parse()` invocations into compile errors.
  - [x] Compile using `cargo test`, so that you find hash literals in test code.
- [x] Remove the `zebrad revhex` command.
  - [x] Stop using `zebrad revhex` in the `zebrad-hash-lookup` script.

### PR DESCRIPTION
**Pull request by vramana**
Fixes #1031

### CODE REVIEW

**Review by daira — APPROVED** [review]
Looks good so far.

**Comment by teor2345** [comment]
Hi @vramana just checking if you needed some help to finish this off?

**Comment by vramana** [comment]
Actually yes. I tried to get full zcashd node up an running locally but it crashes. I was busy with some other work. So I didn't get to debugging it. I'll ping for some help today.

**Comment by teor2345** [comment]
> Actually yes. I tried to get full zcashd node up an running locally but it crashes. I was busy with some other work. So I didn't get to debugging it. I'll ping for some help today.

My time zone probably won't match up with yours until Monday, so feel free to try Discord.

Also feel free to write as much of the PR as you can, and ask the reviewer to test with zcashd.

**Comment by vramana** [comment]
@teor2345 Magically my zcashd node didn't crash. I have a full node now.

**Comment by oxarbitrage** [comment]
Replaced by https://github.com/ZcashFoundation/zebra/pull/1171 , please lets continue any discussion there. Thanks and sorry for the inconvenience but i was not able to push commits into the vramana branch directly.

**Pull request closed without merging**
