### PR TITLE
Derive Arbitrary impls for a bunch of chain and network types

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We need `Arbitrary` impls to write proptests for internal and external network protocol messages.

## Solution

- Derive Arbitrary impls for a bunch of chain and network types
- Add proptest `Strategy` impls for `u32` and full datetimes

The code in this pull request has:
  - [x] Documentation Comments
  - [x] Enables Unit Tests and Property Tests

## Review

Anyone can review, as long as they understand proptests.

## Related Issues

Split off #2160

These tests might have caught security issue #2148 

## Follow Up Work

Rest of #2160

### CODE REVIEW

**Comment by teor2345** [comment]
I think the macOS `sync_large_checkpoints_mainnet` failure was caused by #2172 or #2154, and it should be fixed by #2181 or #2182.

I don't think it's related to this PR, because this PR only changes proptests.

https://github.com/ZcashFoundation/zebra/pull/2179/checks?check_run_id=2635749551#step:10:644

**Comment by dconnolly** [comment]
The `zebra-chain::primitives` module has been a place for cryptographic primitives such as the signature schemes and the proof types, rather than 'utils' or other base types. Sometime like `Amount` got its own module. Should we have a top-level `arbitrary` module for things like this?

**Review by dconnolly — COMMENTED** [review]
@teor2345  The zebra-chain::primitives module has been a place for cryptographic primitives such as the signature schemes and the proof types, rather than 'utils' or other base types. Sometime like Amount got its own module. Should we have a top-level arbitrary module for things like this?

**Comment by teor2345** [comment]
> @teor2345 The zebra-chain::primitives module has been a place for cryptographic primitives such as the signature schemes and the proof types, rather than 'utils' or other base types. Sometime like Amount got its own module. Should we have a top-level arbitrary module for things like this?

These particular strategies are serialization-specific and consensus-critical, so I moved them to `serialization::arbitrary`.

**Comment by teor2345** [comment]
@jvff this should be ready to merge if you want to use it in the #2178 tests

**Review by dconnolly — APPROVED** [review]

**Pull request merged**
