### PR TITLE
v1.0.0-beta.9 release

### PR DESCRIPTION
**Pull request by conradoplg**
---
name: Release Checklist Template
about: Checklist of versioning to create a taggable commit for Zebra
title: ''
labels:
assignees: ''

---

### Which Crates to Increment

To check if any of the top-level crates need version increments, go to the zebra GitHub code page: https://github.com/ZcashFoundation/zebra and use the last modified dates of each crate. Alternatively you can use the github compare tool and check the `main` branch against the last tag ([Example](https://github.com/ZcashFoundation/zebra/compare/v1.0.0-alpha.15...main)). `git diff --stat <previous-release-tag> origin/main` is also useful to see what's changed.

- [x] Increment the crates that have new commits since the last version update
- [x] Increment any crates that depend on crates that have changed
- [x] Keep a list of the crates that haven't been incremented, to include in the PR

### How to Increment Versions

Zebra follows [semantic versioning](https://semver.org).

Semantic versions look like: `MAJOR`.`MINOR`.`PATCH[`-`TAG`.`PRE-RELEASE]`

#### Pre-Release Crates

Pre-Release versions have a `TAG` like "alpha" or "beta". For example: `1.0.0-alpha.0`

1. Increment the `PRE-RELEASE` version for the crate.

#### Unstable Crates

Unstable versions have a `MAJOR` version of zero. For example: `0.1.0`

1. Follow stable crate versioning, but increment the `MINOR` version for breaking changes

#### Stable Crates

For example: `1.0.0`

Increment the first version component in this list, and reset the other components to zero:
1. MAJOR versions for breaking public API changes and removals
    * check for types from dependencies that appear in the public API
2. MINOR versions for new features
3. PATCH versions for bug fixes
    * includes dependency updates that don't impact the public API

### Version Locations

Once you know which versions you want to increment, you can find them in the:
- [x] zebra* `Cargo.toml`s
- [x] tower-* `Cargo.toml`s
- [x] `zebra-network` protocol user agent: https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/constants.rs
- [x] `README.md`
- [x] `book/src/user/install.md`
- [x] `Cargo.lock`: automatically generated by `cargo build`

#### Version Tooling

You can use `fastmod` to interactively find and replace versions.

For example, you can do something like:
```
fastmod --extensions rs,toml,md --fixed-strings '1.0.0-alpha.12' '1.0.0-alpha.13'
fastmod --extensions rs,toml,md --fixed-strings '0.2.9' '0.2.10' tower-batch
fastmod --extensions rs,toml,md --fixed-strings '0.2.8' '0.2.9' tower-fallback
```

### Reviewing Version Bumps

Check for missed changes by going to:
`https://github.com/ZcashFoundation/zebra/tree/<commit-hash>/`
Where `<commit-hash>` is the hash of the last commit in the version bump PR.

If any Zebra or Tower crates have commit messages that are **not** a version bump, we have missed an update.

Also check for crates that depend on crates that have changed. They should get a version bump as well.

## README

As we resolve various outstanding known issues and implement new functionality with each release, we should double check the README for any necessary updates.

We should check and update if necessary:

- [x] The "Known Issues" section

to ensure that any items that are resolved in the latest release are no longer listed in the README.

## Change Log

**Important**: Any merge into `main` deletes any edits to the draft changelog. Once you are ready to tag a release, copy the draft changelog into `CHANGELOG.md`.

We follow the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format.

We use [the Release Drafter workflow](https://github.com/marketplace/actions/release-drafter) to automatically create a [draft changelog](https://github.com/ZcashFoundation/zebra/releases).

To create the final change log:
- [x] Copy the draft changelog into `CHANGELOG.md`
- [x] Delete any trivial changes. Keep the list of those, to include in the PR
- [x] Combine duplicate changes
- [x] Edit change descriptions so they are consistent, and make sense to non-developers
- [x] Check the category for each change
  - prefer the "Fix" category if you're not sure

#### Change Categories

From "Keep a Changelog":
* `Added` for new features.
* `Changed` for changes in existing functionality.
* `Deprecated` for soon-to-be removed features.
* `Removed` for now removed features.
* `Fixed` for any bug fixes.
* `Security` in case of vulnerabilities.

### Create the Release PR

After you have the version increments and the updated changelog:

- [x] Push the version increments and the updated changelog into a branch
      (name suggestion, example: `v1.0.0-alpha.0-release`)
- [x] Create a release PR by adding `&template=release-checklist.md` to the
      comparing url ([Example](https://github.com/ZcashFoundation/zebra/compare/v1.0.0-alpha.0-release?expand=1&template=release-checklist.md)).
      - [ ] Add the list of deleted changelog entries as a comment to make reviewing easier.
      - [ ] Also add the list of not-bumped crates as a comment (can use the same comment as the previous one).
- [x] While the PR is being reviewed, turn on [Merge Freeze](https://www.mergefreeze.com/installations/3676/branches) to stop other PRs merging

### Create the Release

- [x] Once the release PR has been approved and merged, create a new release
      using the draft release as a base, by clicking the Edit icon
      in the [draft release](https://github.com/ZcashFoundation/zebra/releases).
- [x] Set the release title to `Zebra ` followed by the version tag, for example:
      `Zebra 1.0.0-alpha.0`
- [x] Copy the final changelog of this release to the release description
      (starting just _after_ the title `## [Zebra ...`)
- [x] Set the tag name to the version tag, for example: `v1.0.0-alpha.0`
- [x] Set the release to target the `main` branch
- [x] Mark the release as 'pre-release' (until we are no longer alpha/beta)
- [x] Publish the release

## Final Testing

- [x] After tagging the release, test that the exact `cargo install` command in
      `README.md` works (`--git` behaves a bit differently to `--path`)
- [ ] Turn off [Merge Freeze](https://www.mergefreeze.com/installations/3676/branches) to start merging PRs again

If the build fails after tagging:
1. fix the build
2. increment versions again, following these instructions from the start
3. update `README.md` with a **new** git tag
4. update `CHANGELOG.md` with details about the fix
5. tag a **new** release

### CODE REVIEW

**Comment by conradoplg** [comment]
All crates were bumped.

Entries not mentioned in changelog:

- build(deps): bump docker/setup-qemu-action from 1 to 2 (#4347)
- build(deps): bump docker/login-action from 1.14.1 to 2.0.0 (#4346)
- build(deps): bump docker/build-push-action from 2.10.0 to 3.0.0 (#4345)
- build(deps): bump docker/setup-buildx-action from 1 to 2 (#4344)
- Fix incorrect AddressBalance name in diagram (#4342)
- build(deps): bump docker/metadata-action from 3.8.0 to 4.0.1 (#4319)
- build(deps): bump tonic from 0.7.1 to 0.7.2 (#4325)
- build(deps): bump tonic-build from 0.7.1 to 0.7.2 (#4326)
- change(deps): update locked version of indirect dependency `crossbeam-channel` to `0.5.4` (#4331)
- build(deps): bump prost from 0.10.1 to 0.10.2 (#4321)
- build(deps): bump num-integer from 0.1.44 to 0.1.45 (#4260)
- refactor(test): fix confusing environmental variable names in Rust code (#4301)
- change(test): Stop requiring cached lightwalletd state for the send transaction test (#4302)
- build(deps): bump thiserror from 1.0.30 to 1.0.31 (#4259)
- build(deps): bump serde\_json from 1.0.80 to 1.0.81 (#4290)
- build(deps): bump serde from 1.0.136 to 1.0.137 (#4261)
- build(deps): bump serde\_json from 1.0.79 to 1.0.80 (#4262)
- build(deps): bump tokio from 1.18.0 to 1.18.1 (#4280)
- build(deps): bump semver from 1.0.7 to 1.0.9 (#4258)
- feat(ci): clarify lint workflow names (#4279)
- fix(ci): typo causing docker run command to split (#4277)
- build(deps): bump tonic-build from 0.7.0 to 0.7.1 (#4249)
- fix(state): Tweak ephemeral state directory path and improve docs (#4248)
- fix(ci): Increase docs job timeout (#4246)
- build(deps): bump docker/metadata-action from 3.7.0 to 3.8.0 (#4241)
- build(deps): bump tokio from 1.17.0 to 1.18.0 (#4242)
- build(deps): bump tj-actions/changed-files from 18.7 to 19 (#4240)
- fix(ci): Install cmake to fix zcash-params Dockerfile build failure (#4235)
- build(deps): bump spandoc from 0.2.1 to 0.2.2 (#4221)
- build(deps): bump toml from 0.5.8 to 0.5.9 (#4127)
- change(state): Remove `active_value` field from `ChainTipSender` (#4175)
- build(deps): bump reqwest from 0.11.9 to 0.11.10 (#4200)
- build(deps): bump serde\_with from 1.12.1 to 1.13.0 (#4190)
- build(deps): bump google-github-actions/auth from 0.7.0 to 0.7.1 (#4188)
- build(deps): bump inferno from 0.11.1 to 0.11.2 (#4191)
- Fix typos (#4186)
- build(deps): bump owo-colors from 3.3.0 to 3.4.0 (#4189)
- build(deps): bump reviewdog/action-actionlint from 1.23.0 to 1.24.0 (#4161)
- build(deps): bump codecov/codecov-action from 2.1.0 to 3.1.0 (#4162)
- build(deps): bump actions/checkout from 3.0.1 to 3.0.2 (#4163)
- Fix typos (#4164)
- fix(test): don't create another 'state' directory when implementing ZebradTestDirExt (#4158)
- Fix typos (#4112)
- fix(doc): Fix link to run page in installation docs (#4144)
- change(test): Refactor how extra arguments are handled when spawing lightwalled (#4067)

**Comment by conradoplg** [comment]
https://github.com/ZcashFoundation/zebra/runs/6327325222?check_suite_focus=true

```
#27 exporting to image
#27 pushing layers 0.8s done
#27 ERROR: failed to authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized
------
 > exporting to image:
------
error: failed to solve: failed to fetch oauth token: unexpected status: 401 Unauthorized
Error: buildx failed with: error: failed to solve: failed to fetch oauth token: unexpected status: 401 Unauthorized
```

One more victim of #4234  :cry:

**Review by teor2345 — APPROVED** [review]
Looks great, thanks!

**Comment by teor2345** [comment]
> Error: buildx failed with: error: failed to solve: failed to fetch oauth token: unexpected status: 401 Unauthorized

I re-ran the failed jobs, hopefully they will pass in the next few hours.

This PR will need to be manually merged, because merge freeze blocks all Mergify PRs.

**Pull request merged**
