### PR TITLE
Enable 'full' feature in tokio for zebra-test

### PR DESCRIPTION
**Pull request by conradoplg**
## Motivation

Currently in `main` you can't compile a test for a single package, i.e. `cargo test -p zebra-chain --lib`. This is because it uses `zebra-test` which requires the `sync` feature from `tokio`, but only enables it in `dev-dependencies`. However, `dev-dependencies` of dependencies are ignored:

> Note that dev-dependencies in dependencies are always ignored, this is only relevant for the top-level package or workspace members.

https://doc.rust-lang.org/cargo/reference/resolver.html

## Solution

Enable `full` in  `zebra-test`, not only on `dev-dependencies`.
My rationale is that `zebra-test` is not a test in itself, so for it to be used it needs to specify its proper dependencies in `dependencies` and not `dev-`

But I'm not confident this is the best solution. Possible options / improvements:

- Don't use `full` but actually enumerate everything that is required
- Instead add a `dev-dependencies` in each package that uses it

Some package include `zebra-test`in `dependencies` (e.g. `zebra-chain`) instead of just in `dev-dependencies`, so this PR would end up making Zebra always use `full` in `tokio`.

## Review

This is not urgent, but this issue prevents running specific tests in some packages (e.g. `zebra-chain`) while developing which is annoying.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

**Comment by teor2345** [comment]
> Some package include `zebra-test`in `dependencies` (e.g. `zebra-chain`) instead of just in `dev-dependencies`, so this PR would end up making Zebra always use `full` in `tokio`.

I think this is fine, because the `zebra-test` entries in `dependencies` are all `optional`. They are only enabled when the `proptest-impl` feature is active.

**Comment by teor2345** [comment]
>     * Don't use `full` but actually enumerate everything that is required

Cargo's [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) means our test builds will all use `full` anyway.

So I don't think enumerating requirements will help much, unless we want to enumerate the features that are required for each crate, and commit to maintaining that going forward. (I'm not sure it's worth the extra work.)

**Review by teor2345 — APPROVED** [review]
This seems like a good solution to me, but I'm leaving it open for others to review or comment.

**Review by oxarbitrage — APPROVED** [review]
I am fine with this.

**Comment by teor2345** [comment]
Alright let's merge this, because it will block me next time I make changes to `zebra-chain`.

**Pull request merged**
