### PR TITLE
tests(rpc): Add grpc test for `GetTaddressBalanceStream` and `GetAddressUtxosStream`

### LINKED ISSUE #4362: Add Address stream gRPC tests
## Motivation

We're missing these gRPC tests:
- GetTaddressBalanceStream
- GetAddressUtxosStream

This is a medium priority, because there are already tests for the same JSON-RPC methods.

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We skipped a few grpc tests that had streams involved. This PR add tests for `GetTaddressBalanceStream` and `GetAddressUtxosStream`.

Close https://github.com/ZcashFoundation/zebra/issues/4362

## Solution

Add simple grpc tests for `GetTaddressBalanceStream` and `GetAddressUtxosStream`.

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

**Review by teor2345 — COMMENTED** [review]
This looks good, but it's not in CI yet (that's ticket #4168).

How did you test it?

**Comment by oxarbitrage** [comment]
This was tested locally, similar to how all the other grpc tests were done. Ill try to make https://github.com/ZcashFoundation/zebra/issues/4168

**Comment by teor2345** [comment]
We're getting reports of some parsing failures in the gRPC tests, but we're not exactly sure why.

I think having them in CI would be good, but I don't want to block this PR on that.

**Review by teor2345 — APPROVED** [review]
Thanks, let's get this merged, and fix any bugs that come up in CI later.

**Comment by teor2345** [comment]
> This was tested locally, similar to how all the other grpc tests were done. Ill try to make #4168

@oxarbitrage you might want to talk to @gustavovalverde about CI tests, because we are currently working on cached state fixes. So #4168 might be blocked.

**Pull request merged**
