### PR TITLE
fix(sync): Make the syncer ignore some new block verification errors

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

The syncer skips some duplicate block errors, but we added new duplicate block errors in #4937.

This might fix the full sync errors on the `main` branch.

## Solution

- Ignore "block has already been sent to be committed to the state" errors
- Make a finalized state error into "block has already been committed to the state"

## Review

I talked through this with @arya2 already.

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [x] Does the code do what the ticket and PR says?
  - [x] How do you know it works? Does it have tests?

## Follow Up Work

We should fix these permanently using typed errors, so we don't introduce this sort of bug again:
- #2908

### CODE REVIEW

**Review by arya2 — DISMISSED** [review]
This looks good!

**Review by arya2 — APPROVED** [review]

**Comment by arya2** [comment]
@Mergifyio refresh

**Comment by arya2** [comment]
A couple failures in the merge queue, the clippy lint:

> error: the `Err`-variant returned from this function is very large
    --> zebrad/src/components/sync.rs:1027:10
     |
1027 |     ) -> Result<(), BlockDownloadVerifyError> {
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 144 bytes

https://github.com/ZcashFoundation/zebra/actions/runs/3387578258/jobs/5628508335#step:8:501

and compiling in ubuntu-latest:

> 2022-11-03T18:02:59.1665948Z Couldn't compile the test.test src/components/mempool/crawler.rs - components::mempool::crawler (line 16) ... FAILED
> 2022-11-03T18:02:59.1670828Z 
> 2022-11-03T18:02:59.1671033Z failures:
> 2022-11-03T18:02:59.1671272Z 
> 2022-11-03T18:02:59.1675686Z failures:
> 2022-11-03T18:02:59.1686048Z     src/components/mempool/crawler.rs - components::mempool::crawler (line 16)

These are failing on the main branch too

**Comment by teor2345** [comment]
> These are failing on the main branch too

Looks like Rust 1.65:
https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#generic-associated-types-gats

I can open PRs to fix them now.

If it's not caused by this specific PR, can you please open a ticket, or ask the person on `main` branch failures to open one?
That's @oxarbitrage this week.

**Comment by arya2** [comment]
> Looks like Rust 1.65: https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#generic-associated-types-gats

Sounds about right. I created #5547.

**Comment by teor2345** [comment]
> > Looks like Rust 1.65: https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#generic-associated-types-gats
> 
> Sounds about right. I created #5547.

I try to catch these things by running nightly rust, but sometimes they slip through, or I ignore them, or they are merged right before the release.

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
@mergifyio refresh

**Pull request merged**
