### PR TITLE
Update async correctness docs and the async in Zebra RFC

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We've had some recent sync bugs around:
- mutex deadlocks
- future cancellation safety (dropped futures)
- task starvation

So it's probably time to document best practices.

This is unscheduled stable release work.

## Review

I've tagged all the Zebra developers for review, so that everyone gets a chance to understand these issues.

### Reviewer Checklist

  - [ ] Documentation is understandable
  - [ ] Documentation is correct

### CODE REVIEW

**Review by conradoplg — COMMENTED** [review]
This helps, thanks!

**Review by upbqdn — APPROVED** [review]
Thanks for all the clarifications.

**Comment by teor2345** [comment]
> Configuration problem:
> bors.toml: not found

@gustavovalverde oh well it was worth a try

**Comment by teor2345** [comment]
bors cancel

**Review by jvff — APPROVED** [review]

**Review by upbqdn — APPROVED** [review]

**Pull request merged**
