### PR TITLE
Reverse displayed endianness of transaction and block hashes

### LINKED ISSUE #1031: Reverse displayed endianness of transaction and block hashes.
**Is your feature request related to a problem? Please describe.**

Zcashd, for bad legacy reasons, displays block and transaction hashes as the hex-encoding of the *reversal* of the byte string.  This is solely a display choice.  Hashes are parsed as byte sequences as normal, but displayed differently.  Why? They are displayed as if the hex output (a byte string) were actually encoding of an integer, which can have an ordering for proof of work checks.

In Zebra, we try not to replicate bad legacy decisions from Zcashd by default, unless we have a good reason to do to (or have to, for compatibility).  So we originally didn't implement this reverse-endianness display.  However, this is a pretty bad user-experience.

**Describe the solution you'd like**

- [x] Change `Debug`, `Display`, and `FromStr` for `block::Hash` to display the encoding of the reversed byte sequence, and to reverse a hex encoding during parsing.
- [x] Remove the `byte_reverse_hex` function from `zebra-utils/src/bin/zebra-checkpoints/main.rs`.
- [x] Use `zebrad revhex` to reverse all existing `block::Hash` literals in the source code.  To find them, commenting out the `FromStr` impl should turn all `.parse()` invocations into compile errors.
  - [x] Compile using `cargo test`, so that you find hash literals in test code.
  - [x] Regenerate the hard-coded `main-checkpoints.txt` and `test-checkpoints.txt’ checkpoint lists using the modified `zebra-checkpoints` binary.
- [x] Change `Debug`, `Display`, and `FromStr` for `transaction::Hash` to display the encoding of the reversed byte sequence, and to reverse a hex encoding during parsing.
- [x] Use `zebrad revhex` to reverse all existing `transaction::Hash` literals in the source code.  To find them, commenting out the `FromStr` impl should turn all `.parse()` invocations into compile errors.
  - [x] Compile using `cargo test`, so that you find hash literals in test code.
- [x] Remove the `zebrad revhex` command.
  - [x] Stop using `zebrad revhex` in the `zebrad-hash-lookup` script.

### PR DESCRIPTION
**Pull request by oxarbitrage**
Replaces https://github.com/ZcashFoundation/zebra/pull/1056

- Cherry picked commit from @vramana where the hard work was done, hope this is ok.
- Fixed the test cases where it was failing.
- Fixed zebra-checkpoints binary.

Todo:

- [x] Get a new checkpoint list for mainnet and testnet. This will be done by @teor2345. I think we can just push the list once done into this PR.

Should close https://github.com/ZcashFoundation/zebra/issues/1031 when/if merged.

### CODE REVIEW

**Review by yaahc — DISMISSED** [review]

**Review by teor2345 — CHANGES_REQUESTED** [review]
We can't merge this PR yet - I still need to rebuild the full checkpoint lists.

**Review by teor2345 — DISMISSED** [review]
I rebuilt the checkpoint lists in commit  544c572.

**Comment by teor2345** [comment]
@oxarbitrage @yaahc I also found a few more places that needed updates:
- 9ab06709aed0a1c731180391c3a86224693cdc80 - zebrad-hash-lookup script
- 5c91a895a061c3eee7a8fdcd530f52a868ccc17e - fixed hash in `transaction::Hash` tests
- 2476f616897e8d17f819160a3e0b54ad7aeae263 - hash order comment
- cc0c1988df38b57e4855a617c434727cd3e3d6fa - `TransactionHash` to `transaction::Hash` from #905
  - included in this PR because it conflicts with the other transaction changes

**Comment by teor2345** [comment]
I also checked the list of tasks in #1031, and I'm running `zebrad start` on mainnet and testnet.

**Comment by teor2345** [comment]
I tried to test this change using `zebrad start`, but bugs in the sync, state, and network code prevented a full sync. See #1181, #1182, and #1183.

I still think we should merge this change, it's a low-risk improvement, and the bugs aren't likely to be related to this change.

**Review by hdevalence — APPROVED** [review]
LGTM, but did not test yet.

**Comment by vramana** [comment]
@oxarbitrage Thanks for picking up the PR. I was on vacation and couldn't find the time to finish the PR.

**Pull request merged**
