### PR TITLE
A. fix(shielded): use RwLock for note commitment tree root caches

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

As part of #3745, we need to share `zebra_state::Chain`s between threads. So we need to share cached note commitment tree roots between threads.

### API Reference

https://doc.rust-lang.org/std/sync/struct.RwLock.html#method.get_mut
https://doc.rust-lang.org/std/sync/struct.RwLock.html#method.read
https://doc.rust-lang.org/std/sync/struct.RwLock.html#method.write

### Design

I used an `RwLock`, because the cache is only written once after each note commitment tree update. Caches aren't shared between trees, because the cache needs to be consistent with each tree's notes.

Modifying the tree and clearing the cache doesn't require locking, because we already have exclusive access to the tree.

When filling the cache, there is no risk of deadlocks, because each tree has exclusive access to a single `RwLock`. If multiple threads queue on the lock, one of these scenarios happens:
- if the cache is empty, the first writer fills it, the other writers read the cache (exclusively), then subsequent threads share read access to the cache
- if the cache is full, all threads share read access to the cache

## Solution

- use RwLock for note commitment tree root caches

## Review

@conradoplg is most familiar with this code.

### Reviewer Checklist

  - [ ] Existing tests pass

## Follow Up Work

The rest of:
- #3745

### CODE REVIEW

**Comment by teor2345** [comment]
@mergifyio update

**Review by conradoplg — APPROVED** [review]
Looks good!

**Comment by conradoplg** [comment]
@Mergifyio update

**Comment by teor2345** [comment]
The macOS build timed out fetching the Zcash parameters.

**Comment by teor2345** [comment]
@mergifyio refresh

**Pull request merged**
