### PR TITLE
Draft RFC: Initial draft for basic network integration testing

### PR DESCRIPTION
**Pull request by teor2345**
## TODO

- [ ] Resolve testnet integration test issues
  - testnet node deployment #1222
  - re-enable testnet integration test #1791
- [x] Update the RFC with our current network integration tests
- [x] Merge it as a draft

## Outdated Solution

Here's our current plan for the first alpha:
- [x] Run sync tests on 2 large checkpoints in CI (Teor and Deirdre)
- [x] Run previous state sync 100+ block tests in CI (Jane and Deirdre)
- [x] Run fresh state sync to tip tests after merge (Deirdre)

### Related Issues

- RFC Ticket and Ideas: #1004
- Support Testnet eventually, after we deploy more `zcashd` instances to testnet in #1222

### CODE REVIEW

**Comment by hdevalence** [comment]
Let's call this one RFC7.

**Comment by teor2345** [comment]
Here's our current plan for the first alpha:
- [ ] Run sync tests on 2 large checkpoints in CI (Teor and Deirdre)
- [ ] Run previous state sync 100+ block tests in CI (Jane and Deirdre)
- [ ] Run fresh state sync to tip tests after merge (Deirdre)

**Comment by teor2345** [comment]
@yaahc @dconnolly is this RFC a good place to document the network integration tests?

We don't need a lot of detail - it can be quite short. But it would be good to write it down somewhere.

**Comment by yaahc** [comment]
> @yaahc @dconnolly is this RFC a good place to document the network integration tests?
> 
> We don't need a lot of detail - it can be quite short. But it would be good to write it down somewhere.

once @dconnolly has finished testing my test PR together with her infra PR and verified that it all works I think we will be good to start documenting.

**Comment by teor2345** [comment]
We decided to merge this RFC as a draft.

**Pull request merged**
