### PR TITLE
feat(log): Log the tracing level when it is set or reloaded

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Logging the tracing log level helps diagnose tokio-console config issues.

Related to #2112.

### Specifications

https://docs.rs/tracing/latest/tracing/level_filters/index.html#compile-time-filters

## Review

Anyone can review this low-priority PR.

### Reviewer Checklist

  - [ ] Existing tests pass

### CODE REVIEW

**Comment by teor2345** [comment]
Seems like a temporary network error:

> reviewdog: post failed for codespell: failed to create check: POST https://api.github.com/repos/ZcashFoundation/zebra/check-runs: 502 Server Error []
https://github.com/ZcashFoundation/zebra/runs/6618346164?check_suite_focus=true#step:4:8

**Review by oxarbitrage — COMMENTED** [review]
Need to push Cargo.toml ?

**Comment by teor2345** [comment]
> Need to push Cargo.toml ?

I needed some changes from the next PR, but not all of them.

**Review by conradoplg — APPROVED** [review]
Looks good

**Pull request merged**
