### PR TITLE
fix(ci): stop failing the send transaction test

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

In PR #4303, we required cached lightwalletd state for the send transaction test.
But that state is currently unreliable.

Depends-On: #4411

## Solution

- revert to the previous behaviour, were cached state is allowed, but not required

## Review

Anyone can review this PR, it's a high priority because it fixes a CI failure.

We expect the update lightwalletd sync test to fail, that's ticket #4415.

### Reviewer Checklist

  - [ ] send transaction test passes CI

## Follow Up Tasks

Revert this PR once #4415 is implemented.

### CODE REVIEW

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
I'm updating this PR to clear most of the test failures, the remaining one is:
- ticket #4415

**Review by conradoplg — APPROVED** [review]
Looks good.

Failed due to quota issues, retrying

**Comment by conradoplg** [comment]
> Anyone can review this PR, it's a high priority because it fixes a CI failure.
> 
> We expect the update lightwalletd sync test to fail, that's ticket #4415.

This looks good, but I'm bit confused by the intention.
This is currently failing `lightwalletd_update_sync` which seems expected per the comment above. But then what is the goal of this PR? I thought it would be to stop the CI from failing, but CI will keep failing with this. Not sure how to proceed.

**Comment by conradoplg** [comment]
> > Anyone can review this PR, it's a high priority because it fixes a CI failure.
> > We expect the update lightwalletd sync test to fail, that's ticket #4415.
> 
> This looks good, but I'm bit confused by the intention. This is currently failing `lightwalletd_update_sync` which seems expected per the comment above. But then what is the goal of this PR? I thought it would be to stop the CI from failing, but CI will keep failing with this. Not sure how to proceed.

Ah I think I get it, mergify picked up this to merge so I'm assuming we're allowing that test to fail. I wish GitHub would show those tests (which are allowed to fail) differently somehow...

**Comment by dconnolly** [comment]
> > > Anyone can review this PR, it's a high priority because it fixes a CI failure.
> > > We expect the update lightwalletd sync test to fail, that's ticket #4415.
> > 
> > 
> > This looks good, but I'm bit confused by the intention. This is currently failing `lightwalletd_update_sync` which seems expected per the comment above. But then what is the goal of this PR? I thought it would be to stop the CI from failing, but CI will keep failing with this. Not sure how to proceed.
> 
> Ah I think I get it, mergify picked up this to merge so I'm assuming we're allowing that test to fail. I wish GitHub would show those tests (which are allowed to fail) differently somehow...

I would love a ℹ️ icon or something, something that is more neutral than ❌

**Comment by teor2345** [comment]
> > > Anyone can review this PR, it's a high priority because it fixes a CI failure.
> > > We expect the update lightwalletd sync test to fail, that's ticket #4415.
> > 
> > 
> > This looks good, but I'm bit confused by the intention. This is currently failing `lightwalletd_update_sync` which seems expected per the comment above. But then what is the goal of this PR? I thought it would be to stop the CI from failing, but CI will keep failing with this. Not sure how to proceed.
> 
> Ah I think I get it, mergify picked up this to merge so I'm assuming we're allowing that test to fail. I wish GitHub would show those tests (which are allowed to fail) differently somehow...

Yep, the intention is to fix 1 of the 2 failures.

Unfortunately we can't disable the failing tests using the GitHub actions view, because they are all in the same workflow file.

**Pull request merged**
