### PR TITLE
Create `zebra-cli` stub crate

### PR DESCRIPTION
**Pull request by dconnolly**
## Motivation

We want to own our `zebra-*` crates on crates.io

## Solution

This is a stub crate for a binary named `zebra-cli`.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Review by teor2345 — COMMENTED** [review]
Do we also want to add a `zebra-tx` crate, to match `zcash-tx`?

I'm not sure if we'll ever have one, and it seems like a low priority, so it's ok to say "no that's not needed".

**Comment by teor2345** [comment]
Please update `Cargo.lock` to make the builds and CI checks pass.

**Comment by dconnolly** [comment]
> Please update `Cargo.lock` to make the builds and CI checks pass.

Done 👍 https://github.com/ZcashFoundation/zebra/pull/6484/commits/d4a77f954f66a3f7e5c36b535a09c2eeee47d25f

**Comment by dconnolly** [comment]
> Do we also want to add a `zebra-tx` crate, to match `zcash-tx`?
> 
> I'm not sure if we'll ever have one, and it seems like a low priority, so it's ok to say "no that's not needed".

Perhaps not in this PR

**Review by arya2 — APPROVED** [review]
This looks good now, thank you!

**Comment by arya2** [comment]
> Do we also want to add a zebra-tx crate, to match zcash-tx?

Could we add a command in `zebra-cli` or a binary in `zebra-utils` instead?

**Comment by dconnolly** [comment]
> > Do we also want to add a zebra-tx crate, to match zcash-tx?
> 
> Could we add a command in `zebra-cli` or a binary in `zebra-utils` instead?

Yeah I blew away the stub contents of the crate, which included at least one sub-command; I wouldn't mind supporting the `zcash-tx` behavior in `zebra-cli`

**Comment by dconnolly** [comment]
> > > Do we also want to add a zebra-tx crate, to match zcash-tx?
> > 
> > 
> > Could we add a command in `zebra-cli` or a binary in `zebra-utils` instead?
> 
> Yeah I blew away the stub contents of the crate, which included at least one sub-command; I wouldn't mind supporting the `zcash-tx` behavior in `zebra-cli`

(I blew it away because it was just a demo I made pulling in some unified address parsing code and displaying it as a a QR code)

**Comment by teor2345** [comment]
> > Do we also want to add a zebra-tx crate, to match zcash-tx?
> 
> Could we add a command in `zebra-cli` or a binary in `zebra-utils` instead?

This PR is about reserving the crate name in case we decide we want one in future.

So if we're pretty sure we'll never have a `zebra-tx` crate, it's not a priority.

**Pull request merged**
