### PR TITLE
zebrad: Create zebrad.toml in acceptance tests from ZebradConfig

### LINKED ISSUE #929: In the zebrad acceptance tests, create zebrad.toml by serialising a Config struct
Not in love with the string manipulation, and I expect this will only get more complicated. I think it would really be better to just have a `.with_config(Config { ... })` function that lets us manipulate the config more naturally rather than having to build up toml by hand.

_Originally posted by @yaahc in https://github.com/ZcashFoundation/zebra/pull/920_

### PR DESCRIPTION
**Pull request by vramana**
Fixes #929

I could not understand suggestion written in the issue description `.with_config(Config{..})`. The only way I could think of solving this is moving the `tempdir` function to `zebrad` crate. This PR will probably change the generated config file but locally all tests have passed.

### CODE REVIEW

**Comment by yaahc** [comment]
I think moving this test to Zebrad is likely the right decision 🙌

**Review by yaahc — APPROVED** [review]
Looks perfect, thank you.

**Review by oxarbitrage — APPROVED** [review]
I think that moving the function to `zebrad` acceptance tests is the right choice, actually i think is the only one reasonable other than repeating a config structure in `zebra-tests`. Well done.

Please note this PR will conflict with https://github.com/ZcashFoundation/zebra/pull/939 . We should merge this one first and then adapt the related as i think #939 will need changes.

**Comment by vramana** [comment]
@oxarbitrage Yes. I am aware of the conflict that's in the making :D I will resolve it once this PR merges.

**Review by dconnolly — APPROVED** [review]
LGTM! 🕺

**Pull request merged**
