### PR TITLE
change(state): Restrict access to types for database writes

### LINKED ISSUE #7418: fix(state): Don't expose arbitrary batches for database writes
Address the issue raised in https://github.com/ZcashFoundation/zebra/pull/7312#discussion_r1294514456.

### PR DESCRIPTION
**Pull request by upbqdn**
## Motivation

Close #7418.

Depends-On: #7437 

## Solution

This is a quick fix that makes `DiskWriteBatch` and `WriteDisk` available only in the finalized state.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by upbqdn** [comment]
My local tests passed with this PR. If the CI tests fail, we can close this PR without merging.

**Review by arya2 — DISMISSED** [review]

**Review by teor2345 — APPROVED** [review]
Previously this functionality was only available outside zebra-state in tests. Now it is restricted to the crate.

Since it doesn't seem to be used at all outside zebra-state, it's ok to limit it, but future tests that use the state might need to revert this change.

**Comment by teor2345** [comment]
(I've made this change depend on the open state PR to avoid merge conflicts.)

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by upbqdn** [comment]
@mergifyio refresh

**Pull request merged**
