### PR TITLE
fix log level default for server commands

### PR DESCRIPTION
**Pull request by yaahc**

### CODE REVIEW

**Comment by hdevalence** [comment]
FYI, the previous behaviour was intentional (`info` level when `-v` is passed and `warn` when it isn't).  I think it would be better if the meaning of the verbose flag didn't depend on the command.

**Comment by yaahc** [comment]
So you think the default log level for `zebrad start` should be warn only?

**Comment by hdevalence** [comment]
Yeah, that was the idea -- I don't think it's very important, I just wanted to note that it was an intentional change in order to restore handling of the `-v` flag (#831).

**Comment by oxarbitrage** [comment]
I think we should do `info` by default and `debug` with the `-v` flag.

**Pull request merged**
