### PR TITLE
fix(doc): consolidate firebase hosting in prod project

### PR DESCRIPTION
**Pull request by gustavovalverde**
## Motivation

Each documentation we're hosting using Firebase, is deployed to a different GCP project each. We're now using our `zfnd-prod-zebra` to deploy all Zebra services targeting users. And we'd like to have all documentation consolidated under a single GCP project.

### Complex Code or Requirements

A new action is being used, and a custom made step was required as the Workload Identity Provider is not supported, and we're no longer allowed to created long-lived JSON keys from our GCP projects.

## Solution

- Use `FirebaseExtended/action-hosting-deploy` action
- Deploy to new a single GCP project in `zfnd-prod-zebra` 
- Create a `production` environment in GitHub to use the same variable name for `$GCP_PROJECT`
- Deploy the different documentations in parallel
- PRs changing the documentation create a temporal URL to validate the changes

## Review

Anyone from DevOps

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work
- Do not redeploy all docs if just one is needed

### CODE REVIEW

**Comment by gustavovalverde** [comment]
@Mergify refresh

**Comment by gustavovalverde** [comment]
@arya2 @upbqdn do we actually need the `internal` docs published at https://doc-internal.zebra.zfnd.org/zebrad/ additionally to https://doc.zebra.zfnd.org/zebrad/ ?

I might be ignoring something, but I don't see much value added there.

**Comment by arya2** [comment]
> @arya2 @upbqdn do we actually need the `internal` docs published at https://doc-internal.zebra.zfnd.org/zebrad/ additionally to https://doc.zebra.zfnd.org/zebrad/ ?
> 
> I might be ignoring something, but I don't see much value added there.

I haven't found it very useful but it could be convenient for investigating Zebra without access to a dev environment.

We could publish the internal docs on https://doc.zebra.zfnd.org/zebrad/ so it's all in one place? I wouldn't mind just dropping the internal docs page altogether and asking developers to run `cargo doc open` if they want to use it.

**Comment by upbqdn** [comment]
Let's keep it. I use it every now and then, even today.

Having it only locally makes one unable to share links, for example.

**Review by arya2 — APPROVED** [review]
Looks good!

**Pull request merged**
