### PR TITLE
Add metrics for initial peer network protocol versions

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

As part of ticket #2797, we want to check the network protocol versions of the peers supplied by the Zcash DNS seeders.

### Designs

Zebra already has this information, we just need to add it to the logs and metrics.

## Solution

Seed Peer DNS Resolution:
- log the initial peers resolved from each seed
- add metrics for initial peer resolution, including the seed and remote peer IP
- add a grafana dashboard for seed peer resolution
- add a per-seed filter to the peer dashboard

Network Protocol Versions
- add tracing and metrics for peer network protocol versions
- add network protocol versions to  peers dashboard
- show peer network protocol versions for each seeder in the peer dashboard

## Review

Anyone can review this PR, but I think @conradoplg or @upbqdn have set up a Grafana instance already?

Merging this PR isn't urgent.

### Reviewer Checklist

  - [ ] Code records metrics and logs correctly
  - [x] Dashboards work

## Follow Up Work

- #2137
- #2797
- #2812

### CODE REVIEW

**Comment by teor2345** [comment]
This is what the mainnet dashboards look like (for seed peers and all peers):
Screen Shot 2021-09-29 at 11 58 00
Screen Shot 2021-09-29 at 11 58 28

**Comment by teor2345** [comment]
This is what the testnet dashboards look like:
Screen Shot 2021-09-29 at 11 58 14
Screen Shot 2021-09-29 at 11 58 38

**Comment by upbqdn** [comment]
This is what the mainnet dashboards look like for me for the first four minutes of running Zebra:

image

**Comment by upbqdn** [comment]
Here are the first few minutes of running on Testnet:
image

**Review by upbqdn — APPROVED** [review]

**Comment by upbqdn** [comment]
Adding `dev.testnet` and `dev.mainnet` also seems to be a good idea.

**Review by dconnolly — APPROVED** [review]

**Pull request merged**
