### PR TITLE
cleanup(deps): Remove unused `fpe` dependency and cleanup references

### PR DESCRIPTION
**Pull request by mpguerra**
## Motivation

When we removed unused orchard code we also remove our use of the `fpe` crate. However, we forgot to also remove this from `Cargo.toml`

## Solution

This change removes `fpe` from `Cargo.toml` and also from the list of dependencies that should not be audited

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [x] Does the code do what the ticket and PR says?
  - [x] How do you know it works? Does it have tests?

### CODE REVIEW

**Review by teor2345 — DISMISSED** [review]
Thanks, good catch!

**Review by teor2345 — APPROVED** [review]

**Comment by teor2345** [comment]
@mergifyio update

**Comment by dconnolly** [comment]
Why did this even fail?
image

**Comment by dconnolly** [comment]
image

**Comment by teor2345** [comment]
> Why did this even fail?

Can you please link to the error line in the failing job?

**Comment by teor2345** [comment]
> image

This looks like #5069, @gustavovalverde has asked us add a comment to that ticket linking to the error logs.

**Comment by teor2345** [comment]
@mergifyio update

**Pull request merged**
