### PR TITLE
fix(mergify): use low-priority queue for the correct jobs

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

This fixes an inverted match condition for the low priority queue.

You can see that these rules match a Critical PR here:
https://github.com/ZcashFoundation/zebra/pull/3405/checks?check_run_id=4945966369

## Solution

- remove the negation prefix `-` from the Low and Optional rules

## Review

@gustavovalverde can check I got this right.

This is a low priority, because `-P-Low` matches `Optional`, and `-P-Optional` matches `Low`, so the config still works.

### Reviewer Checklist

  - [ ] matches are correct

## Follow Up Work

We could just put PRs with any other priority or no priority in this queue instead. But that would be a functional change for a separate PR.

### CODE REVIEW

**Comment by teor2345** [comment]
The macOS job failed on `app_no_args`, seems like a slow CI machine causing a timeout.

**Comment by teor2345** [comment]
@mergifyio update

**Comment by gustavovalverde** [comment]
Nice catch @teor2345!

By the way, I wouldn't recommend using Mergify update on PRs
image

This causes the squash to include Mergify's bot as an author:
image

In the long run, this seems noisy (visually) and it also affects the repo analytics. Recently, @dconnolly made a comment referring to disabling this option 
image

I'll double-check, as Mergify always tests and merges with the latest trip from main. But I'm not sure if this is true with a single PR.

**Review by gustavovalverde — APPROVED** [review]

**Comment by gustavovalverde** [comment]
@teor2345 I've just realized that removing the Co-author from the merge commit message description also removes the bot from the final commit.

**Pull request merged**
