### PR TITLE
Split storage errors by match type: TXID or WTXID

### LINKED ISSUE #2819: Match rejected transactions correctly by TXID or WTXID
## Motivation

When receiving a mempool-bound transaction we check if it's in the rejected list, and if it is, we avoid downloading/verifying it.

However, this check currently uses `UnminedTxId` which is the WTXID for V5-onward.

### Specifications

https://zips.z.cash/zip-0401

> Each node also MUST hold a FIFO queue `RecentlyEvicted` of pairs `(txid, time)`, where the `time` indicates when the transaction with the given `txid` was evicted. The `txid` (rather than the `wtxid` ...) is used even for version 5 transactions after activation of NU5.

### Designs

For rejected _invalid_ transactions (i.e. transactions that failed verification or storage), Zebra should match:
  - transactions with failed effecting data (`SpendConflict`, `Expired`, missing inputs, nullifier conflicts): check for the same TXID (`mined_id()`) - **this ticket**
  - other rejection reasons: check for the same WTXID (`UnminedTxId`) - #2818 

If it's difficult to distinguish between verifier errors, all verification failures can be matched by WTXID. Then we can open a follow-up ticket to match missing inputs, nullifier conflicts, and `Expired` by `mined_id()`.

This may require some refactoring to allow looking up rejected transactions by their TXID, or splitting the rejected list in two (evicted and rejected?)

## Related Work

Invalid transactions are not currently being added to the rejected list; this is https://github.com/ZcashFoundation/zebra/issues/2818, so that must be done before this one.

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

ZIP-401 requires mempools to match some transaction rejections by `transaction::Hash`, rather than `UnminedTxId`.

Zebra already implements some rejections that should be matched by `transaction::Hash`. So we can modify our existing matches, and prepare for ZIP-401.

Closes #2819.

### Specifications

https://zips.z.cash/zip-0401

> Each node also MUST hold a FIFO queue `RecentlyEvicted` of pairs `(txid, time)`, where the `time` indicates when the transaction with the given `txid` was evicted. The `txid` (rather than the `wtxid` ...) is used even for version 5 transactions after activation of NU5.

### Designs

For rejected _invalid_ transactions (i.e. transactions that failed verification or storage), Zebra should match:
  - transactions with failed effecting data (`SpendConflict`, `Expired`): check for the same TXID (`mined_id()`) - **this ticket**
  - other rejection reasons: check for the same WTXID (`UnminedTxId`) - #2818

## Solution

- match `SpendConflict`, `Expired`, and `RandomlyEvicted` by `transaction::Hash`
- match `FailedVerification` by `UnminedTxId`

## Review

I'd like an initial review from @conradoplg and @upbqdn, because they're implementing the related ZIP-401 tickets.

Does this design work for you?
Is this a minimal change?

### Reviewer Checklist

  - [x] Code implements Specs and Designs
  - [x] Tests for Expected Behaviour
  - [x] Tests for Errors

## Follow Up Work

We might want to split `FailedVerification` into effects failures and authorization failures, see #2834.
But this change is not required for a minimal mempool implementation.

### CODE REVIEW

**Comment by conradoplg** [comment]
I like it!

For https://github.com/ZcashFoundation/zebra/pull/2821 I think we'll need to split this even more:

- `rejected_exact` (`invalid`) (cleared on `grow`)
- `rejected_same_effects`:
  - `expired` (cleared on `reset`)
  - `spend_conflict` (cleared on `grow`)
  - `excess` (cleared on ZIP-401 timeout)
  
Should we do this in this PR, or in a following one?

**Comment by teor2345** [comment]
> For #2821 I think we'll need to split this even more:
> 
>     * `rejected_exact` (`invalid`) (cleared on `grow`)
> 
>     * `rejected_same_effects`:
>       
>       * `expired` (cleared on `reset`)
>       * `spend_conflict` (cleared on `grow`)
>       * `excess` (cleared on ZIP-401 timeout)
> 
> 
> Should we do this in this PR, or in a following one?

I was planning on doing some of that split in #2694, and then whatever is left over we can do in #2821.

**Comment by teor2345** [comment]
Return `impl Iterator` rather than collecting or cloning vectors:
https://github.com/ZcashFoundation/zebra/pull/2827#discussion_r723500351

**Review by conradoplg — APPROVED** [review]
Looks good!

**Pull request merged**
