### PR TITLE
feat(checkpoints): Update mainnet and testnet checkpoints

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We need to update the checkpoints before the next release.

## Solution

Update checkpoints.

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

Release work: https://github.com/ZcashFoundation/zebra/issues/5423

### CODE REVIEW

**Review by gustavovalverde — APPROVED** [review]

**Comment by teor2345** [comment]
Failed due to a non_blocking_logger test hang on macOS.

That's fixed by PR ##5522, so we can just retry this one.

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
@mergifyio refresh

**Pull request merged**
