### PR TITLE
Split memory_state to avoid giant test module

### PR DESCRIPTION
**Pull request by yaahc**
## Motivation

Prior to this PR `memory_state` defined and implemented functionality for three different types, `Chain`, `NonFinalizedState`, and `QueuedBlocks`. Each of these components will need a fair number of unit tests, and I realized that as its currently organized it would be difficult to organize the tests or at a glance figure out which tests are testing which components.

## Solution

This PR changes the organization of `memory_state` such that each component it exports is defined in its own module. In follow up PRs each module will get its own test module, which will focus exclusively on unit tests for the item defined there-in.

The code in this pull request has:
  - ~~Documentation Comments~~
  - ~~Unit Tests and Property Tests~~

## Related Issues

- [Tracking Issue](https://github.com/ZcashFoundation/zebra/issues/1250)

## Follow Up Work

This PR doesn't implement any of the items mentioned in the above tracking issue, but it should make it easier to review the code that later does introduce said tests.

### CODE REVIEW

**Comment by yaahc** [comment]
blocked by https://github.com/ZcashFoundation/zebra/pull/1257, which it is based upon

**Comment by teor2345** [comment]
I merged #1257, so I think this PR is unblocked.

**Comment by teor2345** [comment]
(I'll review after the conflicts have been resolved, because that makes `git diff --color-moved` work better.)

**Review by dconnolly — APPROVED** [review]
it lorge

**Pull request merged**
