### PR TITLE
fix(mergify): restrict merges with unresolved threads

### PR DESCRIPTION
**Pull request by gustavovalverde**
## Motivation
We've had a few cases of Mergify merging reviewed PR's with unresolved comments.

## Solution
- Added `"#review-threads-unresolved=0"` to all `pull_request_rules` which will prevent merges with unresolved threads.

## Review
@dconnolly

### CODE REVIEW

**Review by teor2345 — APPROVED** [review]
Thanks!

**Review by dconnolly — APPROVED** [review]
Nice! I was looking for something like this in the Mergify docs and just did not have the grep-fu to find it 🙏🙏🙏

**Comment by teor2345** [comment]
@dconnolly we don't need to set GitHub auto-merge any more, because mergify will do the merge.

**Comment by dconnolly** [comment]
> @dconnolly we don't need to set GitHub auto-merge any more, because mergify will do the merge.

Not for changes to Mergify config, which makes sense:

**Comment by teor2345** [comment]
Ah right, I just read that:
> For security reason, Mergify will never automatically merge a pull request if it changes the Mergify configuration file.

https://docs.mergify.com/getting-started/#configuration

**Pull request merged**
