### PR TITLE
Disable Sprout anchor check

### PR DESCRIPTION
**Pull request by conradoplg**
## Motivation

There is some issue with a block after 1_200_000 that fails the Sprout anchor check. While we investigate it, disable the check so it doesn't block other development.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

**Comment by conradoplg** [comment]
Started a deployment from this branch https://github.com/ZcashFoundation/zebra/actions/runs/1578426412

**Review by teor2345 — APPROVED** [review]
Code looks good, but let's check how the Google Cloud instance is going before we merge.

**Comment by teor2345** [comment]
> Started a deployment from this branch https://github.com/ZcashFoundation/zebra/actions/runs/1578426412

This appears to have failed shortly after:
> 2021-12-15 02:56:36.250 DDUT
Dec 14 16:56:36.249 INFO {zebrad="ac8faeb" net="Main"}:sync:extend_tips:checkpoint: zebra_consensus::checkpoint: verified checkpoint range block_count=800 current_range=(Excluded(Height(235198)), Included(Height(235998))) 

This looks like the sync hang which is fixed by:
* https://github.com/ZcashFoundation/zebra/pull/3203
* https://github.com/ZcashFoundation/zebra/pull/3200

I'll start a local test to make sure this PR works.

**Comment by conradoplg** [comment]
> I'll start a local test to make sure this PR works.

Thanks! I was just going to ask about this, I was thinking it was a problem with GCloud

**Comment by teor2345** [comment]
FYI, the sprout error also happens on testnet at height `1_057_736` with anchor `3ad623811ffa4fe8498b23f3d6bb4e086dca32269afef6c8e572fd9ee6d0c0ea`:

> Dec 15 14:47:34.177  WARN {zebrad="35cd196" net="Test"}:sync: zebrad::components::sync: error downloading and verifying block e=Invalid(Block(Commit(CloneError { source: CommitBlockError(UnknownSproutAnchor { anchor: Root("3ad623811ffa4fe8498b23f3d6bb4e086dca32269afef6c8e572fd9ee6d0c0ea") }) })))
> Dec 15 14:47:34.177  INFO {zebrad="35cd196" net="Test"}:sync: zebrad::components::sync: waiting to restart sync timeout=61s
> Dec 15 14:48:13.351  INFO {zebrad="35cd196" net="Test"}:{peer=Out("157.245.113.22:18233")}:msg_as_req{msg=inv { invs: 1 }}:inbound:download_and_verify{hash=0059af4fb6240f989f8a12eac03bf999314db4a98d4c878d1c8b37accf9ec407}: zebra_state::service: pruned utxo requests old_len=2 new_len=0 prune_count=2 tip=Some((Height(1057736), block::Hash("00e37070e8dc05663b515f9c1f8060d5680afb9b149e1b2a80acc12b6d8113d6")))

And just to confirm, I'm seeing it on mainnet at height `1_047_907` with anchor `019c435cd1e8aca9a4165f7e126ac6e548952439d50213f4d15c546df9d49b61`:
> Dec 15 16:19:40.240  INFO {zebrad="35cd196" net="Main"}:sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(1047907) min_locator_height=1047808 locators=[Height(1047907), Height(1047906), Height(1047905), Height(1047903), Height(1047899), Height(1047891), Height(1047875), Height(1047843), Height(1047808)]
> Dec 15 16:19:40.240  INFO {zebrad="35cd196" net="Main"}:sync:obtain_tips: zebrad::components::sync: trying to obtain new chain tips tip=block::Hash("00000000018e490c4324c59b69be172f58d7eb9b8d27216be64cb95a696a45b4")
> Dec 15 16:19:45.661  INFO {zebrad="35cd196" net="Main"}:sync:obtain_tips:push_obtain_tips_length{sync_length=499}: zebrad::components::sync::recent_sync_lengths: sending recent sync lengths recent_lengths=[499, 499, 499, 499]
> Dec 15 16:19:51.347  WARN {zebrad="35cd196" net="Main"}:sync: zebrad::components::sync: error downloading and verifying block e=Invalid(Block(Commit(CloneError { source: CommitBlockError(UnknownSproutAnchor { anchor: Root("019c435cd1e8aca9a4165f7e126ac6e548952439d50213f4d15c546df9d49b61") }) })))

This is from a Zebra instance without the fix in this PR.

**Comment by teor2345** [comment]
My local test of this PR synced to tip on mainnet:
> Dec 16 06:05:15.704  INFO zebrad::components::sync::gossip: sending committed block broadcast height=Height(1495835) request=AdvertiseBlock(block::Hash("000000000090c9afe1dcd8e7936115e8e1d20bc6a7d780158e3d3d6c9729d3d1"))

**Pull request merged**
