### PR TITLE
build(deps): bump chrono from 0.4.19 to 0.4.20

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

`chrono` has fixed rust security advisory:
https://rustsec.org/advisories/RUSTSEC-2020-0159

It has also fixed some panic bugs.

## Solution

- Bump chrono to 0.4.20

Related build / security fixes:
- Drop old time crate dependency from chrono 

Related clippy fixes:
- Fix clippy::assign_op_pattern
- Update deprecated constant names

## Review

Zebra isn't actually vulnerable to this security issue in our direct use of `chrono`, but `tracing` might be, so we should get this merged before the next release.

### Reviewer Checklist

  - [ ] Existing tests pass

### CODE REVIEW

**Comment by teor2345** [comment]
We're seeing panics in Zebra, so this is now a high priority.

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
@mergifyio update

**Review by oxarbitrage — APPROVED** [review]

**Comment by oxarbitrage** [comment]
@mergifyio update

**Comment by teor2345** [comment]
@mergifyio update

**Pull request merged**
