### PR TITLE
Handle `Semaphore::acquire()` error

### PR DESCRIPTION
**Pull request by jvff**
## Motivation

This is part of the update to use Tokio version 1 (#2200), and must be merged together with the other PRs.

The newer version of Tokio changed the `Semaphore::acquire()` method to return an error if the semaphore has been closed. Usages of that method need to be updated to handle the error.

## Solution

In the two usages of semaphores in Zebra they are never closed, so the solution here was just to `expect` that calls to `acquire` will never fail.

## Review

Anyone from the team can review this, but it shouldn't be merged yet.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

**Comment by teor2345** [comment]
> In the two usages of semaphores in Zebra they are never closed, so the solution here was just to `expect` that calls to `acquire` will never fail.

Are semaphores closed on drop?
Does Zebra ever drop the semaphores?

**Comment by jvff** [comment]
> > In the two usages of semaphores in Zebra they are never closed, so the solution here was just to `expect` that calls to `acquire` will never fail.
> 
> Are semaphores closed on drop? Does Zebra ever drop the semaphores?

I believe they are closed on drop, but that shouldn't matter because when they are dropped they can't be used anymore. They are different from channels where you can close one endpoint and keep the other open. A semaphore's "endpoints" are just shared `Arc<Semaphore>` references to the same semaphore instance.

**Comment by teor2345** [comment]
> > > In the two usages of semaphores in Zebra they are never closed, so the solution here was just to `expect` that calls to `acquire` will never fail.
> > 
> > Are semaphores closed on drop? Does Zebra ever drop the semaphores?
> 
> I believe they are closed on drop, but that shouldn't matter because when they are dropped they can't be used anymore. They are different from channels where you can close one endpoint and keep the other open. A semaphore's "endpoints" are just shared `Arc<Semaphore>` references to the same semaphore instance.

Ok, I think that makes sense.

(For channels, we ignore errors rather than `expect()`ing, because we don't control the order that channel endpoints are dropped when Zebra shuts down.)

**Review by teor2345 — APPROVED** [review]
This seems fine, but we should run the tests on the rollup PR before merging.

**Comment by jvff** [comment]
Merged through #2994.

**Pull request closed without merging**
