### PR TITLE
release(docs): Update the release checklist pull request and issue templates

### LINKED ISSUE #8934: Fix links in the release-checklist template
https://github.com/ZcashFoundation/zebra/blob/main/.github/PULL_REQUEST_TEMPLATE/release-checklist.md

Almost all links are broken, for example explorer link does not work anymore, several github action links that were moved or deleted, etc.

Will be good to fix this before the next release.

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

Several links in the release template are broken.

Close https://github.com/ZcashFoundation/zebra/issues/8934

## Solution

- Fix the links where possible, remove one where i didn't found an alternative.
- Add a section about git sources dependencies.
- Add a missing book page to the zebra book summary.

### Tests

No tests.

### PR Author's Checklist

- [ ] The PR name will make sense to users.
- [ ] The PR provides a CHANGELOG summary.
- [ ] The solution is tested.
- [ ] The documentation is up to date.
- [ ] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR Author's checklist is complete.
- [ ] The PR resolves the issue.

### CODE REVIEW

**Review by mpguerra — APPROVED** [review]
Thank you for updating!

**Comment by mpguerra** [comment]
@mergify refresh

**Comment by gustavovalverde** [comment]
@mergify refresh

**Comment by mpguerra** [comment]
@mergify queue

**Pull request merged**
