### PR TITLE
feat(ci): run cached state rebuilds in main branch

### PR DESCRIPTION
**Pull request by gustavovalverde**
## Motivation

This is an intermediate PR to allow cached state rebuilds in the `main` branch when merge is successful, needed for https://github.com/ZcashFoundation/zebra/pull/4074

As this workflows run other tests that doesn't add much value, as those tests are validated in the PR checks, and while merging using Mergify, these should be improved in the near future with https://github.com/ZcashFoundation/zebra/issues/4106

This is also a replacement for https://github.com/ZcashFoundation/zebra/pull/4095

## Solution
- Run the Test and Full sync test workflows when pushing to `main`, to have up to date disks using the `main` reference in their name.
- Add GitHub's ref name (branch/PR) to the disk name

## Review

@teor2345 or @dconnolly can review this

## Follow Up Work
https://github.com/ZcashFoundation/zebra/issues/4106

### CODE REVIEW

**Review by teor2345 — COMMENTED** [review]
The changes in this PR look good.

This PR changes the tip sync and checkpoint sync workflows, but those checks weren't automatically triggered, because the state version didn't change.

Can you please run these workflows manually?

Can we open a ticket to run those jobs automatically when their workflows change?
(After we split them out in #4106.)

**Comment by gustavovalverde** [comment]
> Can you please run these workflows manually?

@teor2345 sadly, a GitHub limitation is that manual runs execute the workflow from the `main` branch not from the targeting branch, so it won't use the workflow from this branch, but just take the references from it.

We won't be able to see the changes applied until we actually merge it and then run it manually (from `main`).

**Comment by gustavovalverde** [comment]
> Can we open a ticket to run those jobs automatically when their workflows change?

@teor2345 I've already implemented this in my last 2 pushes

**Review by teor2345 — APPROVED** [review]
Thanks, that makes sense!

**Comment by gustavovalverde** [comment]
@teor2345 interesting, this is not getting queued 🤕 

Edit: I'm merging `main` to confirm

**Comment by gustavovalverde** [comment]
This one will take a while as the sync is being done from genesis, and I need it merge to generate the disks and then finalize  #4074 

I'll merge this manually

**Pull request merged**
