### PR TITLE
deps: Update redjubjub to 0.2

### LINKED ISSUE #606: Point at published redjubjub crate when it's available
Not the git url.

### PR DESCRIPTION
**Pull request by hdevalence**
Closes #606.

### CODE REVIEW

**Review by yaahc — DISMISSED** [review]
easy approval

**Review by dconnolly — CHANGES_REQUESTED** [review]
Ah we need to update the names of SecretKey/PublicKey to SigningKey/VerificationKey

https://github.com/ZcashFoundation/zebra/pull/616/files#file-zebra-chain-src-keys-sapling-rs-L389

**Review by dconnolly — CHANGES_REQUESTED** [review]
Same with

https://github.com/ZcashFoundation/zebra/pull/616/files#file-zebra-chain-src-transaction-shielded_data-rs-L23

**Comment by hdevalence** [comment]
Ah right, I knew there was something.... I'll fix this up.

**Comment by hdevalence** [comment]
running the compiler before sending the PR? that's what we call a "pro gamer move"

**Comment by hdevalence** [comment]
Should be fixed now, let's see how CI does.

**Review by dconnolly — APPROVED** [review]
🥳

**Pull request merged**
