### PR TITLE
Automatically disable colored output when writing to a file

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We want Zebra to write colored output when writing to a terminal, but automatically switch off colors when writing to a file, pipe, or non-terminal device.

We also want to disable abscissa colors ~and color_eyre~ when `config.tracing.use_color` is false.

## Solution

Pre-config:
* disable abscissa colors when stdout or stderr are not connected to a terminal

After config:
* disable tracing colors when stdout is not connected to a terminal, and when the config disables colors
* ~disable the color_eyre panic handler when stdout is not connected to a terminal, and when the config disables colors~

Already implemented:
* color_backtrace already disables colored backtraces when its not connected to a terminal

The code in this pull request has:
  - Comments
  - Manual testing for:
    - auto tracing color disable using `zebrad start | tee`
    - auto abscissa color disable using `zebrad | tee`
    - ~auto color_eyre disable by adding a `panic!()` after the config is loaded~

## Review

@hdevalence wrote the original PR #1408
@yaahc wrote `color_eyre`

## Follow Up Work

Eventually, we want to modify `color_eyre` so that it:
* automatically disables color when output is not to a terminal, and
* has a configuration that always turns colors off, because auto-detection isn't perfect, some users won't have color terminals, and others will want colors off for accessibility

Until that happens, there might be issues with grep and unterminated color sequences in Zebra's `color_eyre` output, but they hopefully won't be that common.

### CODE REVIEW

**Review by hdevalence — DISMISSED** [review]
LGTM, I'd prefer if we didn't add clippy annotations to every file and used our existing clippy.toml instead, but I don't think this PR should block on that.

Do we still want to have a config option, if we auto-detect? We could remove it going forward.

**Review by dconnolly — DISMISSED** [review]
Needs a rebase but ✅

**Comment by teor2345** [comment]
> LGTM, I'd prefer if we didn't add clippy annotations to every file and used our existing clippy.toml instead, but I don't think this PR should block on that.

We can follow up clippy in #1304.

> Do we still want to have a config option, if we auto-detect? We could remove it going forward.

The auto-detection isn't perfect, some users won't have colour terminals, and others will want colours off for accessibility. So it's important we have an "always off" option.

**Comment by teor2345** [comment]
@dconnolly I rebased

@yaahc I backed out the `color_eyre` changes, it would be great if we had the following changes upstream:
* automatically disable color when output is not to a terminal, and
* add a configuration that always turns colors off, because auto-detection isn't perfect, some users won't have color terminals, and others will want colors off for accessibility

**Comment by yaahc** [comment]
> @dconnolly I rebased
> 
> @yaahc I backed out the `color_eyre` changes, it would be great if we had the following changes upstream:
> 
>     * automatically disable color when output is not to a terminal, and
> 
>     * add a configuration that always turns colors off, because auto-detection isn't perfect, some users won't have color terminals, and others will want colors off for accessibility

I worked on this a bunch today, should be ready soon.

https://github.com/yaahc/color-eyre/pull/69

The gist is this lets us create themes and I'll be able to set a blank theme that just disables all colors and have that be configured based on the existing detection and configuration logic.

**Review by dconnolly — APPROVED** [review]

**Pull request merged**
