### PR TITLE
Shielded coinbase test blocks

### PR DESCRIPTION
**Pull request by teor2345**

### CODE REVIEW

**Comment by teor2345** [comment]
These subsidy validation in #1051 accepts these blocks.

**Review by oxarbitrage — DISMISSED** [review]

**Review by dconnolly — DISMISSED** [review]

**Comment by teor2345** [comment]
We're going to ~compress the big block on disk using flate2~ store the big block as binary - I'll make that change today.

**Comment by teor2345** [comment]
This change adds a second or two to the test times - 30s to 32s.

If we want to reduce test times, we should make changes to the existing code.

**Comment by yaahc** [comment]
@teor2345 We're still planning on switching this to be binary blobs instead of hex, right?

**Comment by teor2345** [comment]
> > We're going to ... store the big block as binary - I'll make that change today.
>
> @teor2345 We're still planning on switching this to be binary blobs instead of hex, right?

The large block is in binary:
https://github.com/ZcashFoundation/zebra/pull/1116/files#diff-78c1e13e04bfca0bc3fafe9d5ba42e87

There doesn't seem to be much point in switching the existing, smaller blocks into binary, because then we download both the hex and binary data when cloning Zebra. (So it increases the cost to 3x the actual size of the block, rather than 2x for just hex.)

But there's some small benefits to making all the new blocks binary:
* they only take up the 1x the size of the block, rather than 2x for hex (but that's only about a hundred kilobytes)
* more existing blocks in binary makes it more likely that future PRs will add blocks in binary

So I can make that change in this PR, and force-push.

**Review by dconnolly — APPROVED** [review]
📦🔗📦🔗📦

**Pull request merged**
