### PR TITLE
fix(ci): Update Zebra checkpoints

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Full syncs are currently timing out on the `main` branch.

## Solution

- Update the mainnet and testnet checkpoints

## Review

This is urgent because CI is failing.
Anyone can review this PR.

### Reviewer Checklist

  - [ ] CI passes

### CODE REVIEW

**Review by gustavovalverde — APPROVED** [review]
LGTM

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
> ERROR: (gcloud.compute.ssh) There was a problem refreshing your current auth tokens: ('Unable to retrieve Identity Pool subject token', '{ "message": "GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.", "ref": "Ref A: 82FECBD1DCFB4F28AB347FE5031D71AD Ref B: SN1EDGE2208 Ref C: 2022-09-12T23:14:48Z" }')

https://github.com/ZcashFoundation/zebra/actions/runs/3041153429/jobs/4898098416#step:6:81

**Comment by teor2345** [comment]
@mergifyio update

**Pull request merged**
