### PR TITLE
chore(sync): Update Zebra mainnet and testnet checkpoints - 13 July 2022

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Updating the checkpoints speeds up Zebra's syncing.

## Solution

- Update Zebra mainnet and testnet checkpoints on 13 July 2022

## Review

This is urgent because we want it in the next release.

### Reviewer Checklist

  - [ ] CI might not pass, because syncing needs other fixes

## Follow Up Work

- #4776 is also needed to make syncing work

### CODE REVIEW

**Review by oxarbitrage — APPROVED** [review]
Thanks @teor2345

**Comment by oxarbitrage** [comment]
>  #4776 is also needed to make syncing work

Not really from here, i synchronized the mainnet with the main branch locally. It was a slow process at the end (toke around 14 hours) but never hanged or crashed. I think the checkpoint update will help to make sync faster given the current block sizes we are seeing in the network.

Anyways, everything seems to point to a problem in the batches so i think your PR will maybe fix the underlying problem. I will take a look into it now.

**Comment by teor2345** [comment]
> > #4776 is also needed to make syncing work
> 
> Not really from here, i synchronized the mainnet with the main branch locally. It was a slow process at the end (toke around 14 hours) but never hanged or crashed. I think the checkpoint update will help to make sync faster given the current block sizes we are seeing in the network.
> 
> Anyways, everything seems to point to a problem in the batches so i think your PR will maybe fix the underlying problem. I will take a look into it now.

There's a sync problem that only seems to happen on some machines or networks, so it's tricky to reproduce and fix.
We see it in CI more than in other places.

**Comment by teor2345** [comment]
This passed the CI we expect it to pass, so I admin-merged it.

**Pull request merged**
