### PR TITLE
fix(test/lightwalletd): add an alternative log to the final integration test check

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Sometimes lightwalletd goes straight to logging "Another refresh in progress", without logging "Mempool refresh error" first.

## Review

This is a high-priority fix, but the test sometimes succeeds.

### Reviewer Checklist

  - [ ] Integration test passes

### CODE REVIEW

**Comment by teor2345** [comment]
The Windows tracing conflict test might have failed due to PR #3755.

**Comment by gustavovalverde** [comment]
This has been timing out on a few PRs, i thought it was just happening on the Docker build, but in this PR it happened in all the tests (except macOS) `test tracing_endpoint has been running for over 60 seconds`. There's something odd with **tracing_endpoint**

This makes most test to hang indefinitely cc: @conradoplg  

**EDIT:** Nevermind, I thought https://github.com/ZcashFoundation/zebra/pull/3755 was merged

**Comment by teor2345** [comment]
@mergifyio update

**Review by oxarbitrage — APPROVED** [review]

**Comment by teor2345** [comment]
> Quota 'PD_EXTREME_TOTAL_PROVISIONED_IOPS' exceeded.  Limit: 720000.0 in region us-central1.

**Pull request merged**
