### PR TITLE
Revert #500 (generic errors in tower-batch).

### PR DESCRIPTION
**Pull request by hdevalence**
Unfortunately, since the Batch wrapper was changed to have a generic error
type, when wrapping it in another Service, nothing constrains the error type,
so we have to specify it explicitly to avoid an inference hole.  This is pretty
unergonomic -- from the compiler error message it's very unintuitive that the
right fix is to change `Batch::new` to `Batch::<_, _, SomeError>::new`.

The options are:

1. roll back the changes that make the error type generic, so that the error
   type is a concrete type;

2. keep the error type generic but hardcode the error in the default
   constructor and add an additional code path that allows overriding the
   error.

However, there's a further issue with generic errors: the error type must be
Clone.  This problem comes from the fact that there can be multiple Batch
handles that have to share access to errors generated by the inner Batch
worker, so there's not a way to work around this.  However, almost all error
types aren't Clone, so there are fairly few error types that we would be
swapping in.

This suggests that in case (2) we would be maintaining extra code to allow
generic errors, but with restrictive enough generic bounds to make it
impractical to use generic error types.  For this reason I think that (1) is a
better option.

### CODE REVIEW

**Comment by hdevalence** [comment]
The commit message summarizes this discussion: https://github.com/ZcashFoundation/zebra/pull/665#discussion_r455334816

**Comment by hdevalence** [comment]
I'm not sure why clippy is failing here: https://github.com/ZcashFoundation/zebra/pull/668/checks?check_run_id=895396487

It's complaining about an unused `Result` coming off of the module docs for the crate root.  This seems pretty strange to me.

**Comment by yaahc** [comment]
@hdevalence its likely a corrupted span from a function with multiple proc macro attributes, such as `#[tokio::test]` and `#[spandoc]`. When they're combined on the same fn errors from that fn tend to lose all information about where they came from, which is why I've been breaking test functions into an outer and inner fn where each attribute is only applied to one of them.

**Comment by hdevalence** [comment]
@yaahc Hmm, okay, how can this be fixed or avoided? I'm confused because I don't see any span attributes anywhere in `lib.rs`, so this feels like there are some spooky nonlocal effects.

**Comment by yaahc** [comment]
I'm not sure theres a general purpose way to fix it, but I fixed it for this issue.

**Comment by yaahc** [comment]
Long term, I might be able to look at what function attributes are being applied to the current fn with `spandoc` and produce a warning if theres another proc macro working on the same function, or we could try to figure out the exact cause of the bug either in `rustc` or in `tokio`.

**Review by dconnolly — APPROVED** [review]
ignoring the clippy weirdness coming from zebra-consensus

**Pull request merged**
