### PR TITLE
Add testnet blocks to zebra_state

### PR DESCRIPTION
**Pull request by oxarbitrage**
This is a small part of https://github.com/ZcashFoundation/zebra/issues/683 where testnet genesis block and the first 10 blocks are added as test vectors.

Utilities where added for tests to know in what mode(Testnet, Mainnet) they are currently running. Mode is a mutex that can be updated by any test.

As we want the tests in `zebra_consensus` to use `zebra_test::Transcript`(https://github.com/ZcashFoundation/zebra/issues/744, https://github.com/ZcashFoundation/zebra/issues/610) i decided to get started with the `zebra_state` where this is already in place.

I am unsure if the approach is the most clear, was done trying to avoid duplicated code.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
This will be easier if https://github.com/ZcashFoundation/zebra/pull/773 is merged and this PR rebased into that.

**Comment by daira** [comment]
> Mode is a mutex that can be updated by any test.

Nooooooooo... Global mutable state in tests considered harmful.

**Comment by oxarbitrage** [comment]
Thank you for the head up @daira , for sure is something we will not want to do.

I just force pushed to be more clear on what i am trying to achieve, this is not a definitive version but can take a look if you want.
Basically what i need is to pass some argument to the transcript static however it is hacky just to say that. Looking for options without duplicating the transcripts for the 2 modes.

**Comment by teor2345** [comment]
> Basically what i need is to pass some argument to the transcript static however it is hacky just to say that. Looking for options without duplicating the transcripts for the 2 modes.

It looks like you'll need to write transcripts with `Request=(Network, BlockHeight)`.

Then in the tests, you can call a new async `get_block` function which takes a `Network` and `BlockHeight`, and returns the `zebra-test::vectors` block for that height.

Once that's working, you might be able to make it more ergonomic by using `get_block` inside the transcript implementation.

Then you should be able to call the tests like this example:
```rust
    #[tokio::test]
    async fn test_transcript_mainnet() {
        test_transcript(Mainnet).await;
    }

    #[tokio::test]
    async fn test_transcript_testnet() {
        test_transcript(Testnet).await;
    }

    /// Check the transcript for `network`.
    async fn test_transcript(network: Network) {
        zebra_test::init();
        let transcript = get_transcript(network).await;
        // test transcript
    }
```

**Review by hdevalence — DISMISSED** [review]
Rather than using a mutex to switch test modes, I think it would be a lot clearer to just have additional transcripts -- the existing test code is set up so that each transcript tests one thing, and new things can be added by adding more transcripts.

**Review by yaahc — DISMISSED** [review]
I'm assuming this is good to go pending @hdevalence final review of the changes since his last review.

**Review by yaahc — APPROVED** [review]

**Pull request merged**
