### PR TITLE
fix(ci): Disable beta Rust tests

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Beta Rust builds are failing with:
> warning: libgit2/src/util/tsort.c:382:1: fatal error: error writing to /tmp/ccFhppqU.s: No space left on device

https://github.com/ZcashFoundation/zebra/runs/8195908267?check_suite_focus=true#step:13:493

## Changes

Reverts ZcashFoundation/zebra#5024.

We don't need to disable any branch protection rules, because they weren't re-enabled when we did ticket #4929.

### CODE REVIEW

**Comment by gustavovalverde** [comment]
I'm not completely sure if this is the best course of action, considering that this was recently running fine just after the merge https://github.com/ZcashFoundation/zebra/runs/8161898028?check_suite_focus=true 

As its **beta** rust, this is meant to be "unstable" (?), it might break from time to time and then get fixed. And I feel it might be noisy if we're continuously removing it and then adding it once again, as it requires creating tickets, PR, etc.

Just thinking on a long term strategy when we have this kind of scenarios.

cc: @dconnolly

**Comment by teor2345** [comment]
> I'm not completely sure if this is the best course of action, considering that this was recently running fine just after the merge https://github.com/ZcashFoundation/zebra/runs/8161898028?check_suite_focus=true

We're seeing the disks fill up on both beta and stable Rust. But it seems to happen much more often on beta.

This might be caused by new dependency updates, a cumulative bug across multiple Rust builds, or a bug in the Rust cache action.

There haven't been any changes to beta Rust since we re-enabled it, except maybe the "mir inlining" change:
https://github.com/rust-lang/rust/commits/beta

> As its **beta** rust, this is meant to be "unstable" (?), it might break from time to time and then get fixed.

**beta** rust is meant to be used for testing in CI, so new rust bugs are fixed before they reach **stable** rust.

You might be thinking of **nightly** rust, which is built from the `master` branch.

**beta** rust becomes the next **stable** release every 6 weeks, with only a few backports added to the **nightly** from 12 weeks ago:
https://doc.rust-lang.org/stable/book/appendix-07-nightly-rust.html#choo-choo-release-channels-and-riding-the-trains

> And I feel it might be noisy if we're continuously removing it and then adding it once again, as it requires creating tickets, PR, etc.

I think we might have made a mistake by re-enabling beta Rust before confirming that all the bugs were fixed.

We should be doing these steps every time a beta build fails:
1. Report the bug to https://github.com/rust-lang/rust
2. Wait until the bug is fixed
3. Re-enable beta Rust
4. Require beta Rust to merge PRs to `main`

https://stackoverflow.com/a/70746297

**Comment by teor2345** [comment]
Whatever we decide to do long-term, I would like to get CI passing and showing green ticks again by merging this PR.

Then we can spend some time diagnosing the bug. Or we can just hope it won't happen when the current beta is released as the new Rust stable in 14 days time.

**Comment by teor2345** [comment]
I tried deleting the beta Rust caches using the following GitHub CLI commands:
```sh
gh api -H "Accept: application/vnd.github+json" /repos/ZcashFoundation/Zebra/actions/caches
gh api --method DELETE -H "Accept: application/vnd.github+json" /repos/ZcashFoundation/Zebra/actions/caches/<id>
```

I'm re-running the beta Rust tests on `main` to see if that worked:
https://github.com/ZcashFoundation/zebra/actions/runs/3004090401

If it works, we should also clear the stable Rust caches, because they have had similar issues.

**Comment by teor2345** [comment]
> I tried deleting the beta Rust caches using the following GitHub CLI commands:
> 
> ```shell
> gh api -H "Accept: application/vnd.github+json" /repos/ZcashFoundation/Zebra/actions/caches
> gh api --method DELETE -H "Accept: application/vnd.github+json" /repos/ZcashFoundation/Zebra/actions/caches/<id>
> ```
> 
> I'm re-running the beta Rust tests on `main` to see if that worked: https://github.com/ZcashFoundation/zebra/actions/runs/3004090401
> 
> If it works, we should also clear the stable Rust caches, because they have had similar issues.

This seems to have worked, I'll clear all the caches now.

**Comment by gustavovalverde** [comment]
Latest build ran as expected https://github.com/ZcashFoundation/zebra/runs/8242419327?check_suite_focus=true

It might be nice to put these commands somewhere for future reference:
```shell
gh api -H "Accept: application/vnd.github+json" /repos/ZcashFoundation/Zebra/actions/caches
gh api --method DELETE -H "Accept: application/vnd.github+json" /repos/ZcashFoundation/Zebra/actions/caches/<id>
```

**Comment by teor2345** [comment]
> Latest build ran as expected https://github.com/ZcashFoundation/zebra/runs/8242419327?check_suite_focus=true
> 
> It might be nice to put these commands somewhere for future reference:
> 
> ```shell
> gh api -H "Accept: application/vnd.github+json" /repos/ZcashFoundation/Zebra/actions/caches
> gh api --method DELETE -H "Accept: application/vnd.github+json" /repos/ZcashFoundation/Zebra/actions/caches/<id>
> ```

I put them in https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/continuous-integration.md#resolving-disk-full-errors in PR #5105!

**Comment by teor2345** [comment]
This seems to work for now.

**Comment by teor2345** [comment]
Beta Rust has hung on multiple PRs, so we need to disable it for now, then fix it later:
- https://github.com/ZcashFoundation/zebra/actions/runs/3033501032/jobs/4881766237
- https://github.com/ZcashFoundation/zebra/actions/runs/3033472430/jobs/4881718365

**Comment by teor2345** [comment]
@mergifyio update

**Review by gustavovalverde — APPROVED** [review]

**Pull request merged**
