### PR TITLE
fix(ci): Use correct check for external repositories

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

There's a mistake in PR #7956 where it is skipping important jobs on all PRs in CI, rather than just external PRs.

#### Check before marking the PR as ready for review:
  - [x] Will the PR name make sense to users?
  - [x] Does the PR have a priority label?
  - [x] Have you added or updated tests?
  - [x] Is the documentation up to date?

_If a checkbox isn't relevant to the PR, mark it as done._

### Specifications

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

You can see the full `github.event` object for an external PR here:
https://github.com/ZcashFoundation/zebra/actions/runs/6997671169/job/19034900585?pr=7999#step:2:995

## Solution

Use the `fork` field rather than trying to guess from the PR branch name

### Testing

I manually checked this worked:
- real workflow runs: https://github.com/ZcashFoundation/zebra/actions/runs/6997949380/job/19035477953?pr=8000
- patch-external skipped: https://github.com/ZcashFoundation/zebra/actions/runs/6997949377/job/19035476464?pr=8000

Since the logic is inverted for an external PR, that should also work.

## Review

This is urgent because some PRs and Mergify are skipping some CI jobs.

### Reviewer Checklist

Check before approving the PR:
  - [ ] Does the PR scope match the ticket?
  - [ ] Are there enough tests to make sure it works? Do the tests cover the PR motivation?
  - [ ] Are all the PR blockers dealt with?
        PR blockers can be dealt with in new tickets or PRs.

_And check the PR Author checklist is complete._

### CODE REVIEW

**Comment by teor2345** [comment]
The lint error is a known issue that shouldn't block merging this PR:
> Error: no schema with key or ref "http://json-schema.org/draft-07/schema#"

https://github.com/ZcashFoundation/zebra/actions/runs/6997949358/job/19035511113?pr=8000#step:5:13

**Comment by teor2345** [comment]
Failed due to #7898

**Review by arya2 — APPROVED** [review]
Looks good, thank you!

**Comment by arya2** [comment]
Not sure what happened here, the schema at that URL seems to be there.

> Run marocchino/validate-dependabot@v2.1.0
Error: no schema with key or ref "http://json-schema.org/draft-07/schema#"

https://github.com/ZcashFoundation/zebra/actions/runs/7008453149/job/19064814803#step:5:13

**Comment by teor2345** [comment]
> Not sure what happened here, the schema at that URL seems to be there.
> 
> > Run marocchino/validate-dependabot@v2.1.0
> > Error: no schema with key or ref "http://json-schema.org/draft-07/schema#"
> 
> [ZcashFoundation/zebra/actions/runs/7008453149/job/19064814803#step:5:13](https://github.com/ZcashFoundation/zebra/actions/runs/7008453149/job/19064814803#step:5:13)

It seems to be a rate-limit caused by how that action is implemented internally.

**Pull request merged**
