### PR TITLE
fix(ci): Ignore lightwalletd hangs for now

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Sometimes `lightwalletd` hangs when it gets near the tip.

We can't really fix that, so we just check that it has synced some blocks instead.

Depends-On: #4669, #4675

## Solution

- Allow "adding block to cache" as an alternative tip log, where we previously required "waiting for block"

## Review

This is pretty urgent, it's blocking some lightwalletd tests.

### Reviewer Checklist

  - [ ] CI passes

## Follow Up Tasks

- #4600 
- #4537

### CODE REVIEW

**Comment by gustavovalverde** [comment]
Was reviewing to approve, but test is still failing even though it shows a matching regex
```
{"app":"lightwalletd","level":"info","msg":"Adding block to cache 1020427 000000000049429cfbc02c7d798e23e5db748310eda499977569a5484116ab46","time":"2022-06-21T07:25:34Z"}
```

But the actual regex is expecting a different output:
```
Match Regex:
   [
       "finished initial sync to chain tip, using gossiped blocks .*sync_percent.*=.*100\\.",
   ]
```

FMT is also complaining

Maybe @conradoplg can have a look at this one.

**Comment by conradoplg** [comment]
@Mergifyio update

**Comment by conradoplg** [comment]
> Maybe @conradoplg can have a look at this one.

That's the Zebra sync failure which was hopefully solved by #4662 . I've updated this PR to pick up the fix.

**Comment by teor2345** [comment]
The sync failure in this PR should get better after #4669, and whatever fixes we need to fix the sync speed.

**Comment by gustavovalverde** [comment]
I'm re-testing https://github.com/ZcashFoundation/zebra/pull/4669. Let's wait for the result, merge it to `main` and then update this PR to confirm all checks pass

**Comment by teor2345** [comment]
This is blocking a bunch of work, so I made it "Critical" priority.

**Comment by teor2345** [comment]
> I'm re-testing #4669. Let's wait for the result, merge it to `main` and then update this PR to confirm all checks pass

#4669 passed, I manually rebased on that branch and the latest `main`.

So the diff will contain PR #4669 as well, but the CI results will be correct.

**Comment by teor2345** [comment]
This is still failing, it might need:
- all of #4661 
    - PR #4675, and
    - splitting checkpoint sync and full sync into separate jobs based on log output
- PR #4679
- a successful full sync on `main`

**Comment by upbqdn** [comment]
@Mergifyio update

**Review by upbqdn — APPROVED** [review]

**Pull request merged**
