### PR TITLE
chore(deps): Missed dependency updates

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

Part of #7991.

This change was created by running `cargo update`, `cargo deny --all-features check bans`, then adding the new deny.toml exceptions.

#### Check before marking the PR as ready for review:
  - [x] Will the PR name make sense to users?
  - [x] Does the PR have a priority label?
  - [x] Have you added or updated tests?
  - [x] Is the documentation up to date?

##### For significant changes:
  - [ ] Is there a summary in the CHANGELOG?
  - [ ] Can these changes be split into multiple PRs?

_If a checkbox isn't relevant to the PR, mark it as done._

## Solution

- `cargo update`
- `cargo deny --all-features check bans` 
- Added new `deny.toml` exception

## Review

This PR is for the release and should be reviewed first.

### Reviewer Checklist

Check before approving the PR:
  - [ ] Does the PR scope match the ticket?
  - [ ] Are there enough tests to make sure it works? Do the tests cover the PR motivation?
  - [ ] Are all the PR blockers dealt with?
        PR blockers can be dealt with in new tickets or PRs.

_And check the PR Author checklist is complete._

### CODE REVIEW

**Comment by arya2** [comment]
`cargo update` output:

<details>

```console
$ cargo update
    Updating crates.io index
    Updating anstream v0.6.4 -> v0.6.5
    Updating anstyle-parse v0.2.2 -> v0.2.3
    Updating anstyle-query v1.0.0 -> v1.0.2
    Updating anstyle-wincon v3.0.1 -> v3.0.2
    Updating async-compression v0.4.4 -> v0.4.5
    Updating bindgen v0.68.1 -> v0.69.1
    Updating bstr v1.7.0 -> v1.8.0
    Updating clap v4.4.10 -> v4.4.11
    Updating clap_builder v4.4.9 -> v4.4.11
    Updating color-spantrace v0.2.0 -> v0.2.1
    Updating core-foundation v0.9.3 -> v0.9.4
    Updating core-foundation-sys v0.8.4 -> v0.8.6
    Updating deranged v0.3.9 -> v0.3.10
    Updating dyn-clone v1.0.14 -> v1.0.16
    Updating errno v0.3.5 -> v0.3.8
    Updating eyre v0.6.8 -> v0.6.10
    Updating fiat-crypto v0.2.2 -> v0.2.5
    Updating form_urlencoded v1.2.0 -> v1.2.1
    Updating fs-err v2.9.0 -> v2.11.0
    Updating getrandom v0.2.10 -> v0.2.11
    Updating gimli v0.28.0 -> v0.28.1
    Updating globset v0.4.13 -> v0.4.14
    Updating h2 v0.3.21 -> v0.3.22
    Updating hashbrown v0.14.2 -> v0.14.3
    Updating hdrhistogram v7.5.2 -> v7.5.4
    Updating http v0.2.9 -> v0.2.11
    Updating http-body v0.4.5 -> v0.4.6
    Updating idna v0.4.0 -> v0.5.0
    Updating itoa v1.0.9 -> v1.0.10
    Updating js-sys v0.3.64 -> v0.3.66
    Updating known-folders v1.0.1 -> v1.1.0
    Updating libc v0.2.149 -> v0.2.151
      Adding libredox v0.0.1
    Updating linux-raw-sys v0.4.10 -> v0.4.12
    Updating mio v0.8.9 -> v0.8.10
    Updating once_cell v1.18.0 -> v1.19.0
    Updating parity-scale-codec v3.6.5 -> v3.6.9
    Updating parity-scale-codec-derive v3.6.5 -> v3.6.9
    Updating percent-encoding v2.3.0 -> v2.3.1
    Updating platforms v3.1.2 -> v3.2.0
    Updating portable-atomic v1.5.1 -> v1.6.0
    Updating proc-macro-crate v1.3.1 -> v2.0.0
    Updating proc-macro2 v1.0.69 -> v1.0.70
    Updating prost-build v0.12.1 -> v0.12.3
    Updating prost-types v0.12.1 -> v0.12.3
    Updating redox_users v0.4.3 -> v0.4.4
    Updating ring v0.17.5 -> v0.17.7
    Updating rustix v0.38.21 -> v0.38.28
    Updating rustls v0.21.8 -> v0.21.10
    Updating rustls-pemfile v1.0.3 -> v1.0.4
    Updating ryu v1.0.15 -> v1.0.16
    Updating signature v2.1.0 -> v2.2.0
    Updating smallvec v1.11.1 -> v1.11.2
    Updating spki v0.7.2 -> v0.7.3
    Updating syn v2.0.38 -> v2.0.40
    Updating termcolor v1.3.0 -> v1.4.0
    Updating tokio v1.34.0 -> v1.35.0
    Updating toml_edit v0.19.15 -> v0.20.7
    Updating try-lock v0.2.4 -> v0.2.5
    Updating unicode-bidi v0.3.13 -> v0.3.14
    Updating ureq v2.8.0 -> v2.9.1
    Updating url v2.4.1 -> v2.5.0
    Updating uuid v1.5.0 -> v1.6.1
    Updating wasm-bindgen v0.2.87 -> v0.2.89
    Updating wasm-bindgen-backend v0.2.87 -> v0.2.89
    Updating wasm-bindgen-futures v0.4.37 -> v0.4.39
    Updating wasm-bindgen-macro v0.2.87 -> v0.2.89
    Updating wasm-bindgen-macro-support v0.2.87 -> v0.2.89
    Updating wasm-bindgen-shared v0.2.87 -> v0.2.89
    Updating web-sys v0.3.64 -> v0.3.66
    Updating webpki-roots v0.25.2 -> v0.25.3
      Adding windows-sys v0.52.0
      Adding windows-targets v0.52.0
      Adding windows_aarch64_gnullvm v0.52.0
      Adding windows_aarch64_msvc v0.52.0
      Adding windows_i686_gnu v0.52.0
      Adding windows_i686_msvc v0.52.0
      Adding windows_x86_64_gnu v0.52.0
      Adding windows_x86_64_gnullvm v0.52.0
      Adding windows_x86_64_msvc v0.52.0
    Updating winnow v0.5.18 -> v0.5.27
    Updating zerocopy v0.7.21 -> v0.7.30
    Updating zerocopy-derive v0.7.21 -> v0.7.30
    Updating zeroize v1.6.0 -> v1.7.0
```
</details>

**Comment by arya2** [comment]
codespell job failed:

>      6 |         rm -rf /var/lib/apt/lists/*
>      7 |     
>      8 | >>> RUN pip install codespell
>      9 |     
>     10 |     COPY entrypoint.sh /entrypoint.sh
> 
> https://github.com/ZcashFoundation/zebra/actions/runs/7171993996/job/19528198876?pr=8086#step:2:205

**Comment by teor2345** [comment]
Here are the significant changes (minor, major, new dependencies):  
```
    Updating bstr v1.7.0 -> v1.8.0
    Updating fs-err v2.9.0 -> v2.11.0
    Updating idna v0.4.0 -> v0.5.0
    Updating known-folders v1.0.1 -> v1.1.0
    Updating once_cell v1.18.0 -> v1.19.0
    Updating platforms v3.1.2 -> v3.2.0
    Updating portable-atomic v1.5.1 -> v1.6.0
    Updating proc-macro-crate v1.3.1 -> v2.0.0
    Updating signature v2.1.0 -> v2.2.0
    Updating termcolor v1.3.0 -> v1.4.0
    Updating tokio v1.34.0 -> v1.35.0
    Updating toml_edit v0.19.15 -> v0.20.7
    Updating ureq v2.8.0 -> v2.9.1
    Updating url v2.4.1 -> v2.5.0
    Updating uuid v1.5.0 -> v1.6.1
      Adding windows-sys v0.52.0
      Adding windows-targets v0.52.0
      Adding windows_aarch64_gnullvm v0.52.0
      Adding windows_aarch64_msvc v0.52.0
      Adding windows_i686_gnu v0.52.0
      Adding windows_i686_msvc v0.52.0
      Adding windows_x86_64_gnu v0.52.0
      Adding windows_x86_64_gnullvm v0.52.0
      Adding windows_x86_64_msvc v0.52.0
    Updating zeroize v1.6.0 -> v1.7.0
```

Are any of them concerning?

**Comment by arya2** [comment]
> Are any of them concerning?

~No, I don't think we're worried about any of them~,  We're not concerned with the new uuid dependencies, Zebra doesn't currently compile for Windows anyway.

I'll take a look at tokio and zeroize.

**Review by teor2345 — APPROVED** [review]

**Pull request merged**
