### PR TITLE
fix(build): Fix new nightly clippy lints and cargo feature resolution

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

This PR fixes a cargo resolver version warning, and a bunch of new nightly clippy lints.

The new cargo resolver detects:
- a missing `tokio` feature in `zebra-state` and `zebra-network`, and
- missing dev dependencies in `zebra-node-services`.

This PR fixes those as well.

## Review

This is a low priority cleanup.

This PR currently contains a copy of PR #6813, that will disappear from the diff once it merges.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by teor2345** [comment]
@mergifyio update

**Review by oxarbitrage — APPROVED** [review]

**Review by oxarbitrage — DISMISSED** [review]

**Comment by teor2345** [comment]
This PR failed when merged with PR #6813 due to a missing feature in that PR.

I put the whole of PR #6813 in this PR (it's about to merge to `main` anyway), then added the missing feature.

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by teor2345** [comment]
@mergifyio update

**Review by arya2 — APPROVED** [review]

**Pull request merged**
