### PR TITLE
Stop the sync service downloading duplicate blocks

### PR DESCRIPTION
**Pull request by teor2345**
Avoid downloading duplicate blocks with the sync service.

Also
* use the current state tip in the block locator
* add diagnostic info to the duplicate block verify warnings.

TODO:

- [ ] Split this PR into obvious bugs, "changes I think are useful", and "things I tried and need help with"

Diagnosis:
- [x] why does the sync service send duplicate block requests?
  - keep a list of pending hashes and use them to filter new requests
- [x] why are we downloading blocks at the start of the chain?
  - the locator goes back to genesis
  - some peers are sending us low-height, off-chain blocks
- [x] why does the sync service hang after removing duplicates?
  - the service was relying on duplicates to compensate for failed block downloads
  - the retry limit was too low
  - the backpressure and checkpoint verifier were deadlocked
  - (the block verifier works fine)

ObtainTips:
- [x] should we add the tip (rather than just `tip - 1`) to the block locator?
  - adding the tip makes sure we don't re-download the tip
- [x] should the block locator be limited to the reorg interval?
  - yes, we should only ask for blocks that we'd accept
- [x] fix first_unknown when all hashes are known
  -  we were downloading all the known hashes, rather than skipping them

Verifiers:
- [x] info (or debug) on duplicate blocks

Refactor:
- [ ] abstract the pending hashes and futures into a struct
  - make sure each added future has a pending hash, and each removed future removes its pending hash
- [ ] abstract the failed hashes into a struct?

### CODE REVIEW

**Comment by hdevalence** [comment]
@teor2345 do we know why the syncer gets stuck and starts downloading blocks incorrectly?

**Comment by hdevalence** [comment]
Before we make changes to the sync logic, I think it would be good to have an analysis of why it currently gets confused and breaks down sometimes.

**Comment by teor2345** [comment]
> @teor2345 do we know why the syncer gets stuck and starts downloading blocks incorrectly?

I've discovered these issues:

Duplicate requests:
* the block locator goes back to genesis, but we'll only use blocks within the reorg interval
* the block locator starts at tip-1, leading to duplicate tip downloads
* the sync service doesn't track hashes that it has submitted to the download queue, so it can request the same block twice

Failed retries:
* when a block fails to download, sometimes the retry doesn't work (it looks like we were relying on duplicate downloads to make progress)
* I wonder if backpressure stops us downloading missing blocks

Bad peers:
* on mainnet, when we send ExtendTips, a few peers send us low-difficulty hashes, which aren't on the mainnet or testnet chains
* for some reason, we get low-height blocks in response to download requests
  * I don't know if these blocks match the low-difficulty hashes
* it looks like we download these low-height blocks faster than the best chain

I haven't looked at the missing blocks and bad peers in detail, I can do more analysis tomorrow.

But this issue is pretty complex, so it might help to make incremental progress. In particular, I think tweaking the block locator is pretty safe, and independent of the other changes.

**Comment by teor2345** [comment]
> Before we make changes to the sync logic, I think it would be good to have an analysis of why it currently gets confused and breaks down sometimes.

The details of what I was actually able to fix are in each commit message in this PR. (I also did some analysis above, in the description and the comments. It's a decent summary, but the commit messages have the full details.)

This PR includes a temporary fix for a block download failure deadlock, the details of that issue are in PR #835, along with my attempt at a fix.

**Comment by yaahc** [comment]
> abstract the pending hashes and futures into a struct 

F. I think I implemented this early in the syncer write, I hand wrote a future that would wrap the block download feature and the hash that is associated with that block download future. Let me do some spelunking to see if theres any old commits reachable still that have this code in it.

edit: can't find it :/

**Comment by teor2345** [comment]
Obsoleted by #851, #852, #853, and #854.

**Pull request closed without merging**
