### PR TITLE
Restore and update mempool tests

### LINKED ISSUE #2959: Update mempool tests after ZIP-401 changes
## Motivation

We removed a lot of tests in the PRs for:
- #2889
- #2932 
- #2958

See https://github.com/ZcashFoundation/zebra/commit/d00bd14c9d9a3273c8fb3ad9b2a8a6b513cc8269 (or https://github.com/ZcashFoundation/zebra/commit/0381c2347b17a00edff3e13788d14170e410a37e if that's gone) to see which tests were removed.

We should update those tests for the full ZIP-401 mempool implementation.

If the tests were obsoleted by the ZIP-401 changes, we should leave them deleted.

### PR DESCRIPTION
**Pull request by conradoplg**
## Motivation

See https://github.com/ZcashFoundation/zebra/issues/2959

## Solution

Restore and update the tests. In most cases, instead of working with a transaction count, a cost limit was derived by summing the costs of some of the transactions that will be inserted.

Closes https://github.com/ZcashFoundation/zebra/issues/2959

## Review

I just focused on restoring the tests and still want to think a bit more about if these tests still test everything that we want or if something is missing. But since we want to get this done soon I'm opening the PR as is. Feel free to suggest additions, otherwise I can also amend the tests in a later PR.

Anyone can review, but @teor2345 and/or @dconnolly might be particularly interested.

This seems to be one of the last pending issues for the beta so it's best to review it soon.

### Reviewer Checklist

  - [ ] All deleted tests were restored
  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

**Review by teor2345 — APPROVED** [review]
Looks good to me, thanks for making this happen!

**Review by teor2345 — DISMISSED** [review]
It looks like one of the tests sometimes fails:
```
---- components::mempool::storage::tests::vectors::mempool_storage_basic stdout ----

The application panicked (crashed).
Message:  assertion failed: !some_rejected_transactions.is_empty()
Location: zebrad/src/components/mempool/storage/tests/vectors.rs:104
```
https://github.com/ZcashFoundation/zebra/runs/4029234056?check_suite_focus=true#step:10:1124

This intermittent test failure is a blocker for merging this PR.

**Comment by teor2345** [comment]
The same failure also happened in the coverage build, along with:

```
 ---- components::mempool::tests::vector::mempool_queue stdout ----
Error: 
   0: mempool storage has a cached chain rejection for any transaction with the same effects
   1: transaction evicted from the mempool due to ZIP-401 denial of service limits

Location:
   /rustc/e269e6bf47f40c9046cd44ab787881d700099252/library/core/src/result.rs:1915
```

**Comment by teor2345** [comment]
If the randomised tests are quick, we might want to run them multiple times, to make sure we catch any intermittent failures.

**Comment by conradoplg** [comment]
> If the randomised tests are quick, we might want to run them multiple times, to make sure we catch any intermittent failures.

Good idea! I did that and fixed the tests in ca217354d

**Review by dconnolly — APPROVED** [review]
I'm fine with these retries for now 👍

**Pull request merged**
