### PR TITLE
imp(ci): remove duplicated `test-fake-activation-heights` test

### PR DESCRIPTION
**Pull request by gustavovalverde**
## Motivation

`test-fake-activation-heights` should be removed from:
 https://github.com/ZcashFoundation/zebra/blob/9e0bbb5a6a41ee9549a525a45f21acf3ef3ff9c6/.github/workflows/os-build-tests.yml#L128 as we already have it here https://github.com/ZcashFoundation/zebra/blob/9e0bbb5a6a41ee9549a525a45f21acf3ef3ff9c6/.github/workflows/continous-integration.yml#L161

Depends-On: #3941

## Solution

- Remove it from the `test-os-builds.yml`

## Review

Anyone can review this

### CODE REVIEW

**Review by conradoplg — CHANGES_REQUESTED** [review]
I feel like it should be the other way around: leave it in os-build and remove from continous-integration, since it's just a unit test. Was there any particular reason for doing in this way?

**Review by teor2345 — COMMENTED** [review]
Did you also want to remove other redundant jobs in this PR?

Some steps in the `Build stable on ubuntu-latest` job are redundant, because they are covered by:
* Install zebrad from lockfile without cache on ubuntu-latest
* Test stable on ubuntu-latest

We still need to `Check Cargo.lock is up to date`, but we can remove the steps after that. (And rename the job!)

**Comment by teor2345** [comment]
Please include the clean fix #4206 when next updating this branch.

**Comment by gustavovalverde** [comment]
Closed as further decisions must be taken around this workflow

**Pull request closed without merging**
