### PR TITLE
build(deps): bump insta from 1.15.0 to 1.17.1

### PR DESCRIPTION
**Pull request by conradoplg**
## Motivation

Updating insta to 1.17.1 fails because `bind_to_thread` was depreacated (see #4844) 

## Solution

The replacement is `bind_to_scope` which returns a drop guard.

I thought of two possible approaches:

- Don't rely on a global setting anymore, and manually call `set_prepend_module_to_snapshot(false)` (the only global config we were changing) in all insta tests. Seems error-prone.
- Make `init()` return the drop guard (also `init_async`). This is more invasive since all tests must be changed, but should be less error-prone. I took this approach, but feedback is welcome.

## Review

Not urgent, anyone can review.

All changes are basically search & replace, refer to `zebra-test/src/lib.rs` to the main changes.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

**Review by teor2345 — APPROVED** [review]
Looks good, let's get it merged quickly to avoid merge conflicts.

Another alternative is to emulate the old API using `mem::forget()`.
But that might break depending on how the scope behaves when it's called multiple times without dropping.

So I prefer this alternative, and I like the way we show what's happening.

**Comment by teor2345** [comment]
This PR failed because the docker file changed, invalidating the build cache.

**Comment by teor2345** [comment]
@mergifyio update

**Review by teor2345 — APPROVED** [review]

**Comment by conradoplg** [comment]
@Mergifyio update

**Pull request merged**
