### PR TITLE
doc(ci): Fix incorrect docs about Docker build cache order

### LINKED ISSUE #5186: Docker build cache might be in the wrong order
## Motivation

The branch cache is likely to be faster and cheaper than the `main` cache, because the code is more similar:
https://github.com/ZcashFoundation/zebra/blob/202dc43b11114761068655178d73de144d18d6e0/.github/workflows/build-docker-image.yml#L142-L146

This is a medium priority, because we're trying to reduce costs.

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We want to use the branch build cache first, because the changes to a PR are usually small.
This is a comment-only PR.

Closes #5186.

### API documentation

The order and failure behaviour of caches is undocumented:
https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache

But it seems to be bottom to top, skip on failure.
(This is unusual, typically the order would be top to bottom.)

## Review

This seems to be working in the most efficient way, but the docs are wrong.

### Reviewer Checklist

  - [ ] Docs make sense

### CODE REVIEW

**Comment by teor2345** [comment]
Looking at the logs, it seems like this tries the `main-cache` first:
https://github.com/ZcashFoundation/zebra/actions/runs/3079487516/jobs/4975805832#step:9:218

So this might just need a doc update, I'll try reversing the order.

**Comment by teor2345** [comment]
> Looking at the logs, it seems like this tries the `main-cache` first: https://github.com/ZcashFoundation/zebra/actions/runs/3079487516/jobs/4975805832#step:9:218
> 
> So this might just need a doc update, I'll try reversing the order.

This order seems to work the way we want - checking the branch cache first. But annoyingly it doesn't say which cache it has used.

I'll wait for Gustavo to confirm before merging.

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
`sending_transactions_using_lightwalletd` failed due to a timing issue with the "mempool transaction broadcast" logs.

This might be fixed by PR #5134 or #5164, if not we can fix it after that.

**Comment by teor2345** [comment]
> kex_exchange_identification: read: Connection reset by peer

https://github.com/ZcashFoundation/zebra/actions/runs/3087669400/jobs/4993361663#step:6:108

Failed due to #5069

**Review by dconnolly — APPROVED** [review]

**Review by gustavovalverde — APPROVED** [review]

**Comment by teor2345** [comment]
@mergifyio update

**Comment by gustavovalverde** [comment]
Yesterday I used the wrong button here.

I was trying to add this information with the previous action https://github.com/moby/moby/pull/26839#issuecomment-277383550

**Pull request merged**
