### PR TITLE
refactor(actions): use `development` GitHub environment

### PR DESCRIPTION
**Pull request by gustavovalverde**
## Motivation

[WIP]

This PR is meant to validate the use of GitHub Environments, which should give us extra visibility when we're deploying to Mainnet, Testnet, to our development environment and later on when we're production ready and have to handle all these different environment differently.

### Specifications

https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-protection-rules

### Complex Code or Requirements

Not yet

## Review

Not ready to review

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by teor2345** [comment]
Later today or tomorrow I'll be opening a PR to generate testnet checkpoints in CI in:
https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/continous-integration-docker.yml

It could have some merge conflicts with this PR, because I'll be launching `zebrad` on mainnet and testnet in:
https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/deploy-gcp-tests.yml

I'm also thinking of splitting this job into a reusable workflow, so I can call it for mainnet and testnet:
https://github.com/ZcashFoundation/zebra/blob/ef556ea06b1072670b9215015682a45bf1362326/.github/workflows/continous-integration-docker.yml#L80-L82

How did you want to manage those merge conflicts?
Can you avoid making any testnet-related changes in this PR?

**Comment by gustavovalverde** [comment]
@teor2345 I don't think I will make those Testnet changes here. You can continue, I can handle the conflicts.

**Comment by teor2345** [comment]
> @teor2345 I don't think I will make those Testnet changes here. You can continue, I can handle the conflicts.

Sounds good!

Because testnet is unreliable, we probably won't want to run tests on it, unless we ignore the results, or the tests are only run on demand.

**Comment by gustavovalverde** [comment]
This was tested and it's no longer needed as we won't implement GitHub environments this way

**Pull request closed without merging**
