### PR TITLE
fix(test): resolve a timing issue in fake_peer_set setup

### LINKED ISSUE #5384: `fake_peer_set::mempool_requests_for_transactions` failed with Nil response
## Motivation

In PR #5383, `fake_peer_set::mempool_requests_for_transactions` failed with:
> internal error: entered unreachable code: `MempoolTransactionIds` requests should always respond `Ok(Vec<UnminedTxId>)`, got Ok(Nil)

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/5383#issuecomment-1275204946_
      

## Solution

Just allow a `Nil` response, the other tests cover this case as well.

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

To fix a mempool test that's failing occasionally.

Closes #5384

## Solution

 - Wait for AdvertiseBlock earlier (i.e. before potentially adding transactions to the mempool)

Related cleanups:
 - Replace `unreachable!(..)` with `assert!(added_transactions.is_empty(), ..)` in the `Nil` case where the response is being unwrapped with a match statement
 - Update `unreachable` and `assert` messages to say `MempoolTransactionIds` requests should respond `Ok(Vec<UnminedTxId> | Nil)`
## Review

This is low priority.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by teor2345** [comment]
@arya2 this seems to close ticket #5384, so I added it to the PR description.

Also, I think this CI failure might be a high priority, we've got multiple reports.

**Review by teor2345 — APPROVED** [review]
Let's give it a shot!

**Comment by teor2345** [comment]
This fix does not work on macOS:
> timeout while waiting for a request
> in zebra_test::mock_service::MockService<zebra_network::protocol::internal::request::Request, zebra_network::protocol::internal::response::Response, zebra_test::mock_service::PanicAssertion, alloc::boxed::Box<dyn std::error::Error+core::marker::Send+core::marker::Sync>>

https://github.com/ZcashFoundation/zebra/actions/runs/3238058141/jobs/5305848404#step:14:10158

**Review by teor2345 — CHANGES_REQUESTED** [review]
We need a fix that works on macOS, or we need to turn off this test on macOS.

**Comment by arya2** [comment]
@teor2345 Thank you for updating the PR description.

> We need a fix that works on macOS, or we need to turn off this test on macOS.

Not a MacOS-specific issue, it caused a `timeout while waiting for a request` for the `AdvertiseBlock`. I removed the wait for tip change and moved `AdvertiseBlock` above where the mempool storage is being accessed.

**Review by teor2345 — APPROVED** [review]
This seems to work now

**Pull request merged**
