### PR TITLE
fix(panic): Log a warning instead of panicking for unused mining configs

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

This PR will log a warning if there is a non-default mining section in the loaded config when compiled without the "getblocktemplate-rpcs" feature, instead of panicking.

Part of #7118.

## Solution

- Move the getblocktemplate config to `config/mining.rs`
- Log a warning when there's a mining section in a config without the getblocktemplate-rpcs feature

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Comment by oxarbitrage** [comment]
@arya2 do you need someone to finish this work ? I can find some time to bump it up if you want.

**Comment by arya2** [comment]
> @arya2 do you need someone to finish this work ? I can find some time to bump it up if you want.

Yes, please.

**Comment by teor2345** [comment]
If we make `getblocktemplate-rpcs` into a default feature, this might change priority.

**Review by teor2345 — APPROVED** [review]
Looks good, let's get it merged before any more RPC work.

I committed a quick tweak to the mining config argument passing, because we don't need to pass `()` now the confit is always enabled.

**Pull request merged**
