### PR TITLE
fix(ci): Run required jobs on dependent PRs

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

1. Some required CI jobs don't run on dependent PRs, stopping them from merging after the original PR merges
2. Some CI jobs have confusingly similar (or identical) names

## Solution

1. Make all required CI jobs run on every PR
2. Rename jobs based on the workflow name

After it has been reviewed, an admin will need to update these job names in the `main` branch protection rules:
- [x] Build CI Docker / Build images
- [x] Build lightwalletd Docker

## Review

Anyone can review this PR.

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [x] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

**Review by dconnolly — DISMISSED** [review]

**Comment by dconnolly** [comment]
> After it has been reviewed, an admin will need to update these job names in the `main` branch protection rules:
> 
> * [ ]  Build CI Docker / Build images
> * [ ]  Build lightwalletd Docker

Should we do this now or after some other label:critical PRs are merged?

**Comment by teor2345** [comment]
> > After it has been reviewed, an admin will need to update these job names in the `main` branch protection rules:
> > 
> > * [ ]   Build CI Docker / Build images
> > * [ ]   Build lightwalletd Docker
> 
> Should we do this now or after some other label:critical PRs are merged?

I'd like to make this change when this PR has been approved, and it is ready to merge, and there aren't any higher priority jobs.

Otherwise, all other PRs will block on merging the new job names to main, and re-running CI on every PR.

**Comment by teor2345** [comment]
@mergifyio update

**Comment by dconnolly** [comment]
> After it has been reviewed, an admin will need to update these job names in the `main` branch protection rules:
> 
> * [x]  Build CI Docker / Build images
> * [x]  Build lightwalletd Docker

image
✅

**Comment by dconnolly** [comment]
@teor2345 I think these are not running because paths/paths-ignore of their workflow files aren't being triggered correctly, should this be admin-merged?
image

**Comment by teor2345** [comment]
> @teor2345 I think these are not running because paths/paths-ignore of their workflow files aren't being triggered correctly, should this be admin-merged?

It seems like this PR has bugs.

Since it is not actually ready to merge, I've reverted the changes to the branch protection rules.

**Comment by teor2345** [comment]
It seems to be working fine now, but let's wait until we're both around before we try to merge it again?

**Comment by teor2345** [comment]
It looks like we won't be able to add the new job names until they run on `main`, or they run on multiple PRs. (I can't find the new job names in the branch protection rule settings.)

So I've admin-merged this PR, and we can add the new job names as other PRs update.

**Comment by teor2345** [comment]
> It looks like we won't be able to add the new job names until they run on `main`

Yep, the `main` branch merge was needed, I've added the new job names now.

**Pull request merged**
