### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by vuittont60**
fix some typos

### CODE REVIEW

**Review by teor2345 — APPROVED** [review]
Thanks for this fix!

**Comment by oxarbitrage** [comment]
Thanks @vuittont60 , i have to close this one and replace it with https://github.com/ZcashFoundation/zebra/pull/7862, which is the same code but from a branch inside the foundation repo so we can merge.

**Comment by vuittont60** [comment]
That's all right. Thank you.

**Comment by teor2345** [comment]
Failed due to #4529.

**Comment by mpguerra** [comment]
@gustavovalverde I thought we would be able to see a way to allow some jobs to run here?

**Comment by teor2345** [comment]
> @gustavovalverde I thought we would be able to see a way to allow some jobs to run here?

I already clicked the `Approve and run` button, it only needs be clicked once for every PR change.

After I clicked the button, most jobs worked, but the list I posted in #4529 didn't.

**Pull request closed without merging**
