### PR TITLE
[wip] OpenTelemetry

### PR DESCRIPTION
**Pull request by dconnolly**
## Solution

The code in this pull request has:
  - [ ] Documentation Comments
  - [ ] Unit Tests and Property Tests

### CODE REVIEW

**Comment by dconnolly** [comment]
TODO: scrap this integration in favor of building and deploying the agnostic OpenTelemetry Collector with each container:

https://opentelemetry.io/docs/collector/configuration
https://github.com/open-telemetry/opentelemetry-collector
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/stackdriverexporter
https://github.com/observatorium/opentelemetry-collector-builder

**Comment by hdevalence** [comment]
@dconnolly what does that collector expect of Zebra?

**Comment by dconnolly** [comment]
> @dconnolly what does that collector expect of Zebra?

We can use the existing Prometheus metrics endpoint as a "Receiver" for the collector, we can expose more for collecting traces, probably the open telemetry protocol (otlp) :
https://opentelemetry.io/docs/collector/configuration/#receivers

image

**Comment by dconnolly** [comment]
> > @dconnolly what does that collector expect of Zebra?
> 
> We can use the existing Prometheus metrics endpoint as a "Receiver" for the collector, we can expose more for collecting traces, probably the open telemetry protocol (otlp) :
> https://opentelemetry.io/docs/collector/configuration/#receivers

This is nice because just because we are trying to get our traces and metrics into Google Cloud/Stackdriver, doesn't mean everyone who runs Zebra cares, even if there was a nicer exporter library; exporting with OTLP/Prometheus makes zebrad more agnostic, and when we deploy it ourselves, we can use collector to export that data into whatever sinks we want.

**Comment by dconnolly** [comment]
This may be blocked by rocksdb and grpcio (dep of opentelemetry-otlp) having 'unresolvable' conflict dep on clang-sys

image

**Comment by dconnolly** [comment]
this is a pain in the ass, closing for now

**Pull request closed without merging**
