### PR TITLE
add(tests): Add snapshot tests for sprout database formats

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We're changing our database note commitment tree format code in PR #7053, but we don't have good coverage for sprout trees. (We have snapshots for the raw data, but not converting it into Zebra's data structures.)

### Reference

RocksDB Iterator Mode:
https://docs.rs/rocksdb/latest/rocksdb/enum.IteratorMode.html

Snapshot redactions:
https://insta.rs/docs/redactions/#sorted-redactions

### Complex Code or Requirements

Using database iterators like this has caused hangs before, but so far these methods are only used in tests.

## Solution

Empty Note Commitment Tree snapshot tests:
- [Add snapshot tests for sprout note commitment trees](https://github.com/ZcashFoundation/zebra/commit/1c5ffc0ba8efa302d0c7c0caf321af4303577b79)
  - [Add a method that loads all the sprout trees from the database](https://github.com/ZcashFoundation/zebra/commit/80407d87da657542ae139730d3d838329b7ed55b)
  - [Add methods for loading entire column families from the database](https://github.com/ZcashFoundation/zebra/commit/75ab951026f5e4e4001e45dc4af243a1c8b11f11)

Sprout Note Commitment Tree manual snapshot tests:
- [Add a manual sprout note commitment tree database serialization snapshot test](https://github.com/ZcashFoundation/zebra/pull/7057/commits/9395ccd9f448314f1073b9428772a0b403c7ed93)
- [Add tests for 1,2,4,8 note commitments in a tree](https://github.com/ZcashFoundation/zebra/pull/7057/commits/98c9e31d6556632279a412ff4686e7e1fbb36be7)
- [Randomly cache roots rather than only caching even roots](https://github.com/ZcashFoundation/zebra/pull/7057/commits/f0abd7c218c328a1d61eead7c5b8ed71fe58eed2)

Tree Root tests:
- [Add round-trip proptests for tree root database serialization](https://github.com/ZcashFoundation/zebra/pull/7057/commits/38921413397c8951969f8b23ea3506a92dc514a3)

Related Fixes:
- [Remove redundant "rand" package rename in dependencies](https://github.com/ZcashFoundation/zebra/pull/7057/commits/10f08568089fd46a7c605fe258a1d72ea17fa797)

## Review

@oxarbitrage might find this handy for testing PR #7053.

### Reviewer Checklist

  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

We still don't have some snapshot tests for the entire database, or for some shielded data. (We only use 10 blocks, but the first Sprout transaction is after 100+ blocks.)

We can add them as we change the database format.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
Failed by [container issue](https://github.com/ZcashFoundation/zebra/actions/runs/5353701092/jobs/9711239936?pr=7057). Restarting all jobs

**Comment by teor2345** [comment]
> Failed by [container issue](https://github.com/ZcashFoundation/zebra/actions/runs/5353701092/jobs/9711239936?pr=7057). Restarting all jobs

It first failed at the create instance stage:
> ERROR: (gcloud.compute.instances.create-with-container) Could not fetch resource:
>  <title>Error 502 (Server Error)!!1</title>
>  <p><b>502.</b> <ins>That’s an error.</ins>
>  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

https://github.com/ZcashFoundation/zebra/actions/runs/5353701092/jobs/9711197294?pr=7057#step:11:91

**Comment by teor2345** [comment]
@mergifyio update

**Review by oxarbitrage — APPROVED** [review]
This looks and works very good, it will be needed to test the ECC dependency upgrades of https://github.com/ZcashFoundation/zebra/pull/7053

**Pull request merged**
