### PR TITLE
Create zebrad debian package

### LINKED ISSUE #562: systemd service file
We should consider writing and shipping a systemd service file for zebrad.  This isn't a high priority but it would be nice to have before we do a release.

### PR DESCRIPTION
**Pull request by oxarbitrage**
The following will use [cargo deb](https://github.com/mmstick/cargo-deb) to build a debian package.

If your system dont have `cargo deb` please first do:

`cargo install cargo-deb`

In a zebra directory build the  dpkg with:

`cargo build && cargo deb -p zebrad`

Install:

`sudo dpkg -i target/debian/zebrad_3.0.0~alpha.0_amd64.deb`

Manage:

```
systemctl status zebrad
sudo systemctl stop zebrad
```

Logs:

`journalctl -u zebrad.service`

Uninstall:

` sudo dpkg --purge zebrad`

References:

- https://github.com/vasilakisfil/hello.service
- https://github.com/mmstick/cargo-deb/blob/HEAD/systemd.md

If merged will close https://github.com/ZcashFoundation/zebra/issues/562

### CODE REVIEW

**Comment by dconnolly** [comment]
My first instinct is that we don't want to do this yet, to save all packaging/release decisions for when we are preparing for our first major version release. 

// @chelseakomlo @teor2345 @yaahc @hdevalence

**Comment by hdevalence** [comment]
Yes, let's wait to do any release planning work until after the basic functionality is finished.

**Comment by oxarbitrage** [comment]
Ok, i didn't knew that, sorry. I think we can keep it open(maybe with a blocked tag) for when that time comes.

**Comment by yaahc** [comment]
Side note, I'm really impressed by how concise and short this change is. Thank you for setting it up.

**Comment by hdevalence** [comment]
This is related to #562; I wonder whether we could extract the systemd service file from this PR and merge it in advance as a general-purpose `.service` file rather than a debian-specific one.

**Comment by teor2345** [comment]
> I wonder whether we could extract the systemd service file from this PR and merge it in advance as a general-purpose `.service` file rather than a debian-specific one.

I'm not an expert in systemd configs, but it doesn't look like there is anything Debian-specific in the file.

It might be helpful to document that it is a "minimal" config. In my experience, distribution-specific changes to service configs can break other distributions. So we should maintain a config that is as minimal and generic as possible, and let distributions add their own custom configs.

I'm not sure if this line is standard:
```
WorkingDirectory=~
```

The others look pretty generic.

**Comment by teor2345** [comment]
Another general release management question:

Should we include packaging info in this repository, or create distribution-specific forks?

If we create a fork, we can modify the generic service file for Debian.

If we don't create a fork, let's avoid making a copy of the generic file - instead, let's create a patch with any Debian-specific changes.

That way, we don't have to remember to keep the files in sync.

**Comment by dconnolly** [comment]
@oxarbitrage can we make the service file generic for system.d not just Debian?

**Comment by oxarbitrage** [comment]
Replaced by https://github.com/ZcashFoundation/zebra/pull/1161

Opened new PR as i wanted to change the branch name from `debian` to `zebrad_service` and that seems not possible. Closing this one.

**Pull request closed without merging**
